/// D4rt GEN-079 Relaxer Wrappers for tom_d4rt_dcli
///
/// Auto-generated wrapper classes and factory functions for generic
/// type relaxation. These enable `extractBridgedArg<Base<Arg>>` to
/// succeed when the runtime value has `<dynamic>` type arguments.
///
/// DO NOT EDIT — generated by d4rtgen relaxer generator.
library;

// ignore_for_file: unused_import, invalid_implementation_override, deprecated_member_use, sort_child_properties_last, invalid_use_of_protected_member, unnecessary_non_null_assertion, invalid_use_of_visible_for_testing_member


// GEN-095: No relaxers or RC-2 generic constructors are reachable
// via this package's barrel imports. Emitting empty stubs so the
// orchestrator's `registerRelaxers()` / `registerGenericConstructors()`
// calls still resolve.

/// No-op: no GEN-079 relaxer wrappers for this package.
void registerRelaxers() {}

/// No-op: no RC-2 generic constructor factories for this package.
void registerGenericConstructors() {}
