# Build configuration for tom_d4rt_astgen
#
# This registers the astgen builder that can be used by other packages.
# Version generation is configured in tom_build.yaml.

builders:
  astgen:
    import: "package:tom_d4rt_astgen/builder.dart"
    builder_factories: ["astgenBuilder"]
    build_extensions:
      r"$lib$": [".astgen.done"]
    auto_apply: none
    build_to: source
