/// D4rt Proxy Classes for flutter_material_bridges
///
/// Generated proxy/adapter subclasses that delegate abstract methods
/// to callback functions, enabling D4rt scripts to implement
/// abstract delegates.
///
/// DO NOT EDIT — generated by d4rtgen proxy generator.
library;

// ignore_for_file: unused_import, invalid_use_of_protected_member, unnecessary_non_null_assertion, invalid_use_of_visible_for_testing_member

import 'package:flutter/material.dart';
import 'package:flutter/painting.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/services.dart';
import 'package:flutter/widgets.dart';
import 'package:tom_d4rt_exec/d4rt.dart';

/// D4rt proxy for [CustomPainter].
///
/// Delegates abstract methods to callback functions, enabling
/// D4rt scripts to implement [CustomPainter] via named
/// function parameters.
class D4rtCustomPainter extends CustomPainter {
  /// Callback for [CustomPainter.paint].
  final void Function(Canvas, Size) onPaint;

  /// Callback for [CustomPainter.shouldRepaint].
  final bool Function(CustomPainter) onShouldRepaint;

  /// Callback for [CustomPainter.addListener].
  final void Function(VoidCallback)? onAddListener;

  /// Callback for [CustomPainter.removeListener].
  final void Function(VoidCallback)? onRemoveListener;

  /// Callback for [CustomPainter.shouldRebuildSemantics].
  final bool Function(CustomPainter)? onShouldRebuildSemantics;

  /// Callback for [CustomPainter.hitTest].
  final bool? Function(Offset)? onHitTest;

  /// Callback for [CustomPainter.semanticsBuilder].
  final SemanticsBuilderCallback? Function()? onSemanticsBuilder;

  /// Creates a [D4rtCustomPainter] with callback implementations.
  D4rtCustomPainter({
    required this.onPaint,
    required this.onShouldRepaint,
    this.onAddListener,
    this.onRemoveListener,
    this.onShouldRebuildSemantics,
    this.onHitTest,
    this.onSemanticsBuilder,
  });

  @override
  void paint(Canvas canvas, Size size) =>
      onPaint(canvas, size);

  @override
  bool shouldRepaint(CustomPainter oldDelegate) =>
      onShouldRepaint(oldDelegate);

  @override
  void addListener(VoidCallback listener) =>
      onAddListener != null ? onAddListener!(listener) : super.addListener(listener);

  @override
  void removeListener(VoidCallback listener) =>
      onRemoveListener != null ? onRemoveListener!(listener) : super.removeListener(listener);

  @override
  bool shouldRebuildSemantics(CustomPainter oldDelegate) =>
      onShouldRebuildSemantics != null ? onShouldRebuildSemantics!(oldDelegate) : super.shouldRebuildSemantics(oldDelegate);

  @override
  bool? hitTest(Offset position) =>
      onHitTest != null ? onHitTest!(position) : super.hitTest(position);

  @override
  SemanticsBuilderCallback? get semanticsBuilder => onSemanticsBuilder != null ? onSemanticsBuilder!() : super.semanticsBuilder;

}

/// D4rt proxy for [CustomClipper].
///
/// Delegates abstract methods to callback functions, enabling
/// D4rt scripts to implement [CustomClipper] via named
/// function parameters.
class D4rtCustomClipper<T> extends CustomClipper<T> {
  /// Callback for [CustomClipper.getClip].
  final T Function(Size) onGetClip;

  /// Callback for [CustomClipper.shouldReclip].
  final bool Function(CustomClipper<T>) onShouldReclip;

  /// Callback for [CustomClipper.addListener].
  final void Function(VoidCallback)? onAddListener;

  /// Callback for [CustomClipper.removeListener].
  final void Function(VoidCallback)? onRemoveListener;

  /// Callback for [CustomClipper.getApproximateClipRect].
  final Rect Function(Size)? onGetApproximateClipRect;

  /// Creates a [D4rtCustomClipper] with callback implementations.
  D4rtCustomClipper({
    required this.onGetClip,
    required this.onShouldReclip,
    this.onAddListener,
    this.onRemoveListener,
    this.onGetApproximateClipRect,
  });

  @override
  T getClip(Size size) =>
      onGetClip(size);

  @override
  bool shouldReclip(CustomClipper<T> oldClipper) =>
      onShouldReclip(oldClipper);

  @override
  void addListener(VoidCallback listener) =>
      onAddListener != null ? onAddListener!(listener) : super.addListener(listener);

  @override
  void removeListener(VoidCallback listener) =>
      onRemoveListener != null ? onRemoveListener!(listener) : super.removeListener(listener);

  @override
  Rect getApproximateClipRect(Size size) =>
      onGetApproximateClipRect != null ? onGetApproximateClipRect!(size) : super.getApproximateClipRect(size);

}

/// D4rt proxy for [FlowDelegate].
///
/// Delegates abstract methods to callback functions, enabling
/// D4rt scripts to implement [FlowDelegate] via named
/// function parameters.
class D4rtFlowDelegate extends FlowDelegate {
  /// Callback for [FlowDelegate.paintChildren].
  final void Function(FlowPaintingContext) onPaintChildren;

  /// Callback for [FlowDelegate.shouldRepaint].
  final bool Function(FlowDelegate) onShouldRepaint;

  /// Callback for [FlowDelegate.getSize].
  final Size Function(BoxConstraints)? onGetSize;

  /// Callback for [FlowDelegate.getConstraintsForChild].
  final BoxConstraints Function(int, BoxConstraints)? onGetConstraintsForChild;

  /// Callback for [FlowDelegate.shouldRelayout].
  final bool Function(FlowDelegate)? onShouldRelayout;

  /// Creates a [D4rtFlowDelegate] with callback implementations.
  D4rtFlowDelegate({
    required this.onPaintChildren,
    required this.onShouldRepaint,
    this.onGetSize,
    this.onGetConstraintsForChild,
    this.onShouldRelayout,
  });

  @override
  void paintChildren(FlowPaintingContext context) =>
      onPaintChildren(context);

  @override
  bool shouldRepaint(FlowDelegate oldDelegate) =>
      onShouldRepaint(oldDelegate);

  @override
  Size getSize(BoxConstraints constraints) =>
      onGetSize != null ? onGetSize!(constraints) : super.getSize(constraints);

  @override
  BoxConstraints getConstraintsForChild(int i, BoxConstraints constraints) =>
      onGetConstraintsForChild != null ? onGetConstraintsForChild!(i, constraints) : super.getConstraintsForChild(i, constraints);

  @override
  bool shouldRelayout(FlowDelegate oldDelegate) =>
      onShouldRelayout != null ? onShouldRelayout!(oldDelegate) : super.shouldRelayout(oldDelegate);

}

/// D4rt proxy for [MultiChildLayoutDelegate].
///
/// Delegates abstract methods to callback functions, enabling
/// D4rt scripts to implement [MultiChildLayoutDelegate] via named
/// function parameters.
class D4rtMultiChildLayoutDelegate extends MultiChildLayoutDelegate {
  /// Callback for [MultiChildLayoutDelegate.performLayout].
  final void Function(Size) onPerformLayout;

  /// Callback for [MultiChildLayoutDelegate.shouldRelayout].
  final bool Function(MultiChildLayoutDelegate) onShouldRelayout;

  /// Callback for [MultiChildLayoutDelegate.hasChild].
  final bool Function(Object)? onHasChild;

  /// Callback for [MultiChildLayoutDelegate.layoutChild].
  final Size Function(Object, BoxConstraints)? onLayoutChild;

  /// Callback for [MultiChildLayoutDelegate.positionChild].
  final void Function(Object, Offset)? onPositionChild;

  /// Callback for [MultiChildLayoutDelegate.getSize].
  final Size Function(BoxConstraints)? onGetSize;

  /// Creates a [D4rtMultiChildLayoutDelegate] with callback implementations.
  D4rtMultiChildLayoutDelegate({
    required this.onPerformLayout,
    required this.onShouldRelayout,
    this.onHasChild,
    this.onLayoutChild,
    this.onPositionChild,
    this.onGetSize,
  });

  @override
  void performLayout(Size size) =>
      onPerformLayout(size);

  @override
  bool shouldRelayout(MultiChildLayoutDelegate oldDelegate) =>
      onShouldRelayout(oldDelegate);

  @override
  bool hasChild(Object childId) =>
      onHasChild != null ? onHasChild!(childId) : super.hasChild(childId);

  @override
  Size layoutChild(Object childId, BoxConstraints constraints) =>
      onLayoutChild != null ? onLayoutChild!(childId, constraints) : super.layoutChild(childId, constraints);

  @override
  void positionChild(Object childId, Offset offset) =>
      onPositionChild != null ? onPositionChild!(childId, offset) : super.positionChild(childId, offset);

  @override
  Size getSize(BoxConstraints constraints) =>
      onGetSize != null ? onGetSize!(constraints) : super.getSize(constraints);

}

/// D4rt proxy for [SingleChildLayoutDelegate].
///
/// Delegates abstract methods to callback functions, enabling
/// D4rt scripts to implement [SingleChildLayoutDelegate] via named
/// function parameters.
class D4rtSingleChildLayoutDelegate extends SingleChildLayoutDelegate {
  /// Callback for [SingleChildLayoutDelegate.shouldRelayout].
  final bool Function(SingleChildLayoutDelegate) onShouldRelayout;

  /// Callback for [SingleChildLayoutDelegate.getSize].
  final Size Function(BoxConstraints)? onGetSize;

  /// Callback for [SingleChildLayoutDelegate.getConstraintsForChild].
  final BoxConstraints Function(BoxConstraints)? onGetConstraintsForChild;

  /// Callback for [SingleChildLayoutDelegate.getPositionForChild].
  final Offset Function(Size, Size)? onGetPositionForChild;

  /// Creates a [D4rtSingleChildLayoutDelegate] with callback implementations.
  D4rtSingleChildLayoutDelegate({
    required this.onShouldRelayout,
    this.onGetSize,
    this.onGetConstraintsForChild,
    this.onGetPositionForChild,
  });

  @override
  bool shouldRelayout(SingleChildLayoutDelegate oldDelegate) =>
      onShouldRelayout(oldDelegate);

  @override
  Size getSize(BoxConstraints constraints) =>
      onGetSize != null ? onGetSize!(constraints) : super.getSize(constraints);

  @override
  BoxConstraints getConstraintsForChild(BoxConstraints constraints) =>
      onGetConstraintsForChild != null ? onGetConstraintsForChild!(constraints) : super.getConstraintsForChild(constraints);

  @override
  Offset getPositionForChild(Size size, Size childSize) =>
      onGetPositionForChild != null ? onGetPositionForChild!(size, childSize) : super.getPositionForChild(size, childSize);

}

/// D4rt proxy for [SliverPersistentHeaderDelegate].
///
/// Delegates abstract methods to callback functions, enabling
/// D4rt scripts to implement [SliverPersistentHeaderDelegate] via named
/// function parameters.
class D4rtSliverPersistentHeaderDelegate extends SliverPersistentHeaderDelegate {
  /// Callback for [SliverPersistentHeaderDelegate.build].
  final Widget Function(BuildContext, double, bool) onBuild;

  /// Callback for [SliverPersistentHeaderDelegate.shouldRebuild].
  final bool Function(SliverPersistentHeaderDelegate) onShouldRebuild;

  /// Callback for [SliverPersistentHeaderDelegate.minExtent].
  final double Function() onMinExtent;

  /// Callback for [SliverPersistentHeaderDelegate.maxExtent].
  final double Function() onMaxExtent;

  /// Callback for [SliverPersistentHeaderDelegate.vsync].
  final TickerProvider? Function()? onVsync;

  /// Callback for [SliverPersistentHeaderDelegate.snapConfiguration].
  final FloatingHeaderSnapConfiguration? Function()? onSnapConfiguration;

  /// Callback for [SliverPersistentHeaderDelegate.stretchConfiguration].
  final OverScrollHeaderStretchConfiguration? Function()? onStretchConfiguration;

  /// Callback for [SliverPersistentHeaderDelegate.showOnScreenConfiguration].
  final PersistentHeaderShowOnScreenConfiguration? Function()? onShowOnScreenConfiguration;

  /// Creates a [D4rtSliverPersistentHeaderDelegate] with callback implementations.
  D4rtSliverPersistentHeaderDelegate({
    required this.onBuild,
    required this.onShouldRebuild,
    required this.onMinExtent,
    required this.onMaxExtent,
    this.onVsync,
    this.onSnapConfiguration,
    this.onStretchConfiguration,
    this.onShowOnScreenConfiguration,
  });

  @override
  Widget build(BuildContext context, double shrinkOffset, bool overlapsContent) =>
      onBuild(context, shrinkOffset, overlapsContent);

  @override
  bool shouldRebuild(SliverPersistentHeaderDelegate oldDelegate) =>
      onShouldRebuild(oldDelegate);

  @override
  double get minExtent => onMinExtent();

  @override
  double get maxExtent => onMaxExtent();

  @override
  TickerProvider? get vsync => onVsync != null ? onVsync!() : super.vsync;

  @override
  FloatingHeaderSnapConfiguration? get snapConfiguration => onSnapConfiguration != null ? onSnapConfiguration!() : super.snapConfiguration;

  @override
  OverScrollHeaderStretchConfiguration? get stretchConfiguration => onStretchConfiguration != null ? onStretchConfiguration!() : super.stretchConfiguration;

  @override
  PersistentHeaderShowOnScreenConfiguration? get showOnScreenConfiguration => onShowOnScreenConfiguration != null ? onShowOnScreenConfiguration!() : super.showOnScreenConfiguration;

}

/// D4rt proxy for [DataTableSource].
///
/// Delegates abstract methods to callback functions, enabling
/// D4rt scripts to implement [DataTableSource] via named
/// function parameters.
class D4rtDataTableSource extends DataTableSource {
  /// Callback for [DataTableSource.getRow].
  final DataRow? Function(int) onGetRow;

  /// Callback for [DataTableSource.rowCount].
  final int Function() onRowCount;

  /// Callback for [DataTableSource.isRowCountApproximate].
  final bool Function() onIsRowCountApproximate;

  /// Callback for [DataTableSource.selectedRowCount].
  final int Function() onSelectedRowCount;

  /// Callback for [DataTableSource.addListener].
  final void Function(VoidCallback)? onAddListener;

  /// Callback for [DataTableSource.removeListener].
  final void Function(VoidCallback)? onRemoveListener;

  /// Callback for [DataTableSource.dispose].
  final void Function()? onDispose;

  /// Callback for [DataTableSource.notifyListeners].
  final void Function()? onNotifyListeners;

  /// Callback for [DataTableSource.hasListeners].
  final bool Function()? onHasListeners;

  /// Creates a [D4rtDataTableSource] with callback implementations.
  D4rtDataTableSource({
    required this.onGetRow,
    required this.onRowCount,
    required this.onIsRowCountApproximate,
    required this.onSelectedRowCount,
    this.onAddListener,
    this.onRemoveListener,
    this.onDispose,
    this.onNotifyListeners,
    this.onHasListeners,
  });

  @override
  DataRow? getRow(int index) =>
      onGetRow(index);

  @override
  int get rowCount => onRowCount();

  @override
  bool get isRowCountApproximate => onIsRowCountApproximate();

  @override
  int get selectedRowCount => onSelectedRowCount();

  @override
  void addListener(VoidCallback listener) =>
      onAddListener != null ? onAddListener!(listener) : super.addListener(listener);

  @override
  void removeListener(VoidCallback listener) =>
      onRemoveListener != null ? onRemoveListener!(listener) : super.removeListener(listener);

  @override
  void dispose() =>
      onDispose != null ? onDispose!() : super.dispose();

  @override
  void notifyListeners() =>
      onNotifyListeners != null ? onNotifyListeners!() : super.notifyListeners();

  @override
  bool get hasListeners => onHasListeners != null ? onHasListeners!() : super.hasListeners;

}

/// D4rt proxy for [TransitionDelegate].
///
/// Delegates abstract methods to callback functions, enabling
/// D4rt scripts to implement [TransitionDelegate] via named
/// function parameters.
class D4rtTransitionDelegate<T> extends TransitionDelegate<T> {
  /// Callback for [TransitionDelegate.resolve].
  final Iterable<RouteTransitionRecord> Function({required List<RouteTransitionRecord> newPageRouteHistory, required Map<RouteTransitionRecord?, RouteTransitionRecord> locationToExitingPageRoute, required Map<RouteTransitionRecord?, List<RouteTransitionRecord>> pageRouteToPagelessRoutes}) onResolve;

  /// Creates a [D4rtTransitionDelegate] with callback implementations.
  D4rtTransitionDelegate({
    required this.onResolve,
  });

  @override
  Iterable<RouteTransitionRecord> resolve({required List<RouteTransitionRecord> newPageRouteHistory, required Map<RouteTransitionRecord?, RouteTransitionRecord> locationToExitingPageRoute, required Map<RouteTransitionRecord?, List<RouteTransitionRecord>> pageRouteToPagelessRoutes}) =>
      onResolve(newPageRouteHistory: newPageRouteHistory, locationToExitingPageRoute: locationToExitingPageRoute, pageRouteToPagelessRoutes: pageRouteToPagelessRoutes);

}

/// D4rt proxy for [GradientTransform].
///
/// Delegates abstract methods to callback functions, enabling
/// D4rt scripts to implement [GradientTransform] via named
/// function parameters.
class D4rtGradientTransform extends GradientTransform {
  /// Callback for [GradientTransform.transform].
  final Matrix4? Function(Rect, {TextDirection? textDirection}) onTransform;

  /// Creates a [D4rtGradientTransform] with callback implementations.
  D4rtGradientTransform({
    required this.onTransform,
  });

  @override
  Matrix4? transform(Rect bounds, {TextDirection? textDirection}) =>
      onTransform(bounds, textDirection: textDirection);

}

/// D4rt proxy for [SliderComponentShape].
///
/// Delegates abstract methods to callback functions, enabling
/// D4rt scripts to implement [SliderComponentShape] via named
/// function parameters.
class D4rtSliderComponentShape extends SliderComponentShape {
  /// Callback for [SliderComponentShape.getPreferredSize].
  final Size Function(bool, bool) onGetPreferredSize;

  /// Callback for [SliderComponentShape.paint].
  final void Function(PaintingContext, Offset, {required Animation<double> activationAnimation, required Animation<double> enableAnimation, required bool isDiscrete, required TextPainter labelPainter, required RenderBox parentBox, required SliderThemeData sliderTheme, required TextDirection textDirection, required double value, required double textScaleFactor, required Size sizeWithOverflow}) onPaint;

  /// Creates a [D4rtSliderComponentShape] with callback implementations.
  D4rtSliderComponentShape({
    required this.onGetPreferredSize,
    required this.onPaint,
  });

  @override
  Size getPreferredSize(bool isEnabled, bool isDiscrete) =>
      onGetPreferredSize(isEnabled, isDiscrete);

  @override
  void paint(PaintingContext context, Offset center, {required Animation<double> activationAnimation, required Animation<double> enableAnimation, required bool isDiscrete, required TextPainter labelPainter, required RenderBox parentBox, required SliderThemeData sliderTheme, required TextDirection textDirection, required double value, required double textScaleFactor, required Size sizeWithOverflow}) =>
      onPaint(context, center, activationAnimation: activationAnimation, enableAnimation: enableAnimation, isDiscrete: isDiscrete, labelPainter: labelPainter, parentBox: parentBox, sliderTheme: sliderTheme, textDirection: textDirection, value: value, textScaleFactor: textScaleFactor, sizeWithOverflow: sizeWithOverflow);

}

/// D4rt proxy for [SpellCheckService].
///
/// Delegates abstract methods to callback functions, enabling
/// D4rt scripts to implement [SpellCheckService] via named
/// function parameters.
class D4rtSpellCheckService extends SpellCheckService {
  /// Callback for [SpellCheckService.fetchSpellCheckSuggestions].
  final Future<List<SuggestionSpan>?> Function(Locale, String) onFetchSpellCheckSuggestions;

  /// Creates a [D4rtSpellCheckService] with callback implementations.
  D4rtSpellCheckService({
    required this.onFetchSpellCheckSuggestions,
  });

  @override
  Future<List<SuggestionSpan>?> fetchSpellCheckSuggestions(Locale locale, String text) =>
      onFetchSpellCheckSuggestions(locale, text);

}

/// D4rt proxy for [Decoration].
///
/// Delegates abstract methods to callback functions, enabling
/// D4rt scripts to implement [Decoration] via named
/// function parameters.
class D4rtDecoration extends Decoration {
  /// Callback for [Decoration.createBoxPainter].
  final BoxPainter Function(VoidCallback?) onCreateBoxPainter;

  /// Callback for [Decoration.toStringShort].
  final String Function()? onToStringShort;

  /// Callback for [Decoration.debugAssertIsValid].
  final bool Function()? onDebugAssertIsValid;

  /// Callback for [Decoration.lerpFrom].
  final Decoration? Function(Decoration?, double)? onLerpFrom;

  /// Callback for [Decoration.lerpTo].
  final Decoration? Function(Decoration?, double)? onLerpTo;

  /// Callback for [Decoration.hitTest].
  final bool Function(Size, Offset, {TextDirection? textDirection})? onHitTest;

  /// Callback for [Decoration.getClipPath].
  final Path Function(Rect, TextDirection)? onGetClipPath;

  /// Callback for [Decoration.padding].
  final EdgeInsetsGeometry Function()? onPadding;

  /// Callback for [Decoration.isComplex].
  final bool Function()? onIsComplex;

  /// Creates a [D4rtDecoration] with callback implementations.
  D4rtDecoration({
    required this.onCreateBoxPainter,
    this.onToStringShort,
    this.onDebugAssertIsValid,
    this.onLerpFrom,
    this.onLerpTo,
    this.onHitTest,
    this.onGetClipPath,
    this.onPadding,
    this.onIsComplex,
  });

  @override
  BoxPainter createBoxPainter([VoidCallback? onChanged]) =>
      onCreateBoxPainter(onChanged);

  @override
  String toStringShort() =>
      onToStringShort != null ? onToStringShort!() : super.toStringShort();

  @override
  bool debugAssertIsValid() =>
      onDebugAssertIsValid != null ? onDebugAssertIsValid!() : super.debugAssertIsValid();

  @override
  Decoration? lerpFrom(Decoration? a, double t) =>
      onLerpFrom != null ? onLerpFrom!(a, t) : super.lerpFrom(a, t);

  @override
  Decoration? lerpTo(Decoration? b, double t) =>
      onLerpTo != null ? onLerpTo!(b, t) : super.lerpTo(b, t);

  @override
  bool hitTest(Size size, Offset position, {TextDirection? textDirection}) =>
      onHitTest != null ? onHitTest!(size, position, textDirection: textDirection) : super.hitTest(size, position, textDirection: textDirection);

  @override
  Path getClipPath(Rect rect, TextDirection textDirection) =>
      onGetClipPath != null ? onGetClipPath!(rect, textDirection) : super.getClipPath(rect, textDirection);

  @override
  EdgeInsetsGeometry get padding => onPadding != null ? onPadding!() : super.padding;

  @override
  bool get isComplex => onIsComplex != null ? onIsComplex!() : super.isComplex;

}

/// D4rt proxy for [BoxPainter].
///
/// Delegates abstract methods to callback functions, enabling
/// D4rt scripts to implement [BoxPainter] via named
/// function parameters.
class D4rtBoxPainter extends BoxPainter {
  /// Callback for [BoxPainter.paint].
  final void Function(Canvas, Offset, ImageConfiguration) onPaint;

  /// Callback for [BoxPainter.dispose].
  final void Function()? onDispose;

  /// Creates a [D4rtBoxPainter] with callback implementations.
  D4rtBoxPainter({
    required this.onPaint,
    this.onDispose,
  });

  @override
  void paint(Canvas canvas, Offset offset, ImageConfiguration configuration) =>
      onPaint(canvas, offset, configuration);

  @override
  void dispose() =>
      onDispose != null ? onDispose!() : super.dispose();

}

/// D4rt proxy for [RouteInformationParser].
///
/// Delegates abstract methods to callback functions, enabling
/// D4rt scripts to implement [RouteInformationParser] via named
/// function parameters.
class D4rtRouteInformationParser<T> extends RouteInformationParser<T> {
  /// Callback for [RouteInformationParser.parseRouteInformation].
  final Future<T> Function(RouteInformation)? onParseRouteInformation;

  /// Callback for [RouteInformationParser.parseRouteInformationWithDependencies].
  final Future<T> Function(RouteInformation, BuildContext)? onParseRouteInformationWithDependencies;

  /// Callback for [RouteInformationParser.restoreRouteInformation].
  final RouteInformation? Function(T)? onRestoreRouteInformation;

  /// Creates a [D4rtRouteInformationParser] with callback implementations.
  D4rtRouteInformationParser({
    this.onParseRouteInformation,
    this.onParseRouteInformationWithDependencies,
    this.onRestoreRouteInformation,
  });

  @override
  Future<T> parseRouteInformation(RouteInformation routeInformation) =>
      onParseRouteInformation != null ? onParseRouteInformation!(routeInformation) : super.parseRouteInformation(routeInformation);

  @override
  Future<T> parseRouteInformationWithDependencies(RouteInformation routeInformation, BuildContext context) =>
      onParseRouteInformationWithDependencies != null ? onParseRouteInformationWithDependencies!(routeInformation, context) : super.parseRouteInformationWithDependencies(routeInformation, context);

  @override
  RouteInformation? restoreRouteInformation(T configuration) =>
      onRestoreRouteInformation != null ? onRestoreRouteInformation!(configuration) : super.restoreRouteInformation(configuration);

}

/// D4rt proxy for [RouterDelegate].
///
/// Delegates abstract methods to callback functions, enabling
/// D4rt scripts to implement [RouterDelegate] via named
/// function parameters.
class D4rtRouterDelegate<T> extends RouterDelegate<T> {
  /// Callback for [RouterDelegate.setNewRoutePath].
  final Future<void> Function(T) onSetNewRoutePath;

  /// Callback for [RouterDelegate.popRoute].
  final Future<bool> Function() onPopRoute;

  /// Callback for [RouterDelegate.build].
  final Widget Function(BuildContext) onBuild;

  /// Callback for [RouterDelegate.addListener].
  final void Function(VoidCallback) onAddListener;

  /// Callback for [RouterDelegate.removeListener].
  final void Function(VoidCallback) onRemoveListener;

  /// Callback for [RouterDelegate.setInitialRoutePath].
  final Future<void> Function(T)? onSetInitialRoutePath;

  /// Callback for [RouterDelegate.setRestoredRoutePath].
  final Future<void> Function(T)? onSetRestoredRoutePath;

  /// Callback for [RouterDelegate.currentConfiguration].
  final T? Function()? onCurrentConfiguration;

  /// Creates a [D4rtRouterDelegate] with callback implementations.
  D4rtRouterDelegate({
    required this.onSetNewRoutePath,
    required this.onPopRoute,
    required this.onBuild,
    required this.onAddListener,
    required this.onRemoveListener,
    this.onSetInitialRoutePath,
    this.onSetRestoredRoutePath,
    this.onCurrentConfiguration,
  });

  @override
  Future<void> setNewRoutePath(T configuration) =>
      onSetNewRoutePath(configuration);

  @override
  Future<bool> popRoute() =>
      onPopRoute();

  @override
  Widget build(BuildContext context) =>
      onBuild(context);

  @override
  void addListener(VoidCallback listener) =>
      onAddListener(listener);

  @override
  void removeListener(VoidCallback listener) =>
      onRemoveListener(listener);

  @override
  Future<void> setInitialRoutePath(T configuration) =>
      onSetInitialRoutePath != null ? onSetInitialRoutePath!(configuration) : super.setInitialRoutePath(configuration);

  @override
  Future<void> setRestoredRoutePath(T configuration) =>
      onSetRestoredRoutePath != null ? onSetRestoredRoutePath!(configuration) : super.setRestoredRoutePath(configuration);

  @override
  T? get currentConfiguration => onCurrentConfiguration != null ? onCurrentConfiguration!() : super.currentConfiguration;

}

// =========================================================================
// Proxy Factory Registration (GEN-092)
// =========================================================================

/// Registers interface proxy factories for all generated proxy classes.
///
/// Call this during bridge initialization to enable D4rt scripts to
/// create interpreted subclasses of these abstract classes.
/// Each factory bridges InterpretedInstance method calls to native
/// proxy callbacks.
void registerProxyFactories() {
  // Register factory for CustomPainter
  D4.registerInterfaceProxy('CustomPainter', (visitor, instance) {
    return D4rtCustomPainter(
      onPaint: (Canvas canvas, Size size) {
        final method = instance.klass.findInstanceMethod('paint');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [canvas, size], {});
          return;
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement paint');
      },
      onShouldRepaint: (CustomPainter oldDelegate) {
        final method = instance.klass.findInstanceMethod('shouldRepaint');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [oldDelegate], {});
           return D4.extractBridgedArg<bool>(result, 'shouldRepaint', visitor);
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement shouldRepaint');
      },
      onAddListener: instance.klass.findInstanceMethod('addListener') != null
          ? (VoidCallback listener) {
        final method = instance.klass.findInstanceMethod('addListener');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [listener], {});
          return;
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement addListener');
          }
          : null,
      onRemoveListener: instance.klass.findInstanceMethod('removeListener') != null
          ? (VoidCallback listener) {
        final method = instance.klass.findInstanceMethod('removeListener');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [listener], {});
          return;
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement removeListener');
          }
          : null,
      onShouldRebuildSemantics: instance.klass.findInstanceMethod('shouldRebuildSemantics') != null
          ? (CustomPainter oldDelegate) {
        final method = instance.klass.findInstanceMethod('shouldRebuildSemantics');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [oldDelegate], {});
           return D4.extractBridgedArg<bool>(result, 'shouldRebuildSemantics', visitor);
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement shouldRebuildSemantics');
          }
          : null,
      onHitTest: instance.klass.findInstanceMethod('hitTest') != null
          ? (Offset position) {
        final method = instance.klass.findInstanceMethod('hitTest');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [position], {});
           return D4.extractBridgedArg<bool?>(result, 'hitTest', visitor);
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement hitTest');
          }
          : null,
      onSemanticsBuilder: instance.klass.findInstanceGetter('semanticsBuilder') != null
          ? () {
        final getter = instance.klass.findInstanceGetter('semanticsBuilder');
        if (getter != null) {
          final result = getter.bind(instance).call(visitor, [], {});
           if (result == null) return null;
           if (result is Callable) {
             final _callable = result;
             return (Size p0) {
               final _out = _callable.call(visitor, [p0], {});
               if (_out is List) {
                 return _out.map((e) => D4.extractBridgedArg<CustomPainterSemantics>(e, 'semanticsBuilder', visitor)).toList();
               }
               return D4.extractBridgedArg<List<CustomPainterSemantics>>(_out, 'semanticsBuilder', visitor);
             };
           }
           return D4.extractBridgedArg<List<CustomPainterSemantics> Function(Size size)?>(result, 'semanticsBuilder', visitor);
        }
        try {
          final field = instance.getField('semanticsBuilder');
           if (field == null) return null;
           if (field is Callable) {
             final _callable = field;
             return (Size p0) {
               final _out = _callable.call(visitor, [p0], {});
               if (_out is List) {
                 return _out.map((e) => D4.extractBridgedArg<CustomPainterSemantics>(e, 'semanticsBuilder', visitor)).toList();
               }
               return D4.extractBridgedArg<List<CustomPainterSemantics>>(_out, 'semanticsBuilder', visitor);
             };
           }
           return D4.extractBridgedArg<List<CustomPainterSemantics> Function(Size size)?>(field, 'semanticsBuilder', visitor);
        } catch (_) {}
        throw StateError('Interpreted class ${instance.klass.name} does not implement semanticsBuilder');
          }
          : null,
    );
  });

  // Register factory for CustomClipper
  D4.registerInterfaceProxy('CustomClipper', (visitor, instance) {
    return D4rtCustomClipper<Object>(
      onGetClip: (Size size) {
        final method = instance.klass.findInstanceMethod('getClip');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [size], {});
           return D4.extractBridgedArg<Object>(result, 'getClip', visitor);
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement getClip');
      },
      onShouldReclip: (CustomClipper<Object> oldClipper) {
        final method = instance.klass.findInstanceMethod('shouldReclip');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [oldClipper], {});
           return D4.extractBridgedArg<bool>(result, 'shouldReclip', visitor);
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement shouldReclip');
      },
      onAddListener: instance.klass.findInstanceMethod('addListener') != null
          ? (VoidCallback listener) {
        final method = instance.klass.findInstanceMethod('addListener');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [listener], {});
          return;
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement addListener');
          }
          : null,
      onRemoveListener: instance.klass.findInstanceMethod('removeListener') != null
          ? (VoidCallback listener) {
        final method = instance.klass.findInstanceMethod('removeListener');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [listener], {});
          return;
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement removeListener');
          }
          : null,
      onGetApproximateClipRect: instance.klass.findInstanceMethod('getApproximateClipRect') != null
          ? (Size size) {
        final method = instance.klass.findInstanceMethod('getApproximateClipRect');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [size], {});
           return D4.extractBridgedArg<Rect>(result, 'getApproximateClipRect', visitor);
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement getApproximateClipRect');
          }
          : null,
    );
  });

  // Register factory for FlowDelegate
  D4.registerInterfaceProxy('FlowDelegate', (visitor, instance) {
    return D4rtFlowDelegate(
      onPaintChildren: (FlowPaintingContext context) {
        final method = instance.klass.findInstanceMethod('paintChildren');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [context], {});
          return;
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement paintChildren');
      },
      onShouldRepaint: (FlowDelegate oldDelegate) {
        final method = instance.klass.findInstanceMethod('shouldRepaint');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [oldDelegate], {});
           return D4.extractBridgedArg<bool>(result, 'shouldRepaint', visitor);
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement shouldRepaint');
      },
      onGetSize: instance.klass.findInstanceMethod('getSize') != null
          ? (BoxConstraints constraints) {
        final method = instance.klass.findInstanceMethod('getSize');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [constraints], {});
           return D4.extractBridgedArg<Size>(result, 'getSize', visitor);
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement getSize');
          }
          : null,
      onGetConstraintsForChild: instance.klass.findInstanceMethod('getConstraintsForChild') != null
          ? (int i, BoxConstraints constraints) {
        final method = instance.klass.findInstanceMethod('getConstraintsForChild');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [i, constraints], {});
           return D4.extractBridgedArg<BoxConstraints>(result, 'getConstraintsForChild', visitor);
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement getConstraintsForChild');
          }
          : null,
      onShouldRelayout: instance.klass.findInstanceMethod('shouldRelayout') != null
          ? (FlowDelegate oldDelegate) {
        final method = instance.klass.findInstanceMethod('shouldRelayout');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [oldDelegate], {});
           return D4.extractBridgedArg<bool>(result, 'shouldRelayout', visitor);
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement shouldRelayout');
          }
          : null,
    );
  });

  // Register factory for MultiChildLayoutDelegate
  D4.registerInterfaceProxy('MultiChildLayoutDelegate', (visitor, instance) {
    return D4rtMultiChildLayoutDelegate(
      onPerformLayout: (Size size) {
        final method = instance.klass.findInstanceMethod('performLayout');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [size], {});
          return;
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement performLayout');
      },
      onShouldRelayout: (MultiChildLayoutDelegate oldDelegate) {
        final method = instance.klass.findInstanceMethod('shouldRelayout');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [oldDelegate], {});
           return D4.extractBridgedArg<bool>(result, 'shouldRelayout', visitor);
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement shouldRelayout');
      },
      onHasChild: instance.klass.findInstanceMethod('hasChild') != null
          ? (Object childId) {
        final method = instance.klass.findInstanceMethod('hasChild');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [childId], {});
           return D4.extractBridgedArg<bool>(result, 'hasChild', visitor);
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement hasChild');
          }
          : null,
      onLayoutChild: instance.klass.findInstanceMethod('layoutChild') != null
          ? (Object childId, BoxConstraints constraints) {
        final method = instance.klass.findInstanceMethod('layoutChild');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [childId, constraints], {});
           return D4.extractBridgedArg<Size>(result, 'layoutChild', visitor);
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement layoutChild');
          }
          : null,
      onPositionChild: instance.klass.findInstanceMethod('positionChild') != null
          ? (Object childId, Offset offset) {
        final method = instance.klass.findInstanceMethod('positionChild');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [childId, offset], {});
          return;
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement positionChild');
          }
          : null,
      onGetSize: instance.klass.findInstanceMethod('getSize') != null
          ? (BoxConstraints constraints) {
        final method = instance.klass.findInstanceMethod('getSize');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [constraints], {});
           return D4.extractBridgedArg<Size>(result, 'getSize', visitor);
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement getSize');
          }
          : null,
    );
  });

  // Register factory for SingleChildLayoutDelegate
  D4.registerInterfaceProxy('SingleChildLayoutDelegate', (visitor, instance) {
    return D4rtSingleChildLayoutDelegate(
      onShouldRelayout: (SingleChildLayoutDelegate oldDelegate) {
        final method = instance.klass.findInstanceMethod('shouldRelayout');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [oldDelegate], {});
           return D4.extractBridgedArg<bool>(result, 'shouldRelayout', visitor);
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement shouldRelayout');
      },
      onGetSize: instance.klass.findInstanceMethod('getSize') != null
          ? (BoxConstraints constraints) {
        final method = instance.klass.findInstanceMethod('getSize');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [constraints], {});
           return D4.extractBridgedArg<Size>(result, 'getSize', visitor);
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement getSize');
          }
          : null,
      onGetConstraintsForChild: instance.klass.findInstanceMethod('getConstraintsForChild') != null
          ? (BoxConstraints constraints) {
        final method = instance.klass.findInstanceMethod('getConstraintsForChild');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [constraints], {});
           return D4.extractBridgedArg<BoxConstraints>(result, 'getConstraintsForChild', visitor);
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement getConstraintsForChild');
          }
          : null,
      onGetPositionForChild: instance.klass.findInstanceMethod('getPositionForChild') != null
          ? (Size size, Size childSize) {
        final method = instance.klass.findInstanceMethod('getPositionForChild');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [size, childSize], {});
           return D4.extractBridgedArg<Offset>(result, 'getPositionForChild', visitor);
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement getPositionForChild');
          }
          : null,
    );
  });

  // Register factory for SliverPersistentHeaderDelegate
  D4.registerInterfaceProxy('SliverPersistentHeaderDelegate', (visitor, instance) {
    return D4rtSliverPersistentHeaderDelegate(
      onBuild: (BuildContext context, double shrinkOffset, bool overlapsContent) {
        final method = instance.klass.findInstanceMethod('build');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [context, shrinkOffset, overlapsContent], {});
           return D4.extractBridgedArg<Widget>(result, 'build', visitor);
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement build');
      },
      onShouldRebuild: (SliverPersistentHeaderDelegate oldDelegate) {
        final method = instance.klass.findInstanceMethod('shouldRebuild');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [oldDelegate], {});
           return D4.extractBridgedArg<bool>(result, 'shouldRebuild', visitor);
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement shouldRebuild');
      },
      onMinExtent: () {
        final getter = instance.klass.findInstanceGetter('minExtent');
        if (getter != null) {
          final result = getter.bind(instance).call(visitor, [], {});
           return D4.extractBridgedArg<double>(result, 'minExtent', visitor);
        }
        try {
          final field = instance.getField('minExtent');
           return D4.extractBridgedArg<double>(field, 'minExtent', visitor);
        } catch (_) {}
        throw StateError('Interpreted class ${instance.klass.name} does not implement minExtent');
      },
      onMaxExtent: () {
        final getter = instance.klass.findInstanceGetter('maxExtent');
        if (getter != null) {
          final result = getter.bind(instance).call(visitor, [], {});
           return D4.extractBridgedArg<double>(result, 'maxExtent', visitor);
        }
        try {
          final field = instance.getField('maxExtent');
           return D4.extractBridgedArg<double>(field, 'maxExtent', visitor);
        } catch (_) {}
        throw StateError('Interpreted class ${instance.klass.name} does not implement maxExtent');
      },
      onVsync: instance.klass.findInstanceGetter('vsync') != null
          ? () {
        final getter = instance.klass.findInstanceGetter('vsync');
        if (getter != null) {
          final result = getter.bind(instance).call(visitor, [], {});
           return D4.extractBridgedArg<TickerProvider?>(result, 'vsync', visitor);
        }
        try {
          final field = instance.getField('vsync');
           return D4.extractBridgedArg<TickerProvider?>(field, 'vsync', visitor);
        } catch (_) {}
        throw StateError('Interpreted class ${instance.klass.name} does not implement vsync');
          }
          : null,
      onSnapConfiguration: instance.klass.findInstanceGetter('snapConfiguration') != null
          ? () {
        final getter = instance.klass.findInstanceGetter('snapConfiguration');
        if (getter != null) {
          final result = getter.bind(instance).call(visitor, [], {});
           return D4.extractBridgedArg<FloatingHeaderSnapConfiguration?>(result, 'snapConfiguration', visitor);
        }
        try {
          final field = instance.getField('snapConfiguration');
           return D4.extractBridgedArg<FloatingHeaderSnapConfiguration?>(field, 'snapConfiguration', visitor);
        } catch (_) {}
        throw StateError('Interpreted class ${instance.klass.name} does not implement snapConfiguration');
          }
          : null,
      onStretchConfiguration: instance.klass.findInstanceGetter('stretchConfiguration') != null
          ? () {
        final getter = instance.klass.findInstanceGetter('stretchConfiguration');
        if (getter != null) {
          final result = getter.bind(instance).call(visitor, [], {});
           return D4.extractBridgedArg<OverScrollHeaderStretchConfiguration?>(result, 'stretchConfiguration', visitor);
        }
        try {
          final field = instance.getField('stretchConfiguration');
           return D4.extractBridgedArg<OverScrollHeaderStretchConfiguration?>(field, 'stretchConfiguration', visitor);
        } catch (_) {}
        throw StateError('Interpreted class ${instance.klass.name} does not implement stretchConfiguration');
          }
          : null,
      onShowOnScreenConfiguration: instance.klass.findInstanceGetter('showOnScreenConfiguration') != null
          ? () {
        final getter = instance.klass.findInstanceGetter('showOnScreenConfiguration');
        if (getter != null) {
          final result = getter.bind(instance).call(visitor, [], {});
           return D4.extractBridgedArg<PersistentHeaderShowOnScreenConfiguration?>(result, 'showOnScreenConfiguration', visitor);
        }
        try {
          final field = instance.getField('showOnScreenConfiguration');
           return D4.extractBridgedArg<PersistentHeaderShowOnScreenConfiguration?>(field, 'showOnScreenConfiguration', visitor);
        } catch (_) {}
        throw StateError('Interpreted class ${instance.klass.name} does not implement showOnScreenConfiguration');
          }
          : null,
    );
  });

  // Register factory for DataTableSource
  D4.registerInterfaceProxy('DataTableSource', (visitor, instance) {
    return D4rtDataTableSource(
      onGetRow: (int index) {
        final method = instance.klass.findInstanceMethod('getRow');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [index], {});
           return D4.extractBridgedArg<DataRow?>(result, 'getRow', visitor);
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement getRow');
      },
      onRowCount: () {
        final getter = instance.klass.findInstanceGetter('rowCount');
        if (getter != null) {
          final result = getter.bind(instance).call(visitor, [], {});
           return D4.extractBridgedArg<int>(result, 'rowCount', visitor);
        }
        try {
          final field = instance.getField('rowCount');
           return D4.extractBridgedArg<int>(field, 'rowCount', visitor);
        } catch (_) {}
        throw StateError('Interpreted class ${instance.klass.name} does not implement rowCount');
      },
      onIsRowCountApproximate: () {
        final getter = instance.klass.findInstanceGetter('isRowCountApproximate');
        if (getter != null) {
          final result = getter.bind(instance).call(visitor, [], {});
           return D4.extractBridgedArg<bool>(result, 'isRowCountApproximate', visitor);
        }
        try {
          final field = instance.getField('isRowCountApproximate');
           return D4.extractBridgedArg<bool>(field, 'isRowCountApproximate', visitor);
        } catch (_) {}
        throw StateError('Interpreted class ${instance.klass.name} does not implement isRowCountApproximate');
      },
      onSelectedRowCount: () {
        final getter = instance.klass.findInstanceGetter('selectedRowCount');
        if (getter != null) {
          final result = getter.bind(instance).call(visitor, [], {});
           return D4.extractBridgedArg<int>(result, 'selectedRowCount', visitor);
        }
        try {
          final field = instance.getField('selectedRowCount');
           return D4.extractBridgedArg<int>(field, 'selectedRowCount', visitor);
        } catch (_) {}
        throw StateError('Interpreted class ${instance.klass.name} does not implement selectedRowCount');
      },
      onAddListener: instance.klass.findInstanceMethod('addListener') != null
          ? (VoidCallback listener) {
        final method = instance.klass.findInstanceMethod('addListener');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [listener], {});
          return;
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement addListener');
          }
          : null,
      onRemoveListener: instance.klass.findInstanceMethod('removeListener') != null
          ? (VoidCallback listener) {
        final method = instance.klass.findInstanceMethod('removeListener');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [listener], {});
          return;
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement removeListener');
          }
          : null,
      onDispose: instance.klass.findInstanceMethod('dispose') != null
          ? () {
        final method = instance.klass.findInstanceMethod('dispose');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [], {});
          return;
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement dispose');
          }
          : null,
      onNotifyListeners: instance.klass.findInstanceMethod('notifyListeners') != null
          ? () {
        final method = instance.klass.findInstanceMethod('notifyListeners');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [], {});
          return;
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement notifyListeners');
          }
          : null,
      onHasListeners: instance.klass.findInstanceGetter('hasListeners') != null
          ? () {
        final getter = instance.klass.findInstanceGetter('hasListeners');
        if (getter != null) {
          final result = getter.bind(instance).call(visitor, [], {});
           return D4.extractBridgedArg<bool>(result, 'hasListeners', visitor);
        }
        try {
          final field = instance.getField('hasListeners');
           return D4.extractBridgedArg<bool>(field, 'hasListeners', visitor);
        } catch (_) {}
        throw StateError('Interpreted class ${instance.klass.name} does not implement hasListeners');
          }
          : null,
    );
  });

  // Register factory for TransitionDelegate
  D4.registerInterfaceProxy('TransitionDelegate', (visitor, instance) {
    return D4rtTransitionDelegate<Object>(
      onResolve: ({required List<RouteTransitionRecord> newPageRouteHistory, required Map<RouteTransitionRecord?, RouteTransitionRecord> locationToExitingPageRoute, required Map<RouteTransitionRecord?, List<RouteTransitionRecord>> pageRouteToPagelessRoutes}) {
        final method = instance.klass.findInstanceMethod('resolve');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [], {'newPageRouteHistory': newPageRouteHistory, 'locationToExitingPageRoute': locationToExitingPageRoute, 'pageRouteToPagelessRoutes': pageRouteToPagelessRoutes});
           return D4.extractBridgedArg<Iterable<RouteTransitionRecord>>(result, 'resolve', visitor);
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement resolve');
      },
    );
  });

  // Register factory for GradientTransform
  D4.registerInterfaceProxy('GradientTransform', (visitor, instance) {
    return D4rtGradientTransform(
      onTransform: (Rect bounds, {TextDirection? textDirection}) {
        final method = instance.klass.findInstanceMethod('transform');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [bounds], {'textDirection': textDirection});
           return D4.extractBridgedArg<Matrix4?>(result, 'transform', visitor);
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement transform');
      },
    );
  });

  // Register factory for SliderComponentShape
  D4.registerInterfaceProxy('SliderComponentShape', (visitor, instance) {
    return D4rtSliderComponentShape(
      onGetPreferredSize: (bool isEnabled, bool isDiscrete) {
        final method = instance.klass.findInstanceMethod('getPreferredSize');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [isEnabled, isDiscrete], {});
           return D4.extractBridgedArg<Size>(result, 'getPreferredSize', visitor);
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement getPreferredSize');
      },
      onPaint: (PaintingContext context, Offset center, {required Animation<double> activationAnimation, required Animation<double> enableAnimation, required bool isDiscrete, required TextPainter labelPainter, required RenderBox parentBox, required SliderThemeData sliderTheme, required TextDirection textDirection, required double value, required double textScaleFactor, required Size sizeWithOverflow}) {
        final method = instance.klass.findInstanceMethod('paint');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [context, center], {'activationAnimation': activationAnimation, 'enableAnimation': enableAnimation, 'isDiscrete': isDiscrete, 'labelPainter': labelPainter, 'parentBox': parentBox, 'sliderTheme': sliderTheme, 'textDirection': textDirection, 'value': value, 'textScaleFactor': textScaleFactor, 'sizeWithOverflow': sizeWithOverflow});
          return;
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement paint');
      },
    );
  });

  // Register factory for SpellCheckService
  D4.registerInterfaceProxy('SpellCheckService', (visitor, instance) {
    return D4rtSpellCheckService(
      onFetchSpellCheckSuggestions: (Locale locale, String text) {
        final method = instance.klass.findInstanceMethod('fetchSpellCheckSuggestions');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [locale, text], {});
           return D4.extractBridgedArg<Future<List<SuggestionSpan>?>>(result, 'fetchSpellCheckSuggestions', visitor);
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement fetchSpellCheckSuggestions');
      },
    );
  });

  // Register factory for Decoration
  D4.registerInterfaceProxy('Decoration', (visitor, instance) {
    return D4rtDecoration(
      onCreateBoxPainter: ([VoidCallback? onChanged]) {
        final method = instance.klass.findInstanceMethod('createBoxPainter');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [onChanged], {});
           return D4.extractBridgedArg<BoxPainter>(result, 'createBoxPainter', visitor);
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement createBoxPainter');
      },
      onToStringShort: instance.klass.findInstanceMethod('toStringShort') != null
          ? () {
        final method = instance.klass.findInstanceMethod('toStringShort');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [], {});
           return D4.extractBridgedArg<String>(result, 'toStringShort', visitor);
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement toStringShort');
          }
          : null,
      onDebugAssertIsValid: instance.klass.findInstanceMethod('debugAssertIsValid') != null
          ? () {
        final method = instance.klass.findInstanceMethod('debugAssertIsValid');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [], {});
           return D4.extractBridgedArg<bool>(result, 'debugAssertIsValid', visitor);
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement debugAssertIsValid');
          }
          : null,
      onLerpFrom: instance.klass.findInstanceMethod('lerpFrom') != null
          ? (Decoration? a, double t) {
        final method = instance.klass.findInstanceMethod('lerpFrom');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [a, t], {});
           return D4.extractBridgedArg<Decoration?>(result, 'lerpFrom', visitor);
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement lerpFrom');
          }
          : null,
      onLerpTo: instance.klass.findInstanceMethod('lerpTo') != null
          ? (Decoration? b, double t) {
        final method = instance.klass.findInstanceMethod('lerpTo');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [b, t], {});
           return D4.extractBridgedArg<Decoration?>(result, 'lerpTo', visitor);
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement lerpTo');
          }
          : null,
      onHitTest: instance.klass.findInstanceMethod('hitTest') != null
          ? (Size size, Offset position, {TextDirection? textDirection}) {
        final method = instance.klass.findInstanceMethod('hitTest');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [size, position], {'textDirection': textDirection});
           return D4.extractBridgedArg<bool>(result, 'hitTest', visitor);
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement hitTest');
          }
          : null,
      onGetClipPath: instance.klass.findInstanceMethod('getClipPath') != null
          ? (Rect rect, TextDirection textDirection) {
        final method = instance.klass.findInstanceMethod('getClipPath');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [rect, textDirection], {});
           return D4.extractBridgedArg<Path>(result, 'getClipPath', visitor);
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement getClipPath');
          }
          : null,
      onPadding: instance.klass.findInstanceGetter('padding') != null
          ? () {
        final getter = instance.klass.findInstanceGetter('padding');
        if (getter != null) {
          final result = getter.bind(instance).call(visitor, [], {});
           return D4.extractBridgedArg<EdgeInsetsGeometry>(result, 'padding', visitor);
        }
        try {
          final field = instance.getField('padding');
           return D4.extractBridgedArg<EdgeInsetsGeometry>(field, 'padding', visitor);
        } catch (_) {}
        throw StateError('Interpreted class ${instance.klass.name} does not implement padding');
          }
          : null,
      onIsComplex: instance.klass.findInstanceGetter('isComplex') != null
          ? () {
        final getter = instance.klass.findInstanceGetter('isComplex');
        if (getter != null) {
          final result = getter.bind(instance).call(visitor, [], {});
           return D4.extractBridgedArg<bool>(result, 'isComplex', visitor);
        }
        try {
          final field = instance.getField('isComplex');
           return D4.extractBridgedArg<bool>(field, 'isComplex', visitor);
        } catch (_) {}
        throw StateError('Interpreted class ${instance.klass.name} does not implement isComplex');
          }
          : null,
    );
  });

  // Register factory for BoxPainter
  D4.registerInterfaceProxy('BoxPainter', (visitor, instance) {
    return D4rtBoxPainter(
      onPaint: (Canvas canvas, Offset offset, ImageConfiguration configuration) {
        final method = instance.klass.findInstanceMethod('paint');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [canvas, offset, configuration], {});
          return;
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement paint');
      },
      onDispose: instance.klass.findInstanceMethod('dispose') != null
          ? () {
        final method = instance.klass.findInstanceMethod('dispose');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [], {});
          return;
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement dispose');
          }
          : null,
    );
  });

  // Register factory for RouteInformationParser
  D4.registerInterfaceProxy('RouteInformationParser', (visitor, instance) {
    return D4rtRouteInformationParser<Object>(
      onParseRouteInformation: instance.klass.findInstanceMethod('parseRouteInformation') != null
          ? (RouteInformation routeInformation) {
        final method = instance.klass.findInstanceMethod('parseRouteInformation');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [routeInformation], {});
           return D4.extractBridgedArg<Future<Object>>(result, 'parseRouteInformation', visitor);
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement parseRouteInformation');
          }
          : null,
      onParseRouteInformationWithDependencies: instance.klass.findInstanceMethod('parseRouteInformationWithDependencies') != null
          ? (RouteInformation routeInformation, BuildContext context) {
        final method = instance.klass.findInstanceMethod('parseRouteInformationWithDependencies');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [routeInformation, context], {});
           return D4.extractBridgedArg<Future<Object>>(result, 'parseRouteInformationWithDependencies', visitor);
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement parseRouteInformationWithDependencies');
          }
          : null,
      onRestoreRouteInformation: instance.klass.findInstanceMethod('restoreRouteInformation') != null
          ? (Object configuration) {
        final method = instance.klass.findInstanceMethod('restoreRouteInformation');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [configuration], {});
           return D4.extractBridgedArg<RouteInformation?>(result, 'restoreRouteInformation', visitor);
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement restoreRouteInformation');
          }
          : null,
    );
  });

  // Register factory for RouterDelegate
  D4.registerInterfaceProxy('RouterDelegate', (visitor, instance) {
    return D4rtRouterDelegate<Object>(
      onSetNewRoutePath: (Object configuration) {
        final method = instance.klass.findInstanceMethod('setNewRoutePath');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [configuration], {});
           return D4.extractBridgedArg<Future<void>>(result, 'setNewRoutePath', visitor);
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement setNewRoutePath');
      },
      onPopRoute: () {
        final method = instance.klass.findInstanceMethod('popRoute');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [], {});
           return D4.extractBridgedArg<Future<bool>>(result, 'popRoute', visitor);
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement popRoute');
      },
      onBuild: (BuildContext context) {
        final method = instance.klass.findInstanceMethod('build');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [context], {});
           return D4.extractBridgedArg<Widget>(result, 'build', visitor);
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement build');
      },
      onAddListener: (VoidCallback listener) {
        final method = instance.klass.findInstanceMethod('addListener');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [listener], {});
          return;
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement addListener');
      },
      onRemoveListener: (VoidCallback listener) {
        final method = instance.klass.findInstanceMethod('removeListener');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [listener], {});
          return;
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement removeListener');
      },
      onSetInitialRoutePath: instance.klass.findInstanceMethod('setInitialRoutePath') != null
          ? (Object configuration) {
        final method = instance.klass.findInstanceMethod('setInitialRoutePath');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [configuration], {});
           return D4.extractBridgedArg<Future<void>>(result, 'setInitialRoutePath', visitor);
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement setInitialRoutePath');
          }
          : null,
      onSetRestoredRoutePath: instance.klass.findInstanceMethod('setRestoredRoutePath') != null
          ? (Object configuration) {
        final method = instance.klass.findInstanceMethod('setRestoredRoutePath');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [configuration], {});
           return D4.extractBridgedArg<Future<void>>(result, 'setRestoredRoutePath', visitor);
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement setRestoredRoutePath');
          }
          : null,
      onCurrentConfiguration: instance.klass.findInstanceGetter('currentConfiguration') != null
          ? () {
        final getter = instance.klass.findInstanceGetter('currentConfiguration');
        if (getter != null) {
          final result = getter.bind(instance).call(visitor, [], {});
           return D4.extractBridgedArg<Object?>(result, 'currentConfiguration', visitor);
        }
        try {
          final field = instance.getField('currentConfiguration');
           return D4.extractBridgedArg<Object?>(field, 'currentConfiguration', visitor);
        } catch (_) {}
        throw StateError('Interpreted class ${instance.klass.name} does not implement currentConfiguration');
          }
          : null,
    );
  });

}

