/// D4rt Proxy Classes for flutter_material_bridges
///
/// Generated proxy/adapter subclasses that delegate abstract methods
/// to callback functions, enabling D4rt scripts to implement
/// abstract delegates.
///
/// DO NOT EDIT — generated by d4rtgen proxy generator.
library;

// ignore_for_file: unused_import

import 'package:flutter/rendering.dart';

/// D4rt proxy for [CustomPainter].
///
/// Delegates abstract methods to callback functions, enabling
/// D4rt scripts to implement [CustomPainter] via named
/// function parameters.
class D4rtCustomPainter extends CustomPainter {
  /// Callback for [CustomPainter.paint].
  final void Function(Canvas, Size) onPaint;

  /// Callback for [CustomPainter.shouldRepaint].
  final bool Function(CustomPainter) onShouldRepaint;

  /// Creates a [D4rtCustomPainter] with callback implementations.
  D4rtCustomPainter({required this.onPaint, required this.onShouldRepaint});

  @override
  void paint(Canvas canvas, Size size) => onPaint(canvas, size);

  @override
  bool shouldRepaint(CustomPainter oldDelegate) => onShouldRepaint(oldDelegate);
}

/// D4rt proxy for [CustomClipper].
///
/// Delegates abstract methods to callback functions, enabling
/// D4rt scripts to implement [CustomClipper] via named
/// function parameters.
class D4rtCustomClipper<T> extends CustomClipper<T> {
  /// Callback for [CustomClipper.getClip].
  final T Function(Size) onGetClip;

  /// Callback for [CustomClipper.shouldReclip].
  final bool Function(CustomClipper<T>) onShouldReclip;

  /// Creates a [D4rtCustomClipper] with callback implementations.
  D4rtCustomClipper({required this.onGetClip, required this.onShouldReclip});

  @override
  T getClip(Size size) => onGetClip(size);

  @override
  bool shouldReclip(CustomClipper<T> oldClipper) => onShouldReclip(oldClipper);
}

/// D4rt proxy for [FlowDelegate].
///
/// Delegates abstract methods to callback functions, enabling
/// D4rt scripts to implement [FlowDelegate] via named
/// function parameters.
class D4rtFlowDelegate extends FlowDelegate {
  /// Callback for [FlowDelegate.paintChildren].
  final void Function(FlowPaintingContext) onPaintChildren;

  /// Callback for [FlowDelegate.shouldRepaint].
  final bool Function(FlowDelegate) onShouldRepaint;

  /// Creates a [D4rtFlowDelegate] with callback implementations.
  D4rtFlowDelegate({
    required this.onPaintChildren,
    required this.onShouldRepaint,
  });

  @override
  void paintChildren(FlowPaintingContext context) => onPaintChildren(context);

  @override
  bool shouldRepaint(FlowDelegate oldDelegate) => onShouldRepaint(oldDelegate);
}

/// D4rt proxy for [MultiChildLayoutDelegate].
///
/// Delegates abstract methods to callback functions, enabling
/// D4rt scripts to implement [MultiChildLayoutDelegate] via named
/// function parameters.
class D4rtMultiChildLayoutDelegate extends MultiChildLayoutDelegate {
  /// Callback for [MultiChildLayoutDelegate.performLayout].
  final void Function(Size) onPerformLayout;

  /// Callback for [MultiChildLayoutDelegate.shouldRelayout].
  final bool Function(MultiChildLayoutDelegate) onShouldRelayout;

  /// Creates a [D4rtMultiChildLayoutDelegate] with callback implementations.
  D4rtMultiChildLayoutDelegate({
    required this.onPerformLayout,
    required this.onShouldRelayout,
  });

  @override
  void performLayout(Size size) => onPerformLayout(size);

  @override
  bool shouldRelayout(MultiChildLayoutDelegate oldDelegate) =>
      onShouldRelayout(oldDelegate);
}

/// D4rt proxy for [SingleChildLayoutDelegate].
///
/// Delegates abstract methods to callback functions, enabling
/// D4rt scripts to implement [SingleChildLayoutDelegate] via named
/// function parameters.
///
/// [onShouldRelayout] is required (abstract in base class).
/// [onGetConstraintsForChild], [onGetPositionForChild], and [onGetSize]
/// are optional — when omitted, the base-class defaults are used.
class D4rtSingleChildLayoutDelegate extends SingleChildLayoutDelegate {
  /// Callback for [SingleChildLayoutDelegate.shouldRelayout].
  final bool Function(SingleChildLayoutDelegate) onShouldRelayout;

  /// Optional callback for [SingleChildLayoutDelegate.getConstraintsForChild].
  /// When null, defaults to passing through the incoming constraints.
  final BoxConstraints Function(BoxConstraints)? onGetConstraintsForChild;

  /// Optional callback for [SingleChildLayoutDelegate.getPositionForChild].
  /// When null, defaults to [Offset.zero].
  final Offset Function(Size, Size)? onGetPositionForChild;

  /// Optional callback for [SingleChildLayoutDelegate.getSize].
  /// When null, defaults to [constraints.biggest].
  final Size Function(BoxConstraints)? onGetSize;

  /// Creates a [D4rtSingleChildLayoutDelegate] with callback implementations.
  D4rtSingleChildLayoutDelegate({
    required this.onShouldRelayout,
    this.onGetConstraintsForChild,
    this.onGetPositionForChild,
    this.onGetSize,
  });

  @override
  bool shouldRelayout(SingleChildLayoutDelegate oldDelegate) =>
      onShouldRelayout(oldDelegate);

  @override
  BoxConstraints getConstraintsForChild(BoxConstraints constraints) =>
      onGetConstraintsForChild != null
      ? onGetConstraintsForChild!(constraints)
      : super.getConstraintsForChild(constraints);

  @override
  Offset getPositionForChild(Size size, Size childSize) =>
      onGetPositionForChild != null
      ? onGetPositionForChild!(size, childSize)
      : super.getPositionForChild(size, childSize);

  @override
  Size getSize(BoxConstraints constraints) =>
      onGetSize != null ? onGetSize!(constraints) : super.getSize(constraints);
}
