/// D4rt GEN-079 Relaxer Wrappers for flutter_material_bridges
///
/// Auto-generated wrapper classes and factory functions for generic
/// type relaxation. These enable `extractBridgedArg<Base<Arg>>` to
/// succeed when the runtime value has `<dynamic>` type arguments.
///
/// DO NOT EDIT — generated by d4rtgen relaxer generator.
library;

// ignore_for_file: unused_import
// ignore_for_file: invalid_implementation_override

import 'package:tom_d4rt_exec/d4rt.dart' show D4;

import 'dart:ui';

import 'package:flutter/animation.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:flutter/painting.dart';
import 'package:flutter/physics.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/scheduler.dart';
import 'package:flutter/semantics.dart';
import 'package:flutter/services.dart';
import 'package:flutter/widgets.dart';

// ---------------------------------------------------------------------------
// $RelaxedAbstractLayoutBuilder
// ---------------------------------------------------------------------------

/// Auto-generated GEN-079 relaxer wrapper for AbstractLayoutBuilder<V>.
class $RelaxedAbstractLayoutBuilder<V> implements AbstractLayoutBuilder<V> {
  final AbstractLayoutBuilder _inner;

  $RelaxedAbstractLayoutBuilder(this._inner);

  @override
  dynamic noSuchMethod(Invocation invocation) =>
    super.noSuchMethod(invocation);

  @override
  String toString({dynamic minLevel}) =>
    _inner.toString();

  @override
  Widget Function(BuildContext context, V layoutInfo) get builder => _inner.builder as Widget Function(BuildContext context, V layoutInfo);

  @override
  RenderAbstractLayoutBuilderMixin<V, RenderObject> createRenderObject(BuildContext context) => _inner.createRenderObject(context) as RenderAbstractLayoutBuilderMixin<V, RenderObject>;

  @override
  bool updateShouldRebuild(AbstractLayoutBuilder<V> oldWidget) => _inner.updateShouldRebuild(oldWidget);

}


// ---------------------------------------------------------------------------
// $RelaxedAction
// ---------------------------------------------------------------------------

/// Auto-generated GEN-079 relaxer wrapper for Action<V>.
class $RelaxedAction<V extends Intent> implements Action<V> {
  final Action _inner;

  $RelaxedAction(this._inner);

  @override
  dynamic noSuchMethod(Invocation invocation) =>
    super.noSuchMethod(invocation);

  @override
  String toString({dynamic minLevel}) =>
    _inner.toString();

  @override
  Action<V>? get callingAction => _inner.callingAction as Action<V>?;

  @override
  bool isEnabled(V intent) => _inner.isEnabled(intent);

  @override
  bool consumesKey(V intent) => _inner.consumesKey(intent);

  @override
  KeyEventResult toKeyEventResult(V intent, Object? invokeResult) => _inner.toKeyEventResult(intent, invokeResult);

  @override
  Object? invoke(V intent) => _inner.invoke(intent);

}


// ---------------------------------------------------------------------------
// $RelaxedAdaptation
// ---------------------------------------------------------------------------

/// Auto-generated GEN-079 relaxer wrapper for Adaptation<V>.
class $RelaxedAdaptation<V> extends Adaptation<V> {
  final Adaptation _inner;

  $RelaxedAdaptation(this._inner);

  @override
  V adapt(ThemeData theme, V defaultValue) => _inner.adapt(theme, defaultValue) as V;
}


// ---------------------------------------------------------------------------
// $RelaxedAnimatable
// ---------------------------------------------------------------------------

/// Auto-generated GEN-079 relaxer wrapper for Animatable<V>.
class $RelaxedAnimatable<V> implements Animatable<V> {
  final Animatable _inner;

  $RelaxedAnimatable(this._inner);

  @override
  dynamic noSuchMethod(Invocation invocation) =>
    super.noSuchMethod(invocation);

  @override
  V transform(double t) => _inner.transform(t) as V;

  @override
  V evaluate(Animation<double> animation) => _inner.evaluate(animation) as V;

  @override
  Animation<V> animate(Animation<double> parent) => _inner.animate(parent) as Animation<V>;

  @override
  Animatable<V> chain(Animatable<double> parent) => _inner.chain(parent) as Animatable<V>;

}


// ---------------------------------------------------------------------------
// $RelaxedAnimation
// ---------------------------------------------------------------------------

/// Auto-generated GEN-079 relaxer wrapper for Animation<V>.
class $RelaxedAnimation<V> implements Animation<V> {
  final Animation _inner;

  $RelaxedAnimation(this._inner);

  @override
  dynamic noSuchMethod(Invocation invocation) =>
    super.noSuchMethod(invocation);

  @override
  V get value => _inner.value as V;

}


// ---------------------------------------------------------------------------
// $RelaxedAnnotationResult
// ---------------------------------------------------------------------------

/// Auto-generated GEN-079 relaxer wrapper for AnnotationResult<V>.
class $RelaxedAnnotationResult<V> extends AnnotationResult<V> {
  final AnnotationResult _inner;

  $RelaxedAnnotationResult(this._inner);

  @override
  Iterable<AnnotationEntry<V>> get entries => _inner.entries as Iterable<AnnotationEntry<V>>;

  @override
  Iterable<V> get annotations => _inner.annotations as Iterable<V>;

  @override
  void add(AnnotationEntry<V> entry) => _inner.add(entry);
}


// ---------------------------------------------------------------------------
// $RelaxedCalendarDelegate
// ---------------------------------------------------------------------------

/// Auto-generated GEN-079 relaxer wrapper for CalendarDelegate<V>.
class $RelaxedCalendarDelegate<V extends DateTime> implements CalendarDelegate<V> {
  final CalendarDelegate _inner;

  $RelaxedCalendarDelegate(this._inner);

  @override
  dynamic noSuchMethod(Invocation invocation) =>
    super.noSuchMethod(invocation);

  @override
  V now() => _inner.now() as V;

  @override
  V dateOnly(V date) => _inner.dateOnly(date) as V;

  @override
  DateTimeRange<V> datesOnly(DateTimeRange<V> range) => _inner.datesOnly(range) as DateTimeRange<V>;

  @override
  bool isSameDay(V? dateA, V? dateB) => _inner.isSameDay(dateA, dateB);

  @override
  bool isSameMonth(V? dateA, V? dateB) => _inner.isSameMonth(dateA, dateB);

  @override
  int monthDelta(V startDate, V endDate) => _inner.monthDelta(startDate, endDate);

  @override
  V addMonthsToMonthDate(V monthDate, int monthsToAdd) => _inner.addMonthsToMonthDate(monthDate, monthsToAdd) as V;

  @override
  V addDaysToDate(V date, int days) => _inner.addDaysToDate(date, days) as V;

  @override
  V getMonth(int year, int month) => _inner.getMonth(year, month) as V;

  @override
  V getDay(int year, int month, int day) => _inner.getDay(year, month, day) as V;

  @override
  String formatMonthYear(V date, MaterialLocalizations localizations) => _inner.formatMonthYear(date, localizations);

  @override
  String formatMediumDate(V date, MaterialLocalizations localizations) => _inner.formatMediumDate(date, localizations);

  @override
  String formatShortMonthDay(V date, MaterialLocalizations localizations) => _inner.formatShortMonthDay(date, localizations);

  @override
  String formatShortDate(V date, MaterialLocalizations localizations) => _inner.formatShortDate(date, localizations);

  @override
  String formatFullDate(V date, MaterialLocalizations localizations) => _inner.formatFullDate(date, localizations);

  @override
  String formatCompactDate(V date, MaterialLocalizations localizations) => _inner.formatCompactDate(date, localizations);

  @override
  V? parseCompactDate(String? inputString, MaterialLocalizations localizations) => _inner.parseCompactDate(inputString, localizations) as V?;

}


// ---------------------------------------------------------------------------
// $RelaxedCustomClipper
// ---------------------------------------------------------------------------

/// Auto-generated GEN-079 relaxer wrapper for CustomClipper<V>.
class $RelaxedCustomClipper<V> implements CustomClipper<V> {
  final CustomClipper _inner;

  $RelaxedCustomClipper(this._inner);

  @override
  dynamic noSuchMethod(Invocation invocation) =>
    super.noSuchMethod(invocation);

  @override
  V getClip(Size size) => _inner.getClip(size) as V;

  @override
  bool shouldReclip(CustomClipper<V> oldClipper) => _inner.shouldReclip(oldClipper);

}


// ---------------------------------------------------------------------------
// $RelaxedDateTimeRange
// ---------------------------------------------------------------------------

/// Auto-generated GEN-079 relaxer wrapper for DateTimeRange<V>.
class $RelaxedDateTimeRange<V extends DateTime> extends DateTimeRange<V> {
  final DateTimeRange _inner;

  $RelaxedDateTimeRange(this._inner) : super(start: _inner.start as V, end: _inner.end as V);

  @override
  V get start => _inner.start as V;

  @override
  V get end => _inner.end as V;
}


// ---------------------------------------------------------------------------
// $RelaxedDisposableBuildContext
// ---------------------------------------------------------------------------

/// Auto-generated GEN-079 relaxer wrapper for DisposableBuildContext<V>.
class $RelaxedDisposableBuildContext<V extends State<StatefulWidget>> implements DisposableBuildContext<V> {
  final DisposableBuildContext _inner;

  $RelaxedDisposableBuildContext(this._inner);

  @override
  dynamic noSuchMethod(Invocation invocation) =>
    super.noSuchMethod(invocation);

}


// ---------------------------------------------------------------------------
// $RelaxedDragBoundaryDelegate
// ---------------------------------------------------------------------------

/// Auto-generated GEN-079 relaxer wrapper for DragBoundaryDelegate<V>.
class $RelaxedDragBoundaryDelegate<V> implements DragBoundaryDelegate<V> {
  final DragBoundaryDelegate _inner;

  $RelaxedDragBoundaryDelegate(this._inner);

  @override
  dynamic noSuchMethod(Invocation invocation) =>
    super.noSuchMethod(invocation);

  @override
  bool isWithinBoundary(V draggedObject) => _inner.isWithinBoundary(draggedObject);

  @override
  V nearestPositionWithinBoundary(V draggedObject) => _inner.nearestPositionWithinBoundary(draggedObject) as V;

}


// ---------------------------------------------------------------------------
// $RelaxedDragTargetDetails
// ---------------------------------------------------------------------------

/// Auto-generated GEN-079 relaxer wrapper for DragTargetDetails<V>.
class $RelaxedDragTargetDetails<V> extends DragTargetDetails<V> {
  final DragTargetDetails _inner;

  $RelaxedDragTargetDetails(this._inner) : super(data: _inner.data as V, offset: _inner.offset);

  @override
  V get data => _inner.data as V;
}


// ---------------------------------------------------------------------------
// $RelaxedDraggable
// ---------------------------------------------------------------------------

/// Auto-generated GEN-079 relaxer wrapper for Draggable<V>.
class $RelaxedDraggable<V extends Object> extends Draggable<V> {
  final Draggable _inner;

  $RelaxedDraggable(this._inner) : super(child: _inner.child, feedback: _inner.feedback);

  @override
  V? get data => _inner.data as V?;

  @override
  State<Draggable<V>> createState() => _inner.createState() as State<Draggable<V>>;
}


// ---------------------------------------------------------------------------
// $RelaxedFactory
// ---------------------------------------------------------------------------

/// Auto-generated GEN-079 relaxer wrapper for Factory<V>.
class $RelaxedFactory<V> extends Factory<V> {
  final Factory _inner;

  $RelaxedFactory(this._inner) : super(_inner.constructor as V Function());

  @override
  ValueGetter<V> get constructor => _inner.constructor as ValueGetter<V>;
}


// ---------------------------------------------------------------------------
// $RelaxedGestureRecognizerFactory
// ---------------------------------------------------------------------------

/// Auto-generated GEN-079 relaxer wrapper for GestureRecognizerFactory<V>.
class $RelaxedGestureRecognizerFactory<V extends GestureRecognizer> implements GestureRecognizerFactory<V> {
  final GestureRecognizerFactory _inner;

  $RelaxedGestureRecognizerFactory(this._inner);

  @override
  dynamic noSuchMethod(Invocation invocation) =>
    super.noSuchMethod(invocation);

  @override
  V constructor() => _inner.constructor() as V;

  @override
  void initializer(V instance) => _inner.initializer(instance);

}


// ---------------------------------------------------------------------------
// $RelaxedGlobalKey
// ---------------------------------------------------------------------------

/// Auto-generated GEN-079 relaxer wrapper for GlobalKey<V>.
class $RelaxedGlobalKey<V extends State<StatefulWidget>> implements GlobalKey<V> {
  final GlobalKey _inner;

  $RelaxedGlobalKey(this._inner);

  @override
  dynamic noSuchMethod(Invocation invocation) =>
    super.noSuchMethod(invocation);

  @override
  V? get currentState => _inner.currentState as V?;

}


// ---------------------------------------------------------------------------
// $RelaxedHitTestEntry
// ---------------------------------------------------------------------------

/// Auto-generated GEN-079 relaxer wrapper for HitTestEntry<V>.
class $RelaxedHitTestEntry<V extends HitTestTarget> extends HitTestEntry<V> {
  final HitTestEntry _inner;

  $RelaxedHitTestEntry(this._inner) : super(_inner.target as V) {
  }

  @override
  V get target => _inner.target as V;
}


// ---------------------------------------------------------------------------
// $RelaxedImageProvider
// ---------------------------------------------------------------------------

/// Auto-generated GEN-079 relaxer wrapper for ImageProvider<V>.
class $RelaxedImageProvider<V extends Object> implements ImageProvider<V> {
  final ImageProvider _inner;

  $RelaxedImageProvider(this._inner);

  @override
  dynamic noSuchMethod(Invocation invocation) =>
    super.noSuchMethod(invocation);

  @override
  void resolveStreamForKey(ImageConfiguration configuration, ImageStream stream, V key, ImageErrorListener handleError) => _inner.resolveStreamForKey(configuration, stream, key, handleError);

  @override
  Future<V> obtainKey(ImageConfiguration configuration) => _inner.obtainKey(configuration) as Future<V>;

  @override
  ImageStreamCompleter loadBuffer(V key, DecoderBufferCallback decode) => _inner.loadBuffer(key, decode);

  @override
  ImageStreamCompleter loadImage(V key, ImageDecoderCallback decode) => _inner.loadImage(key, decode);

}


// ---------------------------------------------------------------------------
// $RelaxedIndexedSlot
// ---------------------------------------------------------------------------

/// Auto-generated GEN-079 relaxer wrapper for IndexedSlot<V>.
class $RelaxedIndexedSlot<V extends Element?> implements IndexedSlot<V> {
  final IndexedSlot _inner;

  $RelaxedIndexedSlot(this._inner);

  @override
  dynamic noSuchMethod(Invocation invocation) =>
    super.noSuchMethod(invocation);

  @override
  V get value => _inner.value as V;

}


// ---------------------------------------------------------------------------
// $RelaxedInheritedNotifier
// ---------------------------------------------------------------------------

/// Auto-generated GEN-079 relaxer wrapper for InheritedNotifier<V>.
class $RelaxedInheritedNotifier<V extends Listenable> implements InheritedNotifier<V> {
  final InheritedNotifier _inner;

  $RelaxedInheritedNotifier(this._inner);

  @override
  dynamic noSuchMethod(Invocation invocation) =>
    super.noSuchMethod(invocation);

  @override
  String toString({dynamic minLevel}) =>
    _inner.toString();

  @override
  V? get notifier => _inner.notifier as V?;

  @override
  bool updateShouldNotify(InheritedNotifier<V> oldWidget) => _inner.updateShouldNotify(oldWidget);

}


// ---------------------------------------------------------------------------
// $RelaxedLocalizationsDelegate
// ---------------------------------------------------------------------------

/// Auto-generated GEN-079 relaxer wrapper for LocalizationsDelegate<V>.
class $RelaxedLocalizationsDelegate<V> implements LocalizationsDelegate<V> {
  final LocalizationsDelegate _inner;

  $RelaxedLocalizationsDelegate(this._inner);

  @override
  dynamic noSuchMethod(Invocation invocation) =>
    super.noSuchMethod(invocation);

  @override
  Future<V> load(Locale locale) => _inner.load(locale) as Future<V>;

  @override
  bool shouldReload(LocalizationsDelegate<V> old) => _inner.shouldReload(old);

}


// ---------------------------------------------------------------------------
// $RelaxedPage
// ---------------------------------------------------------------------------

/// Auto-generated GEN-079 relaxer wrapper for Page<V>.
class $RelaxedPage<V> implements Page<V> {
  final Page _inner;

  $RelaxedPage(this._inner);

  @override
  dynamic noSuchMethod(Invocation invocation) =>
    super.noSuchMethod(invocation);

  @override
  PopInvokedWithResultCallback<V> get onPopInvoked => _inner.onPopInvoked as PopInvokedWithResultCallback<V>;

  @override
  Route<V> createRoute(BuildContext context) => _inner.createRoute(context) as Route<V>;

}


// ---------------------------------------------------------------------------
// $RelaxedParentDataWidget
// ---------------------------------------------------------------------------

/// Auto-generated GEN-079 relaxer wrapper for ParentDataWidget<V>.
class $RelaxedParentDataWidget<V extends ParentData> implements ParentDataWidget<V> {
  final ParentDataWidget _inner;

  $RelaxedParentDataWidget(this._inner);

  @override
  dynamic noSuchMethod(Invocation invocation) =>
    super.noSuchMethod(invocation);

  @override
  String toString({dynamic minLevel}) =>
    _inner.toString();

  @override
  ParentDataElement<V> createElement() => _inner.createElement() as ParentDataElement<V>;

}


// ---------------------------------------------------------------------------
// $RelaxedPopEntry
// ---------------------------------------------------------------------------

/// Auto-generated GEN-079 relaxer wrapper for PopEntry<V>.
class $RelaxedPopEntry<V> implements PopEntry<V> {
  final PopEntry _inner;

  $RelaxedPopEntry(this._inner);

  @override
  dynamic noSuchMethod(Invocation invocation) =>
    super.noSuchMethod(invocation);

  @override
  void onPopInvokedWithResult(bool didPop, V? result) => _inner.onPopInvokedWithResult(didPop, result);

}


// ---------------------------------------------------------------------------
// $RelaxedRenderAnnotatedRegion
// ---------------------------------------------------------------------------

/// Auto-generated GEN-079 relaxer wrapper for RenderAnnotatedRegion<V>.
class $RelaxedRenderAnnotatedRegion<V extends Object> extends RenderAnnotatedRegion<V> {
  final RenderAnnotatedRegion _inner;

  $RelaxedRenderAnnotatedRegion(this._inner) : super(value: _inner.value as V, sized: _inner.sized);

  @override
  V get value => _inner.value as V;

  @override
  set value(V newValue) { _inner.value = newValue; }
}


// ---------------------------------------------------------------------------
// $RelaxedRenderObjectToWidgetAdapter
// ---------------------------------------------------------------------------

/// Auto-generated GEN-079 relaxer wrapper for RenderObjectToWidgetAdapter<V>.
class $RelaxedRenderObjectToWidgetAdapter<V extends RenderObject> extends RenderObjectToWidgetAdapter<V> {
  final RenderObjectToWidgetAdapter _inner;

  $RelaxedRenderObjectToWidgetAdapter(this._inner) : super(container: _inner.container as RenderObjectWithChildMixin<V>);

  @override
  RenderObjectWithChildMixin<V> get container => _inner.container as RenderObjectWithChildMixin<V>;

  @override
  RenderObjectToWidgetElement<V> createElement() => _inner.createElement() as RenderObjectToWidgetElement<V>;

  @override
  RenderObjectWithChildMixin<V> createRenderObject(BuildContext context) => _inner.createRenderObject(context) as RenderObjectWithChildMixin<V>;

  @override
  RenderObjectToWidgetElement<V> attachToRenderTree(BuildOwner owner, [RenderObjectToWidgetElement<V>? element]) => _inner.attachToRenderTree(owner, element) as RenderObjectToWidgetElement<V>;
}


// ---------------------------------------------------------------------------
// $RelaxedRenderObjectToWidgetElement
// ---------------------------------------------------------------------------

/// Auto-generated GEN-079 relaxer wrapper for RenderObjectToWidgetElement<V>.
class $RelaxedRenderObjectToWidgetElement<V extends RenderObject> extends RenderObjectToWidgetElement<V> {
  final RenderObjectToWidgetElement _inner;

  $RelaxedRenderObjectToWidgetElement(this._inner) : super(_inner.widget as RenderObjectToWidgetAdapter<V>);

  @override
  RenderObjectWithChildMixin<V> get renderObject => _inner.renderObject as RenderObjectWithChildMixin<V>;

  @override
  void update(RenderObjectToWidgetAdapter<V> newWidget) => _inner.update(newWidget);
}


// ---------------------------------------------------------------------------
// $RelaxedRenderObjectWithChildMixin
// ---------------------------------------------------------------------------

/// Auto-generated GEN-079 relaxer wrapper for RenderObjectWithChildMixin<V>.
class $RelaxedRenderObjectWithChildMixin<V extends RenderObject> implements RenderObjectWithChildMixin<V> {
  final RenderObjectWithChildMixin _inner;

  $RelaxedRenderObjectWithChildMixin(this._inner);

  @override
  dynamic noSuchMethod(Invocation invocation) =>
    super.noSuchMethod(invocation);

  @override
  String toString({dynamic minLevel}) =>
    _inner.toString();

  @override
  V? get child => _inner.child as V?;

  @override
  set child(V? value) { _inner.child = value; }

}


// ---------------------------------------------------------------------------
// $RelaxedRestorableProperty
// ---------------------------------------------------------------------------

/// Auto-generated GEN-079 relaxer wrapper for RestorableProperty<V>.
class $RelaxedRestorableProperty<V> implements RestorableProperty<V> {
  final RestorableProperty _inner;
  bool _syncing = false;

  $RelaxedRestorableProperty(this._inner);

  @override
  dynamic noSuchMethod(Invocation invocation) =>
    super.noSuchMethod(invocation);

  @override
  V createDefaultValue() => _inner.createDefaultValue() as V;

  @override
  V fromPrimitives(Object? data) => _inner.fromPrimitives(data) as V;

  @override
  void initWithValue(V value) => _inner.initWithValue(value);

}


// ---------------------------------------------------------------------------
// $RelaxedRoute
// ---------------------------------------------------------------------------

/// Auto-generated GEN-079 relaxer wrapper for Route<V>.
class $RelaxedRoute<V> implements Route<V> {
  final Route _inner;

  $RelaxedRoute(this._inner);

  @override
  dynamic noSuchMethod(Invocation invocation) =>
    super.noSuchMethod(invocation);

  @override
  V? get currentResult => _inner.currentResult as V?;

  @override
  Future<V?> get popped => _inner.popped as Future<V?>;

  @override
  void onPopInvokedWithResult(bool didPop, V? result) => _inner.onPopInvokedWithResult(didPop, result);

  @override
  bool didPop(V? result) => _inner.didPop(result);

  @override
  void didComplete(V? result) => _inner.didComplete(result);

}


// ---------------------------------------------------------------------------
// $RelaxedRouteInformationParser
// ---------------------------------------------------------------------------

/// Auto-generated GEN-079 relaxer wrapper for RouteInformationParser<V>.
class $RelaxedRouteInformationParser<V> implements RouteInformationParser<V> {
  final RouteInformationParser _inner;

  $RelaxedRouteInformationParser(this._inner);

  @override
  dynamic noSuchMethod(Invocation invocation) =>
    super.noSuchMethod(invocation);

  @override
  Future<V> parseRouteInformation(RouteInformation routeInformation) => _inner.parseRouteInformation(routeInformation) as Future<V>;

  @override
  Future<V> parseRouteInformationWithDependencies(RouteInformation routeInformation, BuildContext context) => _inner.parseRouteInformationWithDependencies(routeInformation, context) as Future<V>;

  @override
  RouteInformation? restoreRouteInformation(V configuration) => _inner.restoreRouteInformation(configuration);

}


// ---------------------------------------------------------------------------
// $RelaxedRouterConfig
// ---------------------------------------------------------------------------

/// Auto-generated GEN-079 relaxer wrapper for RouterConfig<V>.
class $RelaxedRouterConfig<V> extends RouterConfig<V> {
  final RouterConfig _inner;

  $RelaxedRouterConfig(this._inner) : super(routerDelegate: _inner.routerDelegate as RouterDelegate<V>);

  @override
  RouteInformationParser<V>? get routeInformationParser => _inner.routeInformationParser as RouteInformationParser<V>?;

  @override
  RouterDelegate<V> get routerDelegate => _inner.routerDelegate as RouterDelegate<V>;
}


// ---------------------------------------------------------------------------
// $RelaxedRouterDelegate
// ---------------------------------------------------------------------------

/// Auto-generated GEN-079 relaxer wrapper for RouterDelegate<V>.
class $RelaxedRouterDelegate<V> implements RouterDelegate<V> {
  final RouterDelegate _inner;

  $RelaxedRouterDelegate(this._inner);

  @override
  dynamic noSuchMethod(Invocation invocation) =>
    super.noSuchMethod(invocation);

  @override
  V? get currentConfiguration => _inner.currentConfiguration as V?;

  @override
  Future<void> setInitialRoutePath(V configuration) => _inner.setInitialRoutePath(configuration);

  @override
  Future<void> setRestoredRoutePath(V configuration) => _inner.setRestoredRoutePath(configuration);

  @override
  Future<void> setNewRoutePath(V configuration) => _inner.setNewRoutePath(configuration);

}


// ---------------------------------------------------------------------------
// $RelaxedState
// ---------------------------------------------------------------------------

/// Auto-generated GEN-079 relaxer wrapper for State<V>.
class $RelaxedState<V extends StatefulWidget> implements State<V> {
  final State _inner;

  $RelaxedState(this._inner);

  @override
  dynamic noSuchMethod(Invocation invocation) =>
    super.noSuchMethod(invocation);

  @override
  String toString({dynamic minLevel}) =>
    _inner.toString();

  @override
  V get widget => _inner.widget as V;

  @override
  void didUpdateWidget(V oldWidget) => _inner.didUpdateWidget(oldWidget);

}


// ---------------------------------------------------------------------------
// $RelaxedThemeExtension
// ---------------------------------------------------------------------------

/// Auto-generated GEN-079 relaxer wrapper for ThemeExtension<V>.
class $RelaxedThemeExtension<V extends ThemeExtension<V>> implements ThemeExtension<V> {
  final ThemeExtension _inner;

  $RelaxedThemeExtension(this._inner);

  @override
  dynamic noSuchMethod(Invocation invocation) =>
    super.noSuchMethod(invocation);

  @override
  ThemeExtension<V> copyWith() => _inner.copyWith() as ThemeExtension<V>;

  @override
  ThemeExtension<V> lerp(ThemeExtension<V>? other, double t) => _inner.lerp(other, t) as ThemeExtension<V>;

}


// ---------------------------------------------------------------------------
// $RelaxedToggleableStateMixin
// ---------------------------------------------------------------------------

/// Auto-generated GEN-079 relaxer wrapper for ToggleableStateMixin<V>.
class $RelaxedToggleableStateMixin<V extends StatefulWidget> implements ToggleableStateMixin<V> {
  final ToggleableStateMixin _inner;

  $RelaxedToggleableStateMixin(this._inner);

  @override
  dynamic noSuchMethod(Invocation invocation) =>
    super.noSuchMethod(invocation);

  @override
  String toString({dynamic minLevel}) =>
    _inner.toString();

  @override
  V get widget => _inner.widget as V;

  @override
  void didUpdateWidget(V oldWidget) => _inner.didUpdateWidget(oldWidget);

}


// ---------------------------------------------------------------------------
// $RelaxedTreeSliverNode
// ---------------------------------------------------------------------------

/// Auto-generated GEN-079 relaxer wrapper for TreeSliverNode<V>.
class $RelaxedTreeSliverNode<V> extends TreeSliverNode<V> {
  final TreeSliverNode _inner;

  $RelaxedTreeSliverNode(this._inner) : super(_inner.content as V) {
  }

  @override
  V get content => _inner.content as V;

  @override
  List<TreeSliverNode<V>> get children => _inner.children as List<TreeSliverNode<V>>;

  @override
  TreeSliverNode<V>? get parent => _inner.parent as TreeSliverNode<V>?;
}


// ---------------------------------------------------------------------------
// $RelaxedTween
// ---------------------------------------------------------------------------

/// Auto-generated GEN-079 relaxer wrapper for Tween<V>.
class $RelaxedTween<V extends Object?> extends Tween<V> {
  final Tween _inner;

  $RelaxedTween(this._inner) : super();

  @override
  V? get begin => _inner.begin as V?;

  @override
  V? get end => _inner.end as V?;

  @override
  V transform(double t) => _inner.transform(t) as V;

  @override
  V evaluate(Animation<double> animation) => _inner.evaluate(animation) as V;

  @override
  Animation<V> animate(Animation<double> parent) => _inner.animate(parent) as Animation<V>;

  @override
  Animatable<V> chain(Animatable<double> parent) => _inner.chain(parent) as Animatable<V>;

  @override
  V lerp(double t) => _inner.lerp(t) as V;
}


// ---------------------------------------------------------------------------
// $RelaxedTweenSequenceItem
// ---------------------------------------------------------------------------

/// Auto-generated GEN-079 relaxer wrapper for TweenSequenceItem<V>.
class $RelaxedTweenSequenceItem<V> extends TweenSequenceItem<V> {
  final TweenSequenceItem _inner;

  $RelaxedTweenSequenceItem(this._inner) : super(tween: _inner.tween as Animatable<V>, weight: _inner.weight);

  @override
  Animatable<V> get tween => _inner.tween as Animatable<V>;
}


// ---------------------------------------------------------------------------
// $RelaxedValueListenable
// ---------------------------------------------------------------------------

/// Auto-generated GEN-079 relaxer wrapper for ValueListenable<V>.
class $RelaxedValueListenable<V> implements ValueListenable<V> {
  final ValueListenable _inner;

  $RelaxedValueListenable(this._inner);

  @override
  dynamic noSuchMethod(Invocation invocation) =>
    super.noSuchMethod(invocation);

  @override
  V get value => _inner.value as V;

}


// ---------------------------------------------------------------------------
// $RelaxedValueNotifier
// ---------------------------------------------------------------------------

/// Auto-generated GEN-079 relaxer wrapper for ValueNotifier<V>.
class $RelaxedValueNotifier<V> extends ValueNotifier<V> {
  final ValueNotifier _inner;
  bool _syncing = false;

  $RelaxedValueNotifier(this._inner) : super(_inner.value as V) {
    _inner.addListener(_forwardNotify);
  }

  /// Forward notifications from _inner → wrapper.
  void _forwardNotify() {
    if (!_syncing) {
      _syncing = true;
      super.value = _inner.value as V;
      _syncing = false;
    }
  }

  @override
  V get value => _inner.value as V;

  @override
  set value(V newValue) {
    if (!_syncing) {
      _syncing = true;
      _inner.value = newValue;
      super.value = newValue;
      _syncing = false;
    }
  }

  @override
  void dispose() {
    _inner.removeListener(_forwardNotify);
    super.dispose();
  }
}


// ---------------------------------------------------------------------------
// $RelaxedWidgetStateProperty
// ---------------------------------------------------------------------------

/// Auto-generated GEN-079 relaxer wrapper for WidgetStateProperty<V>.
class $RelaxedWidgetStateProperty<V> implements WidgetStateProperty<V> {
  final WidgetStateProperty _inner;

  $RelaxedWidgetStateProperty(this._inner);

  @override
  dynamic noSuchMethod(Invocation invocation) =>
    super.noSuchMethod(invocation);

  @override
  V resolve(Set<WidgetState> states) => _inner.resolve(states) as V;

}


/// Auto-generated relaxer factory for AbstractLayoutBuilder — flutter_widgets layer types.
Object? _relaxAbstractLayoutBuilder$widgets(Object value, String innerTypeArg) {
  if (value is! AbstractLayoutBuilder) return null;
  return switch (innerTypeArg) {
    'BoxConstraints' => $RelaxedAbstractLayoutBuilder<BoxConstraints>(value),
    'Constraints' => $RelaxedAbstractLayoutBuilder<Constraints>(value),
    'SliverConstraints' => $RelaxedAbstractLayoutBuilder<SliverConstraints>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for Action — flutter_widgets layer types.
Object? _relaxAction$widgets(Object value, String innerTypeArg) {
  if (value is! Action) return null;
  return switch (innerTypeArg) {
    'Intent' => $RelaxedAction<Intent>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for Action — flutter_material layer types.
Object? _relaxAction$material(Object value, String innerTypeArg) {
  if (value is! Action) return null;
  return switch (innerTypeArg) {
    'Intent' => $RelaxedAction<Intent>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for Action — flutter_cupertino layer types.
Object? _relaxAction$cupertino(Object value, String innerTypeArg) {
  if (value is! Action) return null;
  return switch (innerTypeArg) {
    'Intent' => $RelaxedAction<Intent>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for Adaptation — flutter_material layer types.
Object? _relaxAdaptation$material(Object value, String innerTypeArg) {
  if (value is! Adaptation) return null;
  return switch (innerTypeArg) {
    'Object' => $RelaxedAdaptation<Object>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for Animatable — flutter_animation layer types.
Object? _relaxAnimatable$animation(Object value, String innerTypeArg) {
  if (value is! Animatable) return null;
  return switch (innerTypeArg) {
    'double' => $RelaxedAnimatable<double>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for Animatable — flutter_rendering layer types.
Object? _relaxAnimatable$rendering(Object value, String innerTypeArg) {
  if (value is! Animatable) return null;
  return switch (innerTypeArg) {
    'double' => $RelaxedAnimatable<double>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for Animatable — flutter_widgets layer types.
Object? _relaxAnimatable$widgets(Object value, String innerTypeArg) {
  if (value is! Animatable) return null;
  return switch (innerTypeArg) {
    'Object' => $RelaxedAnimatable<Object>(value),
    'double' => $RelaxedAnimatable<double>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for Animatable — flutter_material layer types.
Object? _relaxAnimatable$material(Object value, String innerTypeArg) {
  if (value is! Animatable) return null;
  return switch (innerTypeArg) {
    'double' => $RelaxedAnimatable<double>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for Animation — flutter_animation layer types.
Object? _relaxAnimation$animation(Object value, String innerTypeArg) {
  if (value is! Animation) return null;
  return switch (innerTypeArg) {
    'double' => $RelaxedAnimation<double>(value),
    'num' => $RelaxedAnimation<num>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for Animation — flutter_rendering layer types.
Object? _relaxAnimation$rendering(Object value, String innerTypeArg) {
  if (value is! Animation) return null;
  return switch (innerTypeArg) {
    'double' => $RelaxedAnimation<double>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for Animation — flutter_widgets layer types.
Object? _relaxAnimation$widgets(Object value, String innerTypeArg) {
  if (value is! Animation) return null;
  return switch (innerTypeArg) {
    'AlignmentGeometry' => $RelaxedAnimation<AlignmentGeometry>(value),
    'Color' => $RelaxedAnimation<Color>(value),
    'Decoration' => $RelaxedAnimation<Decoration>(value),
    'Offset' => $RelaxedAnimation<Offset>(value),
    'Rect' => $RelaxedAnimation<Rect>(value),
    'RelativeRect' => $RelaxedAnimation<RelativeRect>(value),
    'TextStyle' => $RelaxedAnimation<TextStyle>(value),
    'double' => $RelaxedAnimation<double>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for Animation — flutter_material layer types.
Object? _relaxAnimation$material(Object value, String innerTypeArg) {
  if (value is! Animation) return null;
  return switch (innerTypeArg) {
    'Color' => $RelaxedAnimation<Color>(value),
    'double' => $RelaxedAnimation<double>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for Animation — flutter_cupertino layer types.
Object? _relaxAnimation$cupertino(Object value, String innerTypeArg) {
  if (value is! Animation) return null;
  return switch (innerTypeArg) {
    'double' => $RelaxedAnimation<double>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for AnnotationResult — flutter_rendering layer types.
Object? _relaxAnnotationResult$rendering(Object value, String innerTypeArg) {
  if (value is! AnnotationResult) return null;
  return switch (innerTypeArg) {
    'Object' => $RelaxedAnnotationResult<Object>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for CalendarDelegate — flutter_material layer types.
Object? _relaxCalendarDelegate$material(Object value, String innerTypeArg) {
  if (value is! CalendarDelegate) return null;
  return switch (innerTypeArg) {
    'DateTime' => $RelaxedCalendarDelegate<DateTime>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for CustomClipper — flutter_rendering layer types.
Object? _relaxCustomClipper$rendering(Object value, String innerTypeArg) {
  if (value is! CustomClipper) return null;
  return switch (innerTypeArg) {
    'Path' => $RelaxedCustomClipper<Path>(value),
    'RRect' => $RelaxedCustomClipper<RRect>(value),
    'RSuperellipse' => $RelaxedCustomClipper<RSuperellipse>(value),
    'Rect' => $RelaxedCustomClipper<Rect>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for CustomClipper — flutter_widgets layer types.
Object? _relaxCustomClipper$widgets(Object value, String innerTypeArg) {
  if (value is! CustomClipper) return null;
  return switch (innerTypeArg) {
    'Path' => $RelaxedCustomClipper<Path>(value),
    'RRect' => $RelaxedCustomClipper<RRect>(value),
    'RSuperellipse' => $RelaxedCustomClipper<RSuperellipse>(value),
    'Rect' => $RelaxedCustomClipper<Rect>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for DateTimeRange — flutter_material layer types.
Object? _relaxDateTimeRange$material(Object value, String innerTypeArg) {
  if (value is! DateTimeRange) return null;
  return switch (innerTypeArg) {
    'DateTime' => $RelaxedDateTimeRange<DateTime>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for DisposableBuildContext — flutter_widgets layer types.
Object? _relaxDisposableBuildContext$widgets(Object value, String innerTypeArg) {
  if (value is! DisposableBuildContext) return null;
  return switch (innerTypeArg) {
    'State<StatefulWidget>' => $RelaxedDisposableBuildContext<State<StatefulWidget>>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for DragBoundaryDelegate — flutter_widgets layer types.
Object? _relaxDragBoundaryDelegate$widgets(Object value, String innerTypeArg) {
  if (value is! DragBoundaryDelegate) return null;
  return switch (innerTypeArg) {
    'Rect' => $RelaxedDragBoundaryDelegate<Rect>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for DragBoundaryDelegate — flutter_material layer types.
Object? _relaxDragBoundaryDelegate$material(Object value, String innerTypeArg) {
  if (value is! DragBoundaryDelegate) return null;
  return switch (innerTypeArg) {
    'Rect' => $RelaxedDragBoundaryDelegate<Rect>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for DragTargetDetails — flutter_widgets layer types.
Object? _relaxDragTargetDetails$widgets(Object value, String innerTypeArg) {
  if (value is! DragTargetDetails) return null;
  return switch (innerTypeArg) {
    'Object' => $RelaxedDragTargetDetails<Object>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for Draggable — flutter_widgets layer types.
Object? _relaxDraggable$widgets(Object value, String innerTypeArg) {
  if (value is! Draggable) return null;
  return switch (innerTypeArg) {
    'Object' => $RelaxedDraggable<Object>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for Draggable — flutter_material layer types.
Object? _relaxDraggable$material(Object value, String innerTypeArg) {
  if (value is! Draggable) return null;
  return switch (innerTypeArg) {
    'Object' => $RelaxedDraggable<Object>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for Draggable — flutter_cupertino layer types.
Object? _relaxDraggable$cupertino(Object value, String innerTypeArg) {
  if (value is! Draggable) return null;
  return switch (innerTypeArg) {
    'Object' => $RelaxedDraggable<Object>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for Factory — flutter_rendering layer types.
Object? _relaxFactory$rendering(Object value, String innerTypeArg) {
  if (value is! Factory) return null;
  return switch (innerTypeArg) {
    'OneSequenceGestureRecognizer' => $RelaxedFactory<OneSequenceGestureRecognizer>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for Factory — flutter_widgets layer types.
Object? _relaxFactory$widgets(Object value, String innerTypeArg) {
  if (value is! Factory) return null;
  return switch (innerTypeArg) {
    'OneSequenceGestureRecognizer' => $RelaxedFactory<OneSequenceGestureRecognizer>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for GestureRecognizerFactory — flutter_widgets layer types.
Object? _relaxGestureRecognizerFactory$widgets(Object value, String innerTypeArg) {
  if (value is! GestureRecognizerFactory) return null;
  return switch (innerTypeArg) {
    'GestureRecognizer' => $RelaxedGestureRecognizerFactory<GestureRecognizer>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for GlobalKey — flutter_widgets layer types.
Object? _relaxGlobalKey$widgets(Object value, String innerTypeArg) {
  if (value is! GlobalKey) return null;
  return switch (innerTypeArg) {
    'NavigatorState' => $RelaxedGlobalKey<NavigatorState>(value),
    'State<StatefulWidget>' => $RelaxedGlobalKey<State<StatefulWidget>>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for GlobalKey — flutter_material layer types.
Object? _relaxGlobalKey$material(Object value, String innerTypeArg) {
  if (value is! GlobalKey) return null;
  return switch (innerTypeArg) {
    'NavigatorState' => $RelaxedGlobalKey<NavigatorState>(value),
    'ScaffoldMessengerState' => $RelaxedGlobalKey<ScaffoldMessengerState>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for GlobalKey — flutter_cupertino layer types.
Object? _relaxGlobalKey$cupertino(Object value, String innerTypeArg) {
  if (value is! GlobalKey) return null;
  return switch (innerTypeArg) {
    'NavigatorState' => $RelaxedGlobalKey<NavigatorState>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for HitTestEntry — flutter_gestures layer types.
Object? _relaxHitTestEntry$gestures(Object value, String innerTypeArg) {
  if (value is! HitTestEntry) return null;
  return switch (innerTypeArg) {
    'HitTestTarget' => $RelaxedHitTestEntry<HitTestTarget>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for HitTestEntry — flutter_rendering layer types.
Object? _relaxHitTestEntry$rendering(Object value, String innerTypeArg) {
  if (value is! HitTestEntry) return null;
  return switch (innerTypeArg) {
    'HitTestTarget' => $RelaxedHitTestEntry<HitTestTarget>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for HitTestEntry — flutter_widgets layer types.
Object? _relaxHitTestEntry$widgets(Object value, String innerTypeArg) {
  if (value is! HitTestEntry) return null;
  return switch (innerTypeArg) {
    'HitTestTarget' => $RelaxedHitTestEntry<HitTestTarget>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for ImageProvider — flutter_painting layer types.
Object? _relaxImageProvider$painting(Object value, String innerTypeArg) {
  if (value is! ImageProvider) return null;
  return switch (innerTypeArg) {
    'Object' => $RelaxedImageProvider<Object>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for ImageProvider — flutter_widgets layer types.
Object? _relaxImageProvider$widgets(Object value, String innerTypeArg) {
  if (value is! ImageProvider) return null;
  return switch (innerTypeArg) {
    'Object' => $RelaxedImageProvider<Object>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for ImageProvider — flutter_material layer types.
Object? _relaxImageProvider$material(Object value, String innerTypeArg) {
  if (value is! ImageProvider) return null;
  return switch (innerTypeArg) {
    'Object' => $RelaxedImageProvider<Object>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for ImageProvider — flutter_cupertino layer types.
Object? _relaxImageProvider$cupertino(Object value, String innerTypeArg) {
  if (value is! ImageProvider) return null;
  return switch (innerTypeArg) {
    'Object' => $RelaxedImageProvider<Object>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for IndexedSlot — flutter_widgets layer types.
Object? _relaxIndexedSlot$widgets(Object value, String innerTypeArg) {
  if (value is! IndexedSlot) return null;
  return switch (innerTypeArg) {
    'Element' => $RelaxedIndexedSlot<Element>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for InheritedNotifier — flutter_widgets layer types.
Object? _relaxInheritedNotifier$widgets(Object value, String innerTypeArg) {
  if (value is! InheritedNotifier) return null;
  return switch (innerTypeArg) {
    'Listenable' => $RelaxedInheritedNotifier<Listenable>(value),
    'ValueNotifier<int>' => $RelaxedInheritedNotifier<ValueNotifier<int>>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for LocalizationsDelegate — flutter_widgets layer types.
Object? _relaxLocalizationsDelegate$widgets(Object value, String innerTypeArg) {
  if (value is! LocalizationsDelegate) return null;
  return switch (innerTypeArg) {
    'Object' => $RelaxedLocalizationsDelegate<Object>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for Page — flutter_widgets layer types.
Object? _relaxPage$widgets(Object value, String innerTypeArg) {
  if (value is! Page) return null;
  return switch (innerTypeArg) {
    'Object' => $RelaxedPage<Object>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for ParentDataWidget — flutter_widgets layer types.
Object? _relaxParentDataWidget$widgets(Object value, String innerTypeArg) {
  if (value is! ParentDataWidget) return null;
  return switch (innerTypeArg) {
    'ParentData' => $RelaxedParentDataWidget<ParentData>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for PopEntry — flutter_widgets layer types.
Object? _relaxPopEntry$widgets(Object value, String innerTypeArg) {
  if (value is! PopEntry) return null;
  return switch (innerTypeArg) {
    'Object' => $RelaxedPopEntry<Object>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for PopEntry — flutter_material layer types.
Object? _relaxPopEntry$material(Object value, String innerTypeArg) {
  if (value is! PopEntry) return null;
  return switch (innerTypeArg) {
    'Object' => $RelaxedPopEntry<Object>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for PopEntry — flutter_cupertino layer types.
Object? _relaxPopEntry$cupertino(Object value, String innerTypeArg) {
  if (value is! PopEntry) return null;
  return switch (innerTypeArg) {
    'Object' => $RelaxedPopEntry<Object>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for RenderAnnotatedRegion — flutter_widgets layer types.
Object? _relaxRenderAnnotatedRegion$widgets(Object value, String innerTypeArg) {
  if (value is! RenderAnnotatedRegion) return null;
  return switch (innerTypeArg) {
    'Object' => $RelaxedRenderAnnotatedRegion<Object>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for RenderObjectToWidgetAdapter — flutter_widgets layer types.
Object? _relaxRenderObjectToWidgetAdapter$widgets(Object value, String innerTypeArg) {
  if (value is! RenderObjectToWidgetAdapter) return null;
  return switch (innerTypeArg) {
    'RenderObject' => $RelaxedRenderObjectToWidgetAdapter<RenderObject>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for RenderObjectToWidgetElement — flutter_widgets layer types.
Object? _relaxRenderObjectToWidgetElement$widgets(Object value, String innerTypeArg) {
  if (value is! RenderObjectToWidgetElement) return null;
  return switch (innerTypeArg) {
    'RenderObject' => $RelaxedRenderObjectToWidgetElement<RenderObject>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for RenderObjectWithChildMixin — flutter_widgets layer types.
Object? _relaxRenderObjectWithChildMixin$widgets(Object value, String innerTypeArg) {
  if (value is! RenderObjectWithChildMixin) return null;
  return switch (innerTypeArg) {
    'RenderObject' => $RelaxedRenderObjectWithChildMixin<RenderObject>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for RestorableProperty — flutter_widgets layer types.
Object? _relaxRestorableProperty$widgets(Object value, String innerTypeArg) {
  if (value is! RestorableProperty) return null;
  return switch (innerTypeArg) {
    'Object' => $RelaxedRestorableProperty<Object>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for RestorableProperty — flutter_material layer types.
Object? _relaxRestorableProperty$material(Object value, String innerTypeArg) {
  if (value is! RestorableProperty) return null;
  return switch (innerTypeArg) {
    'Object' => $RelaxedRestorableProperty<Object>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for Route — flutter_widgets layer types.
Object? _relaxRoute$widgets(Object value, String innerTypeArg) {
  if (value is! Route) return null;
  return switch (innerTypeArg) {
    'Object' => $RelaxedRoute<Object>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for RouteInformationParser — flutter_widgets layer types.
Object? _relaxRouteInformationParser$widgets(Object value, String innerTypeArg) {
  if (value is! RouteInformationParser) return null;
  return switch (innerTypeArg) {
    'Object' => $RelaxedRouteInformationParser<Object>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for RouteInformationParser — flutter_material layer types.
Object? _relaxRouteInformationParser$material(Object value, String innerTypeArg) {
  if (value is! RouteInformationParser) return null;
  return switch (innerTypeArg) {
    'Object' => $RelaxedRouteInformationParser<Object>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for RouteInformationParser — flutter_cupertino layer types.
Object? _relaxRouteInformationParser$cupertino(Object value, String innerTypeArg) {
  if (value is! RouteInformationParser) return null;
  return switch (innerTypeArg) {
    'Object' => $RelaxedRouteInformationParser<Object>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for RouterConfig — flutter_widgets layer types.
Object? _relaxRouterConfig$widgets(Object value, String innerTypeArg) {
  if (value is! RouterConfig) return null;
  return switch (innerTypeArg) {
    'Object' => $RelaxedRouterConfig<Object>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for RouterConfig — flutter_material layer types.
Object? _relaxRouterConfig$material(Object value, String innerTypeArg) {
  if (value is! RouterConfig) return null;
  return switch (innerTypeArg) {
    'Object' => $RelaxedRouterConfig<Object>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for RouterConfig — flutter_cupertino layer types.
Object? _relaxRouterConfig$cupertino(Object value, String innerTypeArg) {
  if (value is! RouterConfig) return null;
  return switch (innerTypeArg) {
    'Object' => $RelaxedRouterConfig<Object>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for RouterDelegate — flutter_widgets layer types.
Object? _relaxRouterDelegate$widgets(Object value, String innerTypeArg) {
  if (value is! RouterDelegate) return null;
  return switch (innerTypeArg) {
    'Object' => $RelaxedRouterDelegate<Object>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for RouterDelegate — flutter_material layer types.
Object? _relaxRouterDelegate$material(Object value, String innerTypeArg) {
  if (value is! RouterDelegate) return null;
  return switch (innerTypeArg) {
    'Object' => $RelaxedRouterDelegate<Object>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for RouterDelegate — flutter_cupertino layer types.
Object? _relaxRouterDelegate$cupertino(Object value, String innerTypeArg) {
  if (value is! RouterDelegate) return null;
  return switch (innerTypeArg) {
    'Object' => $RelaxedRouterDelegate<Object>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for State — flutter_widgets layer types.
Object? _relaxState$widgets(Object value, String innerTypeArg) {
  if (value is! State) return null;
  return switch (innerTypeArg) {
    'StatefulWidget' => $RelaxedState<StatefulWidget>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for ToggleableStateMixin — flutter_widgets layer types.
Object? _relaxToggleableStateMixin$widgets(Object value, String innerTypeArg) {
  if (value is! ToggleableStateMixin) return null;
  return switch (innerTypeArg) {
    'StatefulWidget' => $RelaxedToggleableStateMixin<StatefulWidget>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for TreeSliverNode — flutter_widgets layer types.
Object? _relaxTreeSliverNode$widgets(Object value, String innerTypeArg) {
  if (value is! TreeSliverNode) return null;
  return switch (innerTypeArg) {
    'Object' => $RelaxedTreeSliverNode<Object>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for Tween — flutter_animation layer types.
Object? _relaxTween$animation(Object value, String innerTypeArg) {
  if (value is! Tween) return null;
  return switch (innerTypeArg) {
    'Object' => $RelaxedTween<Object>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for Tween — flutter_widgets layer types.
Object? _relaxTween$widgets(Object value, String innerTypeArg) {
  if (value is! Tween) return null;
  return switch (innerTypeArg) {
    'Object' => $RelaxedTween<Object>(value),
    'Rect' => $RelaxedTween<Rect>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for TweenSequenceItem — flutter_animation layer types.
Object? _relaxTweenSequenceItem$animation(Object value, String innerTypeArg) {
  if (value is! TweenSequenceItem) return null;
  return switch (innerTypeArg) {
    'double' => $RelaxedTweenSequenceItem<double>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for ValueListenable — flutter_widgets layer types.
Object? _relaxValueListenable$widgets(Object value, String innerTypeArg) {
  if (value is! ValueListenable) return null;
  return switch (innerTypeArg) {
    'ClipboardStatus' => $RelaxedValueListenable<ClipboardStatus>(value),
    'bool' => $RelaxedValueListenable<bool>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for ValueListenable — flutter_material layer types.
Object? _relaxValueListenable$material(Object value, String innerTypeArg) {
  if (value is! ValueListenable) return null;
  return switch (innerTypeArg) {
    'ClipboardStatus' => $RelaxedValueListenable<ClipboardStatus>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for ValueListenable — flutter_cupertino layer types.
Object? _relaxValueListenable$cupertino(Object value, String innerTypeArg) {
  if (value is! ValueListenable) return null;
  return switch (innerTypeArg) {
    'ClipboardStatus' => $RelaxedValueListenable<ClipboardStatus>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for ValueNotifier — flutter_rendering layer types.
Object? _relaxValueNotifier$rendering(Object value, String innerTypeArg) {
  if (value is! ValueNotifier) return null;
  return switch (innerTypeArg) {
    'bool' => $RelaxedValueNotifier<bool>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for ValueNotifier — flutter_widgets layer types.
Object? _relaxValueNotifier$widgets(Object value, String innerTypeArg) {
  if (value is! ValueNotifier) return null;
  return switch (innerTypeArg) {
    'EdgeInsets' => $RelaxedValueNotifier<EdgeInsets>(value),
    'MagnifierInfo' => $RelaxedValueNotifier<MagnifierInfo>(value),
    'int' => $RelaxedValueNotifier<int>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for ValueNotifier — flutter_material layer types.
Object? _relaxValueNotifier$material(Object value, String innerTypeArg) {
  if (value is! ValueNotifier) return null;
  return switch (innerTypeArg) {
    'MagnifierInfo' => $RelaxedValueNotifier<MagnifierInfo>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for ValueNotifier — flutter_cupertino layer types.
Object? _relaxValueNotifier$cupertino(Object value, String innerTypeArg) {
  if (value is! ValueNotifier) return null;
  return switch (innerTypeArg) {
    'MagnifierInfo' => $RelaxedValueNotifier<MagnifierInfo>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for WidgetStateProperty — flutter_widgets layer types.
Object? _relaxWidgetStateProperty$widgets(Object value, String innerTypeArg) {
  if (value is! WidgetStateProperty) return null;
  return switch (innerTypeArg) {
    'BorderSide' => $RelaxedWidgetStateProperty<BorderSide>(value),
    'MouseCursor' => $RelaxedWidgetStateProperty<MouseCursor>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for WidgetStateProperty — flutter_material layer types.
Object? _relaxWidgetStateProperty$material(Object value, String innerTypeArg) {
  if (value is! WidgetStateProperty) return null;
  return switch (innerTypeArg) {
    'BorderSide' => $RelaxedWidgetStateProperty<BorderSide>(value),
    'Color' => $RelaxedWidgetStateProperty<Color>(value),
    'EdgeInsetsGeometry' => $RelaxedWidgetStateProperty<EdgeInsetsGeometry>(value),
    'Icon' => $RelaxedWidgetStateProperty<Icon>(value),
    'IconThemeData' => $RelaxedWidgetStateProperty<IconThemeData>(value),
    'MouseCursor' => $RelaxedWidgetStateProperty<MouseCursor>(value),
    'OutlinedBorder' => $RelaxedWidgetStateProperty<OutlinedBorder>(value),
    'Size' => $RelaxedWidgetStateProperty<Size>(value),
    'TextStyle' => $RelaxedWidgetStateProperty<TextStyle>(value),
    'Widget' => $RelaxedWidgetStateProperty<Widget>(value),
    'bool' => $RelaxedWidgetStateProperty<bool>(value),
    'double' => $RelaxedWidgetStateProperty<double>(value),
    _ => null,
  };
}


/// Auto-generated relaxer factory for WidgetStateProperty — flutter_cupertino layer types.
Object? _relaxWidgetStateProperty$cupertino(Object value, String innerTypeArg) {
  if (value is! WidgetStateProperty) return null;
  return switch (innerTypeArg) {
    'Color' => $RelaxedWidgetStateProperty<Color>(value),
    'Icon' => $RelaxedWidgetStateProperty<Icon>(value),
    'MouseCursor' => $RelaxedWidgetStateProperty<MouseCursor>(value),
    'double' => $RelaxedWidgetStateProperty<double>(value),
    _ => null,
  };
}


// =============================================================================
// Registration
// =============================================================================

/// Register all auto-generated relaxer factories with the D4 runtime.
///
/// Call this once during bridge setup — replaces the old hand-written
/// `registerGenericTypeRelaxers()` function.
void registerRelaxers() {
  D4.registerGenericTypeWrapper('AbstractLayoutBuilder', _relaxAbstractLayoutBuilder$widgets);
  D4.registerGenericTypeWrapper('Action', _relaxAction$widgets);
  D4.registerGenericTypeWrapper('Action', _relaxAction$material);
  D4.registerGenericTypeWrapper('Action', _relaxAction$cupertino);
  D4.registerGenericTypeWrapper('Adaptation', _relaxAdaptation$material);
  D4.registerGenericTypeWrapper('Animatable', _relaxAnimatable$animation);
  D4.registerGenericTypeWrapper('Animatable', _relaxAnimatable$rendering);
  D4.registerGenericTypeWrapper('Animatable', _relaxAnimatable$widgets);
  D4.registerGenericTypeWrapper('Animatable', _relaxAnimatable$material);
  D4.registerGenericTypeWrapper('Animation', _relaxAnimation$animation);
  D4.registerGenericTypeWrapper('Animation', _relaxAnimation$rendering);
  D4.registerGenericTypeWrapper('Animation', _relaxAnimation$widgets);
  D4.registerGenericTypeWrapper('Animation', _relaxAnimation$material);
  D4.registerGenericTypeWrapper('Animation', _relaxAnimation$cupertino);
  D4.registerGenericTypeWrapper('AnnotationResult', _relaxAnnotationResult$rendering);
  D4.registerGenericTypeWrapper('CalendarDelegate', _relaxCalendarDelegate$material);
  D4.registerGenericTypeWrapper('CustomClipper', _relaxCustomClipper$rendering);
  D4.registerGenericTypeWrapper('CustomClipper', _relaxCustomClipper$widgets);
  D4.registerGenericTypeWrapper('DateTimeRange', _relaxDateTimeRange$material);
  D4.registerGenericTypeWrapper('DisposableBuildContext', _relaxDisposableBuildContext$widgets);
  D4.registerGenericTypeWrapper('DragBoundaryDelegate', _relaxDragBoundaryDelegate$widgets);
  D4.registerGenericTypeWrapper('DragBoundaryDelegate', _relaxDragBoundaryDelegate$material);
  D4.registerGenericTypeWrapper('DragTargetDetails', _relaxDragTargetDetails$widgets);
  D4.registerGenericTypeWrapper('Draggable', _relaxDraggable$widgets);
  D4.registerGenericTypeWrapper('Draggable', _relaxDraggable$material);
  D4.registerGenericTypeWrapper('Draggable', _relaxDraggable$cupertino);
  D4.registerGenericTypeWrapper('Factory', _relaxFactory$rendering);
  D4.registerGenericTypeWrapper('Factory', _relaxFactory$widgets);
  D4.registerGenericTypeWrapper('GestureRecognizerFactory', _relaxGestureRecognizerFactory$widgets);
  D4.registerGenericTypeWrapper('GlobalKey', _relaxGlobalKey$widgets);
  D4.registerGenericTypeWrapper('GlobalKey', _relaxGlobalKey$material);
  D4.registerGenericTypeWrapper('GlobalKey', _relaxGlobalKey$cupertino);
  D4.registerGenericTypeWrapper('HitTestEntry', _relaxHitTestEntry$gestures);
  D4.registerGenericTypeWrapper('HitTestEntry', _relaxHitTestEntry$rendering);
  D4.registerGenericTypeWrapper('HitTestEntry', _relaxHitTestEntry$widgets);
  D4.registerGenericTypeWrapper('ImageProvider', _relaxImageProvider$painting);
  D4.registerGenericTypeWrapper('ImageProvider', _relaxImageProvider$widgets);
  D4.registerGenericTypeWrapper('ImageProvider', _relaxImageProvider$material);
  D4.registerGenericTypeWrapper('ImageProvider', _relaxImageProvider$cupertino);
  D4.registerGenericTypeWrapper('IndexedSlot', _relaxIndexedSlot$widgets);
  D4.registerGenericTypeWrapper('InheritedNotifier', _relaxInheritedNotifier$widgets);
  D4.registerGenericTypeWrapper('LocalizationsDelegate', _relaxLocalizationsDelegate$widgets);
  D4.registerGenericTypeWrapper('Page', _relaxPage$widgets);
  D4.registerGenericTypeWrapper('ParentDataWidget', _relaxParentDataWidget$widgets);
  D4.registerGenericTypeWrapper('PopEntry', _relaxPopEntry$widgets);
  D4.registerGenericTypeWrapper('PopEntry', _relaxPopEntry$material);
  D4.registerGenericTypeWrapper('PopEntry', _relaxPopEntry$cupertino);
  D4.registerGenericTypeWrapper('RenderAnnotatedRegion', _relaxRenderAnnotatedRegion$widgets);
  D4.registerGenericTypeWrapper('RenderObjectToWidgetAdapter', _relaxRenderObjectToWidgetAdapter$widgets);
  D4.registerGenericTypeWrapper('RenderObjectToWidgetElement', _relaxRenderObjectToWidgetElement$widgets);
  D4.registerGenericTypeWrapper('RenderObjectWithChildMixin', _relaxRenderObjectWithChildMixin$widgets);
  D4.registerGenericTypeWrapper('RestorableProperty', _relaxRestorableProperty$widgets);
  D4.registerGenericTypeWrapper('RestorableProperty', _relaxRestorableProperty$material);
  D4.registerGenericTypeWrapper('Route', _relaxRoute$widgets);
  D4.registerGenericTypeWrapper('RouteInformationParser', _relaxRouteInformationParser$widgets);
  D4.registerGenericTypeWrapper('RouteInformationParser', _relaxRouteInformationParser$material);
  D4.registerGenericTypeWrapper('RouteInformationParser', _relaxRouteInformationParser$cupertino);
  D4.registerGenericTypeWrapper('RouterConfig', _relaxRouterConfig$widgets);
  D4.registerGenericTypeWrapper('RouterConfig', _relaxRouterConfig$material);
  D4.registerGenericTypeWrapper('RouterConfig', _relaxRouterConfig$cupertino);
  D4.registerGenericTypeWrapper('RouterDelegate', _relaxRouterDelegate$widgets);
  D4.registerGenericTypeWrapper('RouterDelegate', _relaxRouterDelegate$material);
  D4.registerGenericTypeWrapper('RouterDelegate', _relaxRouterDelegate$cupertino);
  D4.registerGenericTypeWrapper('State', _relaxState$widgets);
  D4.registerGenericTypeWrapper('ToggleableStateMixin', _relaxToggleableStateMixin$widgets);
  D4.registerGenericTypeWrapper('TreeSliverNode', _relaxTreeSliverNode$widgets);
  D4.registerGenericTypeWrapper('Tween', _relaxTween$animation);
  D4.registerGenericTypeWrapper('Tween', _relaxTween$widgets);
  D4.registerGenericTypeWrapper('TweenSequenceItem', _relaxTweenSequenceItem$animation);
  D4.registerGenericTypeWrapper('ValueListenable', _relaxValueListenable$widgets);
  D4.registerGenericTypeWrapper('ValueListenable', _relaxValueListenable$material);
  D4.registerGenericTypeWrapper('ValueListenable', _relaxValueListenable$cupertino);
  D4.registerGenericTypeWrapper('ValueNotifier', _relaxValueNotifier$rendering);
  D4.registerGenericTypeWrapper('ValueNotifier', _relaxValueNotifier$widgets);
  D4.registerGenericTypeWrapper('ValueNotifier', _relaxValueNotifier$material);
  D4.registerGenericTypeWrapper('ValueNotifier', _relaxValueNotifier$cupertino);
  D4.registerGenericTypeWrapper('WidgetStateProperty', _relaxWidgetStateProperty$widgets);
  D4.registerGenericTypeWrapper('WidgetStateProperty', _relaxWidgetStateProperty$material);
  D4.registerGenericTypeWrapper('WidgetStateProperty', _relaxWidgetStateProperty$cupertino);
}

