/// D4rt Proxy Classes for flutter_material_bridges
///
/// Generated proxy/adapter subclasses that delegate abstract methods
/// to callback functions, enabling D4rt scripts to implement
/// abstract delegates.
///
/// DO NOT EDIT — generated by d4rtgen proxy generator.
library;

// ignore_for_file: unused_import, invalid_use_of_protected_member, unnecessary_non_null_assertion, invalid_use_of_visible_for_testing_member

import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/widgets.dart';
import 'package:tom_d4rt_ast/runtime.dart';

/// D4rt proxy for [CustomPainter].
///
/// Delegates abstract methods to callback functions, enabling
/// D4rt scripts to implement [CustomPainter] via named
/// function parameters.
class D4rtCustomPainter extends CustomPainter {
  /// Callback for [CustomPainter.paint].
  final void Function(Canvas, Size) onPaint;

  /// Callback for [CustomPainter.shouldRepaint].
  final bool Function(CustomPainter) onShouldRepaint;

  /// Callback for [CustomPainter.addListener].
  final void Function(void Function())? onAddListener;

  /// Callback for [CustomPainter.removeListener].
  final void Function(void Function())? onRemoveListener;

  /// Callback for [CustomPainter.shouldRebuildSemantics].
  final bool Function(CustomPainter)? onShouldRebuildSemantics;

  /// Callback for [CustomPainter.hitTest].
  final bool? Function(Offset)? onHitTest;

  /// Callback for [CustomPainter.semanticsBuilder].
  final List<CustomPainterSemantics> Function(Size)? Function()? onSemanticsBuilder;

  /// Creates a [D4rtCustomPainter] with callback implementations.
  D4rtCustomPainter({
    required this.onPaint,
    required this.onShouldRepaint,
    this.onAddListener,
    this.onRemoveListener,
    this.onShouldRebuildSemantics,
    this.onHitTest,
    this.onSemanticsBuilder,
  });

  @override
  void paint(Canvas canvas, Size size) =>
      onPaint(canvas, size);

  @override
  bool shouldRepaint(CustomPainter oldDelegate) =>
      onShouldRepaint(oldDelegate);

  @override
  void addListener(void Function() listener) =>
      onAddListener != null ? onAddListener!(listener) : super.addListener(listener);

  @override
  void removeListener(void Function() listener) =>
      onRemoveListener != null ? onRemoveListener!(listener) : super.removeListener(listener);

  @override
  bool shouldRebuildSemantics(CustomPainter oldDelegate) =>
      onShouldRebuildSemantics != null ? onShouldRebuildSemantics!(oldDelegate) : super.shouldRebuildSemantics(oldDelegate);

  @override
  bool? hitTest(Offset position) =>
      onHitTest != null ? onHitTest!(position) : super.hitTest(position);

  @override
  List<CustomPainterSemantics> Function(Size)? get semanticsBuilder => onSemanticsBuilder != null ? onSemanticsBuilder!() : super.semanticsBuilder;

}

/// D4rt proxy for [CustomClipper].
///
/// Delegates abstract methods to callback functions, enabling
/// D4rt scripts to implement [CustomClipper] via named
/// function parameters.
class D4rtCustomClipper<T> extends CustomClipper<T> {
  /// Callback for [CustomClipper.getClip].
  final T Function(Size) onGetClip;

  /// Callback for [CustomClipper.shouldReclip].
  final bool Function(CustomClipper<T>) onShouldReclip;

  /// Callback for [CustomClipper.addListener].
  final void Function(void Function())? onAddListener;

  /// Callback for [CustomClipper.removeListener].
  final void Function(void Function())? onRemoveListener;

  /// Callback for [CustomClipper.getApproximateClipRect].
  final Rect Function(Size)? onGetApproximateClipRect;

  /// Creates a [D4rtCustomClipper] with callback implementations.
  D4rtCustomClipper({
    required this.onGetClip,
    required this.onShouldReclip,
    this.onAddListener,
    this.onRemoveListener,
    this.onGetApproximateClipRect,
  });

  @override
  T getClip(Size size) =>
      onGetClip(size);

  @override
  bool shouldReclip(CustomClipper<T> oldClipper) =>
      onShouldReclip(oldClipper);

  @override
  void addListener(void Function() listener) =>
      onAddListener != null ? onAddListener!(listener) : super.addListener(listener);

  @override
  void removeListener(void Function() listener) =>
      onRemoveListener != null ? onRemoveListener!(listener) : super.removeListener(listener);

  @override
  Rect getApproximateClipRect(Size size) =>
      onGetApproximateClipRect != null ? onGetApproximateClipRect!(size) : super.getApproximateClipRect(size);

}

/// D4rt proxy for [FlowDelegate].
///
/// Delegates abstract methods to callback functions, enabling
/// D4rt scripts to implement [FlowDelegate] via named
/// function parameters.
class D4rtFlowDelegate extends FlowDelegate {
  /// Callback for [FlowDelegate.paintChildren].
  final void Function(FlowPaintingContext) onPaintChildren;

  /// Callback for [FlowDelegate.shouldRepaint].
  final bool Function(FlowDelegate) onShouldRepaint;

  /// Callback for [FlowDelegate.getSize].
  final Size Function(BoxConstraints)? onGetSize;

  /// Callback for [FlowDelegate.getConstraintsForChild].
  final BoxConstraints Function(int, BoxConstraints)? onGetConstraintsForChild;

  /// Callback for [FlowDelegate.shouldRelayout].
  final bool Function(FlowDelegate)? onShouldRelayout;

  /// Creates a [D4rtFlowDelegate] with callback implementations.
  D4rtFlowDelegate({
    required this.onPaintChildren,
    required this.onShouldRepaint,
    this.onGetSize,
    this.onGetConstraintsForChild,
    this.onShouldRelayout,
  });

  @override
  void paintChildren(FlowPaintingContext context) =>
      onPaintChildren(context);

  @override
  bool shouldRepaint(FlowDelegate oldDelegate) =>
      onShouldRepaint(oldDelegate);

  @override
  Size getSize(BoxConstraints constraints) =>
      onGetSize != null ? onGetSize!(constraints) : super.getSize(constraints);

  @override
  BoxConstraints getConstraintsForChild(int i, BoxConstraints constraints) =>
      onGetConstraintsForChild != null ? onGetConstraintsForChild!(i, constraints) : super.getConstraintsForChild(i, constraints);

  @override
  bool shouldRelayout(FlowDelegate oldDelegate) =>
      onShouldRelayout != null ? onShouldRelayout!(oldDelegate) : super.shouldRelayout(oldDelegate);

}

/// D4rt proxy for [MultiChildLayoutDelegate].
///
/// Delegates abstract methods to callback functions, enabling
/// D4rt scripts to implement [MultiChildLayoutDelegate] via named
/// function parameters.
class D4rtMultiChildLayoutDelegate extends MultiChildLayoutDelegate {
  /// Callback for [MultiChildLayoutDelegate.performLayout].
  final void Function(Size) onPerformLayout;

  /// Callback for [MultiChildLayoutDelegate.shouldRelayout].
  final bool Function(MultiChildLayoutDelegate) onShouldRelayout;

  /// Callback for [MultiChildLayoutDelegate.hasChild].
  final bool Function(Object)? onHasChild;

  /// Callback for [MultiChildLayoutDelegate.layoutChild].
  final Size Function(Object, BoxConstraints)? onLayoutChild;

  /// Callback for [MultiChildLayoutDelegate.positionChild].
  final void Function(Object, Offset)? onPositionChild;

  /// Callback for [MultiChildLayoutDelegate.getSize].
  final Size Function(BoxConstraints)? onGetSize;

  /// Creates a [D4rtMultiChildLayoutDelegate] with callback implementations.
  D4rtMultiChildLayoutDelegate({
    required this.onPerformLayout,
    required this.onShouldRelayout,
    this.onHasChild,
    this.onLayoutChild,
    this.onPositionChild,
    this.onGetSize,
  });

  @override
  void performLayout(Size size) =>
      onPerformLayout(size);

  @override
  bool shouldRelayout(MultiChildLayoutDelegate oldDelegate) =>
      onShouldRelayout(oldDelegate);

  @override
  bool hasChild(Object childId) =>
      onHasChild != null ? onHasChild!(childId) : super.hasChild(childId);

  @override
  Size layoutChild(Object childId, BoxConstraints constraints) =>
      onLayoutChild != null ? onLayoutChild!(childId, constraints) : super.layoutChild(childId, constraints);

  @override
  void positionChild(Object childId, Offset offset) =>
      onPositionChild != null ? onPositionChild!(childId, offset) : super.positionChild(childId, offset);

  @override
  Size getSize(BoxConstraints constraints) =>
      onGetSize != null ? onGetSize!(constraints) : super.getSize(constraints);

}

/// D4rt proxy for [SingleChildLayoutDelegate].
///
/// Delegates abstract methods to callback functions, enabling
/// D4rt scripts to implement [SingleChildLayoutDelegate] via named
/// function parameters.
class D4rtSingleChildLayoutDelegate extends SingleChildLayoutDelegate {
  /// Callback for [SingleChildLayoutDelegate.shouldRelayout].
  final bool Function(SingleChildLayoutDelegate) onShouldRelayout;

  /// Callback for [SingleChildLayoutDelegate.getSize].
  final Size Function(BoxConstraints)? onGetSize;

  /// Callback for [SingleChildLayoutDelegate.getConstraintsForChild].
  final BoxConstraints Function(BoxConstraints)? onGetConstraintsForChild;

  /// Callback for [SingleChildLayoutDelegate.getPositionForChild].
  final Offset Function(Size, Size)? onGetPositionForChild;

  /// Creates a [D4rtSingleChildLayoutDelegate] with callback implementations.
  D4rtSingleChildLayoutDelegate({
    required this.onShouldRelayout,
    this.onGetSize,
    this.onGetConstraintsForChild,
    this.onGetPositionForChild,
  });

  @override
  bool shouldRelayout(SingleChildLayoutDelegate oldDelegate) =>
      onShouldRelayout(oldDelegate);

  @override
  Size getSize(BoxConstraints constraints) =>
      onGetSize != null ? onGetSize!(constraints) : super.getSize(constraints);

  @override
  BoxConstraints getConstraintsForChild(BoxConstraints constraints) =>
      onGetConstraintsForChild != null ? onGetConstraintsForChild!(constraints) : super.getConstraintsForChild(constraints);

  @override
  Offset getPositionForChild(Size size, Size childSize) =>
      onGetPositionForChild != null ? onGetPositionForChild!(size, childSize) : super.getPositionForChild(size, childSize);

}

/// D4rt proxy for [SliverPersistentHeaderDelegate].
///
/// Delegates abstract methods to callback functions, enabling
/// D4rt scripts to implement [SliverPersistentHeaderDelegate] via named
/// function parameters.
class D4rtSliverPersistentHeaderDelegate extends SliverPersistentHeaderDelegate {
  /// Callback for [SliverPersistentHeaderDelegate.build].
  final Widget Function(BuildContext, double, bool) onBuild;

  /// Callback for [SliverPersistentHeaderDelegate.shouldRebuild].
  final bool Function(SliverPersistentHeaderDelegate) onShouldRebuild;

  /// Callback for [SliverPersistentHeaderDelegate.minExtent].
  final double Function() onMinExtent;

  /// Callback for [SliverPersistentHeaderDelegate.maxExtent].
  final double Function() onMaxExtent;

  /// Callback for [SliverPersistentHeaderDelegate.vsync].
  final TickerProvider? Function()? onVsync;

  /// Callback for [SliverPersistentHeaderDelegate.snapConfiguration].
  final FloatingHeaderSnapConfiguration? Function()? onSnapConfiguration;

  /// Callback for [SliverPersistentHeaderDelegate.stretchConfiguration].
  final OverScrollHeaderStretchConfiguration? Function()? onStretchConfiguration;

  /// Callback for [SliverPersistentHeaderDelegate.showOnScreenConfiguration].
  final PersistentHeaderShowOnScreenConfiguration? Function()? onShowOnScreenConfiguration;

  /// Creates a [D4rtSliverPersistentHeaderDelegate] with callback implementations.
  D4rtSliverPersistentHeaderDelegate({
    required this.onBuild,
    required this.onShouldRebuild,
    required this.onMinExtent,
    required this.onMaxExtent,
    this.onVsync,
    this.onSnapConfiguration,
    this.onStretchConfiguration,
    this.onShowOnScreenConfiguration,
  });

  @override
  Widget build(BuildContext context, double shrinkOffset, bool overlapsContent) =>
      onBuild(context, shrinkOffset, overlapsContent);

  @override
  bool shouldRebuild(SliverPersistentHeaderDelegate oldDelegate) =>
      onShouldRebuild(oldDelegate);

  @override
  double get minExtent => onMinExtent();

  @override
  double get maxExtent => onMaxExtent();

  @override
  TickerProvider? get vsync => onVsync != null ? onVsync!() : super.vsync;

  @override
  FloatingHeaderSnapConfiguration? get snapConfiguration => onSnapConfiguration != null ? onSnapConfiguration!() : super.snapConfiguration;

  @override
  OverScrollHeaderStretchConfiguration? get stretchConfiguration => onStretchConfiguration != null ? onStretchConfiguration!() : super.stretchConfiguration;

  @override
  PersistentHeaderShowOnScreenConfiguration? get showOnScreenConfiguration => onShowOnScreenConfiguration != null ? onShowOnScreenConfiguration!() : super.showOnScreenConfiguration;

}

/// D4rt proxy for [DataTableSource].
///
/// Delegates abstract methods to callback functions, enabling
/// D4rt scripts to implement [DataTableSource] via named
/// function parameters.
class D4rtDataTableSource extends DataTableSource {
  /// Callback for [DataTableSource.getRow].
  final DataRow? Function(int) onGetRow;

  /// Callback for [DataTableSource.rowCount].
  final int Function() onRowCount;

  /// Callback for [DataTableSource.isRowCountApproximate].
  final bool Function() onIsRowCountApproximate;

  /// Callback for [DataTableSource.selectedRowCount].
  final int Function() onSelectedRowCount;

  /// Callback for [DataTableSource.addListener].
  final void Function(void Function())? onAddListener;

  /// Callback for [DataTableSource.removeListener].
  final void Function(void Function())? onRemoveListener;

  /// Callback for [DataTableSource.dispose].
  final void Function()? onDispose;

  /// Callback for [DataTableSource.notifyListeners].
  final void Function()? onNotifyListeners;

  /// Callback for [DataTableSource.hasListeners].
  final bool Function()? onHasListeners;

  /// Creates a [D4rtDataTableSource] with callback implementations.
  D4rtDataTableSource({
    required this.onGetRow,
    required this.onRowCount,
    required this.onIsRowCountApproximate,
    required this.onSelectedRowCount,
    this.onAddListener,
    this.onRemoveListener,
    this.onDispose,
    this.onNotifyListeners,
    this.onHasListeners,
  });

  @override
  DataRow? getRow(int index) =>
      onGetRow(index);

  @override
  int get rowCount => onRowCount();

  @override
  bool get isRowCountApproximate => onIsRowCountApproximate();

  @override
  int get selectedRowCount => onSelectedRowCount();

  @override
  void addListener(void Function() listener) =>
      onAddListener != null ? onAddListener!(listener) : super.addListener(listener);

  @override
  void removeListener(void Function() listener) =>
      onRemoveListener != null ? onRemoveListener!(listener) : super.removeListener(listener);

  @override
  void dispose() =>
      onDispose != null ? onDispose!() : super.dispose();

  @override
  void notifyListeners() =>
      onNotifyListeners != null ? onNotifyListeners!() : super.notifyListeners();

  @override
  bool get hasListeners => onHasListeners != null ? onHasListeners!() : super.hasListeners;

}

// =========================================================================
// Proxy Factory Registration (GEN-092)
// =========================================================================

/// Registers interface proxy factories for all generated proxy classes.
///
/// Call this during bridge initialization to enable D4rt scripts to
/// create interpreted subclasses of these abstract classes.
/// Each factory bridges InterpretedInstance method calls to native
/// proxy callbacks.
void registerProxyFactories() {
  // Register factory for CustomPainter
  D4.registerInterfaceProxy('CustomPainter', (visitor, instance) {
    return D4rtCustomPainter(
      onPaint: (Canvas canvas, Size size) {
        final method = instance.klass.findInstanceMethod('paint');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [canvas, size], {});
          return;
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement paint');
      },
      onShouldRepaint: (CustomPainter oldDelegate) {
        final method = instance.klass.findInstanceMethod('shouldRepaint');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [oldDelegate], {});
          return D4.extractBridgedArg<bool>(result, 'shouldRepaint');
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement shouldRepaint');
      },
      onAddListener: instance.klass.findInstanceMethod('addListener') != null
          ? (void Function() listener) {
        final method = instance.klass.findInstanceMethod('addListener');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [listener], {});
          return;
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement addListener');
          }
          : null,
      onRemoveListener: instance.klass.findInstanceMethod('removeListener') != null
          ? (void Function() listener) {
        final method = instance.klass.findInstanceMethod('removeListener');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [listener], {});
          return;
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement removeListener');
          }
          : null,
      onShouldRebuildSemantics: instance.klass.findInstanceMethod('shouldRebuildSemantics') != null
          ? (CustomPainter oldDelegate) {
        final method = instance.klass.findInstanceMethod('shouldRebuildSemantics');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [oldDelegate], {});
          return D4.extractBridgedArg<bool>(result, 'shouldRebuildSemantics');
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement shouldRebuildSemantics');
          }
          : null,
      onHitTest: instance.klass.findInstanceMethod('hitTest') != null
          ? (Offset position) {
        final method = instance.klass.findInstanceMethod('hitTest');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [position], {});
          return D4.extractBridgedArg<bool?>(result, 'hitTest');
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement hitTest');
          }
          : null,
      onSemanticsBuilder: instance.klass.findInstanceGetter('semanticsBuilder') != null
          ? () {
        final getter = instance.klass.findInstanceGetter('semanticsBuilder');
        if (getter != null) {
          final result = getter.bind(instance).call(visitor, [], {});
          return D4.extractBridgedArg<List<CustomPainterSemantics> Function(Size)?>(result, 'semanticsBuilder');
        }
        try {
          final field = instance.getField('semanticsBuilder');
          return D4.extractBridgedArg<List<CustomPainterSemantics> Function(Size)?>(field, 'semanticsBuilder');
        } catch (_) {}
        throw StateError('Interpreted class ${instance.klass.name} does not implement semanticsBuilder');
          }
          : null,
    );
  });

  // Register factory for CustomClipper
  D4.registerInterfaceProxy('CustomClipper', (visitor, instance) {
    return D4rtCustomClipper(
      onGetClip: (Size size) {
        final method = instance.klass.findInstanceMethod('getClip');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [size], {});
          return D4.extractBridgedArg<dynamic>(result, 'getClip');
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement getClip');
      },
      onShouldReclip: (CustomClipper<dynamic> oldClipper) {
        final method = instance.klass.findInstanceMethod('shouldReclip');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [oldClipper], {});
          return D4.extractBridgedArg<bool>(result, 'shouldReclip');
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement shouldReclip');
      },
      onAddListener: instance.klass.findInstanceMethod('addListener') != null
          ? (void Function() listener) {
        final method = instance.klass.findInstanceMethod('addListener');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [listener], {});
          return;
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement addListener');
          }
          : null,
      onRemoveListener: instance.klass.findInstanceMethod('removeListener') != null
          ? (void Function() listener) {
        final method = instance.klass.findInstanceMethod('removeListener');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [listener], {});
          return;
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement removeListener');
          }
          : null,
      onGetApproximateClipRect: instance.klass.findInstanceMethod('getApproximateClipRect') != null
          ? (Size size) {
        final method = instance.klass.findInstanceMethod('getApproximateClipRect');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [size], {});
          return D4.extractBridgedArg<Rect>(result, 'getApproximateClipRect');
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement getApproximateClipRect');
          }
          : null,
    );
  });

  // Register factory for FlowDelegate
  D4.registerInterfaceProxy('FlowDelegate', (visitor, instance) {
    return D4rtFlowDelegate(
      onPaintChildren: (FlowPaintingContext context) {
        final method = instance.klass.findInstanceMethod('paintChildren');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [context], {});
          return;
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement paintChildren');
      },
      onShouldRepaint: (FlowDelegate oldDelegate) {
        final method = instance.klass.findInstanceMethod('shouldRepaint');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [oldDelegate], {});
          return D4.extractBridgedArg<bool>(result, 'shouldRepaint');
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement shouldRepaint');
      },
      onGetSize: instance.klass.findInstanceMethod('getSize') != null
          ? (BoxConstraints constraints) {
        final method = instance.klass.findInstanceMethod('getSize');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [constraints], {});
          return D4.extractBridgedArg<Size>(result, 'getSize');
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement getSize');
          }
          : null,
      onGetConstraintsForChild: instance.klass.findInstanceMethod('getConstraintsForChild') != null
          ? (int i, BoxConstraints constraints) {
        final method = instance.klass.findInstanceMethod('getConstraintsForChild');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [i, constraints], {});
          return D4.extractBridgedArg<BoxConstraints>(result, 'getConstraintsForChild');
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement getConstraintsForChild');
          }
          : null,
      onShouldRelayout: instance.klass.findInstanceMethod('shouldRelayout') != null
          ? (FlowDelegate oldDelegate) {
        final method = instance.klass.findInstanceMethod('shouldRelayout');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [oldDelegate], {});
          return D4.extractBridgedArg<bool>(result, 'shouldRelayout');
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement shouldRelayout');
          }
          : null,
    );
  });

  // Register factory for MultiChildLayoutDelegate
  D4.registerInterfaceProxy('MultiChildLayoutDelegate', (visitor, instance) {
    return D4rtMultiChildLayoutDelegate(
      onPerformLayout: (Size size) {
        final method = instance.klass.findInstanceMethod('performLayout');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [size], {});
          return;
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement performLayout');
      },
      onShouldRelayout: (MultiChildLayoutDelegate oldDelegate) {
        final method = instance.klass.findInstanceMethod('shouldRelayout');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [oldDelegate], {});
          return D4.extractBridgedArg<bool>(result, 'shouldRelayout');
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement shouldRelayout');
      },
      onHasChild: instance.klass.findInstanceMethod('hasChild') != null
          ? (Object childId) {
        final method = instance.klass.findInstanceMethod('hasChild');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [childId], {});
          return D4.extractBridgedArg<bool>(result, 'hasChild');
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement hasChild');
          }
          : null,
      onLayoutChild: instance.klass.findInstanceMethod('layoutChild') != null
          ? (Object childId, BoxConstraints constraints) {
        final method = instance.klass.findInstanceMethod('layoutChild');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [childId, constraints], {});
          return D4.extractBridgedArg<Size>(result, 'layoutChild');
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement layoutChild');
          }
          : null,
      onPositionChild: instance.klass.findInstanceMethod('positionChild') != null
          ? (Object childId, Offset offset) {
        final method = instance.klass.findInstanceMethod('positionChild');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [childId, offset], {});
          return;
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement positionChild');
          }
          : null,
      onGetSize: instance.klass.findInstanceMethod('getSize') != null
          ? (BoxConstraints constraints) {
        final method = instance.klass.findInstanceMethod('getSize');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [constraints], {});
          return D4.extractBridgedArg<Size>(result, 'getSize');
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement getSize');
          }
          : null,
    );
  });

  // Register factory for SingleChildLayoutDelegate
  D4.registerInterfaceProxy('SingleChildLayoutDelegate', (visitor, instance) {
    return D4rtSingleChildLayoutDelegate(
      onShouldRelayout: (SingleChildLayoutDelegate oldDelegate) {
        final method = instance.klass.findInstanceMethod('shouldRelayout');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [oldDelegate], {});
          return D4.extractBridgedArg<bool>(result, 'shouldRelayout');
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement shouldRelayout');
      },
      onGetSize: instance.klass.findInstanceMethod('getSize') != null
          ? (BoxConstraints constraints) {
        final method = instance.klass.findInstanceMethod('getSize');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [constraints], {});
          return D4.extractBridgedArg<Size>(result, 'getSize');
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement getSize');
          }
          : null,
      onGetConstraintsForChild: instance.klass.findInstanceMethod('getConstraintsForChild') != null
          ? (BoxConstraints constraints) {
        final method = instance.klass.findInstanceMethod('getConstraintsForChild');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [constraints], {});
          return D4.extractBridgedArg<BoxConstraints>(result, 'getConstraintsForChild');
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement getConstraintsForChild');
          }
          : null,
      onGetPositionForChild: instance.klass.findInstanceMethod('getPositionForChild') != null
          ? (Size size, Size childSize) {
        final method = instance.klass.findInstanceMethod('getPositionForChild');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [size, childSize], {});
          return D4.extractBridgedArg<Offset>(result, 'getPositionForChild');
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement getPositionForChild');
          }
          : null,
    );
  });

  // Register factory for SliverPersistentHeaderDelegate
  D4.registerInterfaceProxy('SliverPersistentHeaderDelegate', (visitor, instance) {
    return D4rtSliverPersistentHeaderDelegate(
      onBuild: (BuildContext context, double shrinkOffset, bool overlapsContent) {
        final method = instance.klass.findInstanceMethod('build');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [context, shrinkOffset, overlapsContent], {});
          return D4.extractBridgedArg<Widget>(result, 'build');
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement build');
      },
      onShouldRebuild: (SliverPersistentHeaderDelegate oldDelegate) {
        final method = instance.klass.findInstanceMethod('shouldRebuild');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [oldDelegate], {});
          return D4.extractBridgedArg<bool>(result, 'shouldRebuild');
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement shouldRebuild');
      },
      onMinExtent: () {
        final getter = instance.klass.findInstanceGetter('minExtent');
        if (getter != null) {
          final result = getter.bind(instance).call(visitor, [], {});
          return D4.extractBridgedArg<double>(result, 'minExtent');
        }
        try {
          final field = instance.getField('minExtent');
          return D4.extractBridgedArg<double>(field, 'minExtent');
        } catch (_) {}
        throw StateError('Interpreted class ${instance.klass.name} does not implement minExtent');
      },
      onMaxExtent: () {
        final getter = instance.klass.findInstanceGetter('maxExtent');
        if (getter != null) {
          final result = getter.bind(instance).call(visitor, [], {});
          return D4.extractBridgedArg<double>(result, 'maxExtent');
        }
        try {
          final field = instance.getField('maxExtent');
          return D4.extractBridgedArg<double>(field, 'maxExtent');
        } catch (_) {}
        throw StateError('Interpreted class ${instance.klass.name} does not implement maxExtent');
      },
      onVsync: instance.klass.findInstanceGetter('vsync') != null
          ? () {
        final getter = instance.klass.findInstanceGetter('vsync');
        if (getter != null) {
          final result = getter.bind(instance).call(visitor, [], {});
          return D4.extractBridgedArg<TickerProvider?>(result, 'vsync');
        }
        try {
          final field = instance.getField('vsync');
          return D4.extractBridgedArg<TickerProvider?>(field, 'vsync');
        } catch (_) {}
        throw StateError('Interpreted class ${instance.klass.name} does not implement vsync');
          }
          : null,
      onSnapConfiguration: instance.klass.findInstanceGetter('snapConfiguration') != null
          ? () {
        final getter = instance.klass.findInstanceGetter('snapConfiguration');
        if (getter != null) {
          final result = getter.bind(instance).call(visitor, [], {});
          return D4.extractBridgedArg<FloatingHeaderSnapConfiguration?>(result, 'snapConfiguration');
        }
        try {
          final field = instance.getField('snapConfiguration');
          return D4.extractBridgedArg<FloatingHeaderSnapConfiguration?>(field, 'snapConfiguration');
        } catch (_) {}
        throw StateError('Interpreted class ${instance.klass.name} does not implement snapConfiguration');
          }
          : null,
      onStretchConfiguration: instance.klass.findInstanceGetter('stretchConfiguration') != null
          ? () {
        final getter = instance.klass.findInstanceGetter('stretchConfiguration');
        if (getter != null) {
          final result = getter.bind(instance).call(visitor, [], {});
          return D4.extractBridgedArg<OverScrollHeaderStretchConfiguration?>(result, 'stretchConfiguration');
        }
        try {
          final field = instance.getField('stretchConfiguration');
          return D4.extractBridgedArg<OverScrollHeaderStretchConfiguration?>(field, 'stretchConfiguration');
        } catch (_) {}
        throw StateError('Interpreted class ${instance.klass.name} does not implement stretchConfiguration');
          }
          : null,
      onShowOnScreenConfiguration: instance.klass.findInstanceGetter('showOnScreenConfiguration') != null
          ? () {
        final getter = instance.klass.findInstanceGetter('showOnScreenConfiguration');
        if (getter != null) {
          final result = getter.bind(instance).call(visitor, [], {});
          return D4.extractBridgedArg<PersistentHeaderShowOnScreenConfiguration?>(result, 'showOnScreenConfiguration');
        }
        try {
          final field = instance.getField('showOnScreenConfiguration');
          return D4.extractBridgedArg<PersistentHeaderShowOnScreenConfiguration?>(field, 'showOnScreenConfiguration');
        } catch (_) {}
        throw StateError('Interpreted class ${instance.klass.name} does not implement showOnScreenConfiguration');
          }
          : null,
    );
  });

  // Register factory for DataTableSource
  D4.registerInterfaceProxy('DataTableSource', (visitor, instance) {
    return D4rtDataTableSource(
      onGetRow: (int index) {
        final method = instance.klass.findInstanceMethod('getRow');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [index], {});
          return D4.extractBridgedArg<DataRow?>(result, 'getRow');
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement getRow');
      },
      onRowCount: () {
        final getter = instance.klass.findInstanceGetter('rowCount');
        if (getter != null) {
          final result = getter.bind(instance).call(visitor, [], {});
          return D4.extractBridgedArg<int>(result, 'rowCount');
        }
        try {
          final field = instance.getField('rowCount');
          return D4.extractBridgedArg<int>(field, 'rowCount');
        } catch (_) {}
        throw StateError('Interpreted class ${instance.klass.name} does not implement rowCount');
      },
      onIsRowCountApproximate: () {
        final getter = instance.klass.findInstanceGetter('isRowCountApproximate');
        if (getter != null) {
          final result = getter.bind(instance).call(visitor, [], {});
          return D4.extractBridgedArg<bool>(result, 'isRowCountApproximate');
        }
        try {
          final field = instance.getField('isRowCountApproximate');
          return D4.extractBridgedArg<bool>(field, 'isRowCountApproximate');
        } catch (_) {}
        throw StateError('Interpreted class ${instance.klass.name} does not implement isRowCountApproximate');
      },
      onSelectedRowCount: () {
        final getter = instance.klass.findInstanceGetter('selectedRowCount');
        if (getter != null) {
          final result = getter.bind(instance).call(visitor, [], {});
          return D4.extractBridgedArg<int>(result, 'selectedRowCount');
        }
        try {
          final field = instance.getField('selectedRowCount');
          return D4.extractBridgedArg<int>(field, 'selectedRowCount');
        } catch (_) {}
        throw StateError('Interpreted class ${instance.klass.name} does not implement selectedRowCount');
      },
      onAddListener: instance.klass.findInstanceMethod('addListener') != null
          ? (void Function() listener) {
        final method = instance.klass.findInstanceMethod('addListener');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [listener], {});
          return;
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement addListener');
          }
          : null,
      onRemoveListener: instance.klass.findInstanceMethod('removeListener') != null
          ? (void Function() listener) {
        final method = instance.klass.findInstanceMethod('removeListener');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [listener], {});
          return;
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement removeListener');
          }
          : null,
      onDispose: instance.klass.findInstanceMethod('dispose') != null
          ? () {
        final method = instance.klass.findInstanceMethod('dispose');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [], {});
          return;
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement dispose');
          }
          : null,
      onNotifyListeners: instance.klass.findInstanceMethod('notifyListeners') != null
          ? () {
        final method = instance.klass.findInstanceMethod('notifyListeners');
        if (method != null) {
          final result = method.bind(instance).call(visitor, [], {});
          return;
        }
        throw StateError('Interpreted class ${instance.klass.name} does not implement notifyListeners');
          }
          : null,
      onHasListeners: instance.klass.findInstanceGetter('hasListeners') != null
          ? () {
        final getter = instance.klass.findInstanceGetter('hasListeners');
        if (getter != null) {
          final result = getter.bind(instance).call(visitor, [], {});
          return D4.extractBridgedArg<bool>(result, 'hasListeners');
        }
        try {
          final field = instance.getField('hasListeners');
          return D4.extractBridgedArg<bool>(field, 'hasListeners');
        } catch (_) {}
        throw StateError('Interpreted class ${instance.klass.name} does not implement hasListeners');
          }
          : null,
    );
  });

}

