targets:
  $default:
    builders:
      tom_d4rt_generator:d4rt_bridge_builder:
        options:
          name: d4rt_generator_example
          modules:
            - name: all
              barrelFiles:
                - lib/test_classes.dart
              outputPath: lib/src/d4rt_bridges/example_bridges.b.dart
              barrelImport: "package:d4rt_generator_example/test_classes.dart"
          helpersImport: "package:tom_d4rt/tom_d4rt.dart"
          generateBarrel: true
          barrelPath: lib/d4rt_bridges.b.dart
          generateDartscript: true
          dartscriptPath: lib/dartscript.b.dart
          registrationClass: D4rtGeneratorExampleBridges
          generateTestRunner: true
          testRunnerPath: bin/d4rtrun.b.dart
