/// D4rt RC-2 generic-constructor factory emitter (MCI#6 / B3 — R3).
///
/// The interpreter cannot reify a script's explicit type argument into a real
/// native generic: `GlobalKey<NavigatorState>()` reaches the bridge as a
/// type-erased constructor call, so a plain bridge factory builds
/// `GlobalKey<dynamic>` and the downstream `as GlobalKey<NavigatorState>` cast
/// fails. The fix is a `D4.registerGenericConstructor(class, '', …)` whose body
/// switches on the reified type-arg name and constructs the concrete
/// `Class<T>(…)` per arm.
///
/// These switches were previously hand-written near-verbatim in each twin's
/// `d4rt_runtime_registrations.dart` (`GlobalKey`, `ValueKey`, `ValueNotifier`).
/// This emitter templates them from a [GenericConstructorConfig]. Two body
/// shapes occur in the corpus, selected by [GenericConstructorKind]:
///
/// - [GenericConstructorKind.namedPassthrough] (`GlobalKey`): forward a fixed
///   named-arg set to `Class<T>(named…)`, default arm builds the non-null
///   unparameterized `Class(named…)`.
/// - [GenericConstructorKind.nullableValue] (`ValueKey`, `ValueNotifier`): read
///   `positional[0]` and emit the nullable-aware
///   `value is T ? Class<T>(value) : Class<T?>(value as T?)`, default arm
///   returns `null` so the bridge ctor infers `T` from the runtime value.
///
/// The emitter produces a **canonical** form (the golden pins that contract; the
/// regen-time base-test gate validates behavioural equivalence with the hand
/// code, whose only differences are cosmetic comment drift and switch-arm
/// ordering). `StrutStyle` — the fourth class historically grouped with B3 — is
/// **not** a type-arg switch but a bespoke cross-package coercion constructor
/// slated for `StrutStyleUserBridge` replacement, so it is out of scope here.
library;

import 'bridge_config.dart';

/// Emits the full `D4.registerGenericConstructor(...)` statement for [config],
/// indented two spaces for emission inside the generated
/// `registerGenericConstructors()` function.
///
/// Returns the empty string when [GenericConstructorConfig.typeArgVariants] is
/// empty (nothing to reify). The output is a single statement (trailing newline
/// included).
String generateGenericConstructor(GenericConstructorConfig config) {
  if (config.typeArgVariants.isEmpty) return '';
  return switch (config.kind) {
    GenericConstructorKind.namedPassthrough => _namedPassthrough(config),
    GenericConstructorKind.nullableValue => _nullableValue(config),
  };
}

/// Emits the `_registerGeneratedGenericConstructors()` wrapper function with one
/// [generateGenericConstructor] call per config, in declaration order.
///
/// Returns the empty string when no config contributes output (all empty
/// allow-lists or an empty list), so the committed bridge file is unchanged
/// until at least one constructor is declared.
String generateGenericConstructorRegistrations(
  List<GenericConstructorConfig> configs,
) {
  final bodies = configs
      .map(generateGenericConstructor)
      .where((s) => s.isNotEmpty)
      .toList();
  if (bodies.isEmpty) return '';

  final b = StringBuffer();
  b.writeln('/// Registers the generated RC-2 generic constructor factories');
  b.writeln('/// (MCI#6 B3). Each reifies a script-supplied `<T>` into a');
  b.writeln('/// concrete native generic over a declared type-arg allow-list.');
  b.writeln('void _registerGeneratedGenericConstructors() {');
  for (var i = 0; i < bodies.length; i++) {
    if (i > 0) b.writeln();
    b.write(bodies[i]);
  }
  b.writeln('}');
  return b.toString();
}

/// `GlobalKey`-shaped emission: forward the named-arg set to `Class<T>(named…)`
/// per arm, with a non-null unparameterized `Class(named…)` default.
String _namedPassthrough(GenericConstructorConfig config) {
  final className = config.className;
  // `a: a, b: b` — every arm (including the default) forwards the same set.
  final forwards =
      config.namedArgs.map((a) => '${a.name}: ${a.name}').join(', ');

  final b = StringBuffer();
  b.writeln('  // RC-2 / B3 — reify $className<T> over the declared type-arg');
  b.writeln("  // allow-list so the interpreter's type-erased constructor");
  b.writeln('  // boundary builds the concrete native generic. Generated by the');
  b.writeln('  // d4rtgen generic-constructor generator.');
  b.writeln("  D4.registerGenericConstructor('$className', '',");
  b.writeln('      (visitor, positional, named, typeArgs) {');
  for (final a in config.namedArgs) {
    b.writeln('    final ${a.name} =');
    b.writeln("        D4.extractBridgedArgOrNull<${a.type}>(named['${a.name}'], '${a.name}');");
  }
  b.writeln('    final typeName = (typeArgs != null && typeArgs.isNotEmpty)');
  b.writeln('        ? typeArgs[0].name');
  b.writeln('        : null;');
  b.writeln('    return switch (typeName) {');
  for (final t in config.typeArgVariants) {
    b.writeln("      '$t' => $className<$t>($forwards),");
  }
  b.writeln('      _ => $className($forwards),');
  b.writeln('    };');
  b.writeln('  });');
  return b.toString();
}

/// `ValueKey`/`ValueNotifier`-shaped emission: read `positional[0]` and emit the
/// nullable-aware ternary per arm, with a `null` default (the bridge ctor infers
/// `T`). An optional leading `dynamic|Object|Object?` arm builds `Class<dynamic>`.
String _nullableValue(GenericConstructorConfig config) {
  final className = config.className;

  final b = StringBuffer();
  b.writeln('  // RC-2 / B3 — reify $className<T> over the declared type-arg');
  b.writeln('  // allow-list with nullable-aware construction; an unlisted or');
  b.writeln('  // absent <T> returns null so the bridge ctor infers T from the');
  b.writeln('  // runtime value. Generated by the d4rtgen generic-constructor');
  b.writeln('  // generator.');
  b.writeln("  D4.registerGenericConstructor('$className', '',");
  b.writeln('      (visitor, positional, named, typeArgs) {');
  b.writeln('    final value = positional.isNotEmpty ? positional[0] : null;');
  b.writeln('    final typeName = (typeArgs != null && typeArgs.isNotEmpty)');
  b.writeln('        ? typeArgs[0].name');
  b.writeln('        : null;');
  b.writeln('    return switch (typeName) {');
  if (config.includeDynamicArm) {
    b.writeln(
        "      'dynamic' || 'Object' || 'Object?' => $className<dynamic>(value),");
  }
  for (final t in config.typeArgVariants) {
    b.writeln("      '$t' => value is $t");
    b.writeln('          ? $className<$t>(value)');
    b.writeln('          : $className<$t?>(value as $t?),');
  }
  b.writeln('      _ => null,');
  b.writeln('    };');
  b.writeln('  });');
  return b.toString();
}
