/// D4rt generic method/static interceptor re-dispatch emitter (MCI#8 / B4 — R4).
///
/// Some Flutter lookups are keyed by the *exact* reified type argument — e.g.
/// `RadioGroup.maybeOf<T>(context)` resolves via
/// `dependOnInheritedWidgetOfExactType<_RadioGroupStateScope<T>>()`. The
/// generated bridge adapter forwards such calls without `<T>`, collapsing the
/// lookup to `<dynamic>` and missing the concrete `_RadioGroupStateScope<String>`
/// in the tree. The interpreter exposes an interceptor hook at the top of these
/// adapters (`D4.findBridgedMethodInterceptor` / `findBridgedStaticMethodInterceptor`);
/// the interceptor body was previously hand-written in each twin's
/// `d4rt_runtime_registrations.dart` and re-dispatched the generic over an
/// allow-list of common type-arg names.
///
/// This emitter templates exactly that **re-dispatch half** from a
/// [GenericInterceptorConfig]. The R5 ancestor-walk fallback for script-defined
/// `<T>` stays hand-written (retired later by MCI#11): supply it via
/// [GenericInterceptorConfig.fallbackExpr] and the generated body chains to it
/// when the switch returns null.
///
/// The emitter produces a **canonical** form (the golden pins that contract;
/// the regen-time base-test gate validates behavioural equivalence with the
/// hand code, whose only differences are cosmetic comment drift and switch-arm
/// ordering). Generalising the forwarded argument list beyond the single
/// `BuildContext` is a follow-up should a second shape arise.
library;

import 'bridge_config.dart';

/// Emits the full `D4.registerBridged{,Static}MethodInterceptor(...)` call for
/// [config], including the re-dispatch `switch (typeName)` over its type-arg
/// allow-list.
///
/// Returns the empty string when [GenericInterceptorConfig.typeArgVariants] is
/// empty (nothing to re-dispatch). The output is a single statement (trailing
/// newline included) suitable for emission inside the generated interceptor
/// registration function.
String generateGenericInterceptor(GenericInterceptorConfig config) {
  if (config.typeArgVariants.isEmpty) return '';

  final className = config.className;
  final methodName = config.methodName;
  final ctxIndex = config.contextArgIndex;
  final ctxType = config.contextArgType;
  // Static re-dispatch targets the class itself; instance re-dispatch targets
  // the validated receiver.
  final receiver = config.isStatic ? className : 't';

  final registerFn = config.isStatic
      ? 'registerBridgedStaticMethodInterceptor'
      : 'registerBridgedMethodInterceptor';
  final lambdaParams = config.isStatic
      ? '(visitor, positional, named, typeArgs)'
      : '(visitor, target, positional, named, typeArgs)';

  final b = StringBuffer();
  b.writeln('  // MCI#8 — re-dispatch $className.$methodName<T> over the declared');
  b.writeln("  // type-arg allow-list so the type-erased bridge boundary doesn't");
  b.writeln('  // collapse <T> to <dynamic>. Generated by the d4rtgen generic-');
  b.writeln('  // interceptor generator.');
  b.writeln("  D4.$registerFn('$className', '$methodName',");
  b.writeln('      $lambdaParams {');
  if (!config.isStatic) {
    b.writeln('    final t = target is $className ? target : null;');
    b.writeln('    if (t == null) return null;');
  }
  b.writeln('    if (positional.length <= $ctxIndex) return null;');
  b.writeln('    final ctx = positional[$ctxIndex];');
  b.writeln('    if (ctx is! $ctxType) return null;');
  b.writeln('    final typeName = (typeArgs != null && typeArgs.isNotEmpty)');
  b.writeln('        ? typeArgs[0].name');
  b.writeln('        : null;');
  b.writeln('    final byType = switch (typeName) {');
  for (final t in config.typeArgVariants) {
    b.writeln("      '$t' => $receiver.$methodName<$t>(ctx),");
  }
  b.writeln('      _ => null,');
  b.writeln('    };');
  final fallback = config.fallbackExpr;
  if (fallback != null) {
    b.writeln('    if (byType != null) return byType;');
    b.writeln('    return $fallback;');
  } else {
    b.writeln('    return byType;');
  }
  b.writeln('  });');
  return b.toString();
}

/// Emits the `_registerGeneratedGenericInterceptors()` function wrapping one
/// [generateGenericInterceptor] call per config, in declaration order.
///
/// Returns the empty string when no config contributes output (all empty
/// allow-lists or an empty list), so the committed bridge file is unchanged
/// until at least one interceptor is declared.
String generateGenericInterceptorRegistrations(
  List<GenericInterceptorConfig> configs,
) {
  final bodies = configs
      .map(generateGenericInterceptor)
      .where((s) => s.isNotEmpty)
      .toList();
  if (bodies.isEmpty) return '';

  final b = StringBuffer();
  b.writeln('/// Registers the generated generic re-dispatch interceptors');
  b.writeln('/// (MCI#8). Each forwards a script-supplied `<T>` to a native');
  b.writeln('/// generic call over a declared type-arg allow-list.');
  b.writeln('void _registerGeneratedGenericInterceptors() {');
  for (var i = 0; i < bodies.length; i++) {
    if (i > 0) b.writeln();
    b.write(bodies[i]);
  }
  b.writeln('}');
  return b.toString();
}
