/// D4rt generic-type-argument proxy-variant emitter (MCI#6 / B1).
///
/// An invariant generic delegate such as `CustomClipper<T>` cannot be backed
/// by a single `CustomClipper<Path>` proxy: when a script declares
/// `extends CustomClipper<RRect>`, Flutter's downstream
/// `_RenderCustomClip<RRect>._clip = clipper.getClip(size)` cast fails with
/// `_NativePath is not a subtype of RRect`. The fix is one **typed** proxy per
/// concrete type argument, each returning a non-null fallback of its own `T`,
/// plus a `registerInterfaceProxy` selector that picks the variant matching the
/// script's reified bridged-super type argument
/// (`instance.klass.bridgedSuperTypeArgNames[0]`).
///
/// These four `_InterpretedCustomClipper{Path,Rect,RRect,RSuperellipse}`
/// classes were previously hand-written near-verbatim in each twin's
/// `d4rt_runtime_registrations.dart`. This emitter replaces them with one
/// parameterized template: the per-variant pieces are just the type argument
/// `T` and the non-null [TypeArgProxyVariant.defaultExpr]. The emitter produces
/// a **canonical** form (the golden pins that contract; the regen-time
/// base-test gate validates behavioural equivalence with the hand code, whose
/// only differences are cosmetic doc-comment drift and switch-arm ordering).
///
/// The abstract method shape is `CustomClipper`'s (`T getClip(Size size)` plus
/// the secondary `bool shouldReclip(covariant CustomClipper<T> oldClipper)`),
/// which is the sole B1 case. Generalising to arbitrary single-method typed
/// variants is a follow-up should a second case arise.
library;

import 'bridge_config.dart';

/// Emits the typed proxy-variant classes for [config] in declaration order.
///
/// Returns the concatenated class definitions (each separated by a blank
/// line), or the empty string when [ProxyClassConfig.typeArgVariants] is empty.
/// The proxy class name is `_Interpreted${className}${typeArg}` — e.g.
/// `_InterpretedCustomClipperRRect`.
String generateTypeArgProxyClasses(ProxyClassConfig config) {
  if (config.typeArgVariants.isEmpty) return '';
  final buffer = StringBuffer();
  for (var i = 0; i < config.typeArgVariants.length; i++) {
    if (i > 0) buffer.writeln();
    buffer.write(generateTypeArgProxyVariant(config.className, config.typeArgVariants[i]));
  }
  return buffer.toString();
}

/// Emits one typed proxy-variant class for [variant] backing interpreted
/// subclasses of `$baseClassName<${variant.typeArg}>`.
String generateTypeArgProxyVariant(
  String baseClassName,
  TypeArgProxyVariant variant,
) {
  final t = variant.typeArg;
  final def = variant.defaultExpr;
  final proxyName = '_Interpreted$baseClassName$t';
  final b = StringBuffer();
  b.writeln('/// Native [$baseClassName<$t>] backing an interpreted subclass');
  b.writeln('/// declared as `extends $baseClassName<$t>`.');
  b.writeln('///');
  b.writeln('/// Generated by the d4rtgen proxy generator (MCI#6 typeArgVariants).');
  b.writeln('class $proxyName extends $baseClassName<$t> {');
  b.writeln('  $proxyName(this._visitor, this._instance);');
  b.writeln();
  b.writeln('  final InterpreterVisitor _visitor;');
  b.writeln('  final InterpretedInstance _instance;');
  b.writeln();
  b.writeln('  @override');
  b.writeln('  $t getClip(Size size) {');
  b.writeln("    final method = _instance.klass.findInstanceMethod('getClip');");
  b.writeln('    if (method == null) return $def;');
  b.writeln('    try {');
  b.writeln('      final raw = method.bind(_instance).call(_visitor, [size], {});');
  b.writeln('      if (raw is $t) return raw;');
  b.writeln('    } catch (_) {}');
  b.writeln('    return $def;');
  b.writeln('  }');
  b.writeln();
  b.writeln('  @override');
  b.writeln('  bool shouldReclip(covariant $baseClassName<$t> oldClipper) {');
  b.writeln("    final method = _instance.klass.findInstanceMethod('shouldReclip');");
  b.writeln('    if (method == null) return false;');
  b.writeln('    try {');
  b.writeln('      final raw = method.bind(_instance).call(_visitor, [oldClipper], {});');
  b.writeln('      if (raw is bool) return raw;');
  b.writeln('    } catch (_) {}');
  b.writeln('    return false;');
  b.writeln('  }');
  b.writeln('}');
  return b.toString();
}

/// Emits the `registerInterfaceProxy` selector that dispatches to the typed
/// variant matching the script's reified bridged-super type argument.
///
/// The **first** entry in [ProxyClassConfig.typeArgVariants] is the default arm
/// (matched when the script gives no type argument or an unlisted one); the
/// remaining entries each get a `case` arm. Returns the empty string when no
/// variants are configured.
String generateTypeArgProxySelector(ProxyClassConfig config) {
  if (config.typeArgVariants.isEmpty) return '';
  final className = config.className;
  final variants = config.typeArgVariants;
  final defaultVariant = variants.first;
  final caseVariants = variants.skip(1);

  String proxyCtor(TypeArgProxyVariant v) =>
      '_Interpreted$className${v.typeArg}(visitor, instance)';

  final b = StringBuffer();
  b.writeln('  // MCI#6 — pick the typed $className proxy variant that matches');
  b.writeln("  // the script's reified bridged-super type argument so Flutter's");
  b.writeln('  // downstream invariant-generic cast succeeds. Generated by the');
  b.writeln('  // d4rtgen proxy generator (typeArgVariants).');
  b.writeln("  D4.registerInterfaceProxy('$className', (visitor, instance) {");
  b.writeln('    final typeArgNames = instance.klass.bridgedSuperTypeArgNames;');
  b.writeln('    final firstArg = (typeArgNames != null && typeArgNames.isNotEmpty)');
  b.writeln('        ? typeArgNames[0]');
  b.writeln("        : '';");
  b.writeln('    final Object proxy;');
  b.writeln('    switch (firstArg) {');
  for (final v in caseVariants) {
    b.writeln("      case '${v.typeArg}':");
    b.writeln('        proxy = ${proxyCtor(v)};');
    b.writeln('        break;');
  }
  b.writeln('      default:');
  b.writeln('        proxy = ${proxyCtor(defaultVariant)};');
  b.writeln('        break;');
  b.writeln('    }');
  b.writeln('    instance.nativeProxy ??= proxy;');
  b.writeln('    return proxy;');
  b.writeln('  });');
  return b.toString();
}

/// Convenience: the variant classes followed by a blank line and the selector.
///
/// In the real bridge file the classes live in the top-level declaration block
/// and the selector inside `registerD4rtInterfaceProxyOverrides()`; this
/// combined form is primarily for tests and inspection.
String generateTypeArgProxyFamily(ProxyClassConfig config) {
  if (config.typeArgVariants.isEmpty) return '';
  final classes = generateTypeArgProxyClasses(config);
  final selector = generateTypeArgProxySelector(config);
  return '$classes\n$selector';
}
