targets:
  $default:
    builders:
      tom_d4rt_generator:d4rt_bridge_builder:
        options:
          name: user_guide_example
          modules:
            - name: all
              barrelFiles:
                - lib/user_guide_example.dart
              outputPath: lib/src/d4rt_bridges/user_guide_bridges.b.dart
              barrelImport: "package:user_guide_example/user_guide_example.dart"
          helpersImport: "package:tom_d4rt/tom_d4rt.dart"
          generateBarrel: true
          barrelPath: lib/d4rt_bridges.b.dart
          generateDartscript: true
          dartscriptPath: lib/dartscript.b.dart
          registrationClass: UserGuideExampleBridges
          generateTestRunner: true
          testRunnerPath: bin/d4rtrun.b.dart
