// ignore_for_file: avoid_print, deprecated_member_use, sort_child_properties_last
// D4rt test script: Tests InspectorReferenceData from widgets
import 'package:flutter/material.dart';

dynamic build(BuildContext context) {
  print('InspectorReferenceData test executing');
  print('=' * 50);

  // === InspectorReferenceData class tests ===
  // InspectorReferenceData tracks object references in the widget
  // inspector. Does not hold object from garbage collection.

  // Test 1: Class purpose
  print('\nTest 1: Class purpose');
  print('Tracks object references for WidgetInspectorService');
  print('Uses WeakReference to avoid memory leaks');
  print('Annotated with @visibleForTesting');

  // Test 2: Constructor
  print('\nTest 2: Constructor');
  print('InspectorReferenceData(Object object, String id)');
  print('Stores object as WeakReference (for most types)');
  print('Direct storage for: String, num, bool');

  // Test 3: Properties
  print('\nTest 3: Properties');
  print('id: String - unique identifier for the object');
  print('count: int - number of times object referenced');
  print('value: Object? - the referenced object (via getter)');

  // Test 4: WeakReference behavior
  print('\nTest 4: WeakReference behavior');
  print('For complex objects:');
  print('  - Stored as WeakReference<Object>');
  print('  - Can be garbage collected');
  print('  - value getter returns ref.target');
  print('For String, num, bool:');
  print('  - Stored directly (not GC-able via WeakRef)');

  // Test 5: Reference counting
  print('\nTest 5: Reference counting');
  print('count property starts at 1');
  print('Incremented when object re-referenced');
  print('Used for lifecycle management');

  // Test 6: Id generation
  print('\nTest 6: Id pattern');
  print('IDs are unique strings');
  print('Generated by WidgetInspectorService');
  print('Used for VM service protocol');

  // Test 7: Value access
  print('\nTest 7: Value getter');
  print('Object? get value =>');
  print('  _ref?.target ?? _value');
  print('');
  print('Returns null if object was GCd');
  print('Returns direct value for primitives');

  // Test 8: Usage context
  print('\nTest 8: Usage context');
  print('Created by WidgetInspectorService.toId()');
  print('Stored in object groups');
  print('Accessed via WidgetInspectorService.toObject()');

  // Test 9: Memory management
  print('\nTest 9: Memory management');
  print('Groups can be disposed via:');
  print('  WidgetInspectorService.disposeGroup(groupName)');
  print('Ensures inspector doesnt leak memory');

  // Test 10: Type checking
  print('\nTest 10: Special type handling');
  print('Types that skip WeakReference:');
  print('  - String');
  print('  - num (int, double)');
  print('  - bool');
  print('Reason: Not supported by WeakReference');

  print('\n' + '=' * 50);
  print('InspectorReferenceData test completed');

  return Column(
    mainAxisSize: MainAxisSize.min,
    children: [
      Text(
        'InspectorReferenceData Tests',
        style: TextStyle(fontWeight: FontWeight.bold, fontSize: 18),
      ),
      SizedBox(height: 8),
      Text('Tests: 10 categories executed'),
      Text('Type: Reference tracking class'),
      Text('Storage: WeakReference based'),
      Text('Purpose: Inspector object lifecycle'),
    ],
  );
}
