// GENERATED — regenerate with:
//   dart run tool/stdlib_member_diff.dart --baseline
//
// The standing member-coverage baseline for the `dart:*` stdlib bridges, read by
// `member_coverage_baseline_test.dart`. Do not hand-edit: a hand-edited entry is
// an assertion about the interpreter that nothing measured, which is exactly the
// claim this baseline was introduced to stop anyone making.
//
// Current state: 231 confirmed-unreachable members across
// 13 classes, and 37 members on
// 3 classes that cannot be measured at all. Those totals
// are documentation, not assertions — the test derives them from the tables
// below so there is only ever one thing to update.
//
// Regenerating is a normal part of closing a gap and a normal part of adding an
// instance recipe. It is NOT a normal part of making a red suite green: if
// `no previously-reachable member became unreachable` is the test that failed,
// regenerating hides a live defect.

/// Members proven unreachable through the interpreter, per bridged class.
const confirmedGaps = <String, List<String>>{
  'ByteBuffer': [r'asFloat32x4List', r'asFloat64x2List', r'asInt32x4List'],
  'HttpClient': [r'authenticateProxy', r'connectionFactory'],
  'HttpServer': [
    r'any',
    r'asBroadcastStream',
    r'asyncExpand',
    r'asyncMap',
    r'cast',
    r'contains',
    r'distinct',
    r'drain',
    r'elementAt',
    r'every',
    r'expand',
    r'first',
    r'firstWhere',
    r'fold',
    r'forEach',
    r'handleError',
    r'isBroadcast',
    r'isEmpty',
    r'join',
    r'last',
    r'lastWhere',
    r'length',
    r'map',
    r'pipe',
    r'reduce',
    r'single',
    r'singleWhere',
    r'skip',
    r'skipWhile',
    r'take',
    r'takeWhile',
    r'timeout',
    r'toList',
    r'toSet',
    r'transform',
    r'where',
  ],
  'LinkedListEntry': [r'insertAfter', r'insertBefore'],
  'Object': [r'noSuchMethod'],
  'RawDatagramSocket': [
    r'any',
    r'asBroadcastStream',
    r'asyncExpand',
    r'asyncMap',
    r'cast',
    r'contains',
    r'distinct',
    r'drain',
    r'elementAt',
    r'every',
    r'expand',
    r'first',
    r'firstWhere',
    r'fold',
    r'forEach',
    r'handleError',
    r'isBroadcast',
    r'isEmpty',
    r'join',
    r'last',
    r'lastWhere',
    r'length',
    r'map',
    r'pipe',
    r'reduce',
    r'single',
    r'singleWhere',
    r'skip',
    r'skipWhile',
    r'take',
    r'takeWhile',
    r'timeout',
    r'toList',
    r'toSet',
    r'transform',
    r'where',
  ],
  'RawServerSocket': [
    r'any',
    r'asBroadcastStream',
    r'asyncExpand',
    r'asyncMap',
    r'cast',
    r'contains',
    r'distinct',
    r'drain',
    r'elementAt',
    r'every',
    r'expand',
    r'first',
    r'firstWhere',
    r'fold',
    r'forEach',
    r'handleError',
    r'isBroadcast',
    r'isEmpty',
    r'join',
    r'last',
    r'lastWhere',
    r'length',
    r'map',
    r'pipe',
    r'reduce',
    r'single',
    r'singleWhere',
    r'skip',
    r'skipWhile',
    r'take',
    r'takeWhile',
    r'timeout',
    r'toList',
    r'toSet',
    r'transform',
    r'where',
  ],
  'RawSocket': [
    r'any',
    r'asBroadcastStream',
    r'asyncExpand',
    r'asyncMap',
    r'cast',
    r'contains',
    r'distinct',
    r'drain',
    r'elementAt',
    r'every',
    r'expand',
    r'first',
    r'firstWhere',
    r'fold',
    r'forEach',
    r'handleError',
    r'isBroadcast',
    r'isEmpty',
    r'join',
    r'last',
    r'lastWhere',
    r'length',
    r'map',
    r'pipe',
    r'readMessage',
    r'reduce',
    r'sendMessage',
    r'single',
    r'singleWhere',
    r'skip',
    r'skipWhile',
    r'take',
    r'takeWhile',
    r'timeout',
    r'toList',
    r'toSet',
    r'transform',
    r'where',
  ],
  'ReceivePort': [
    r'any',
    r'asBroadcastStream',
    r'asyncExpand',
    r'asyncMap',
    r'cast',
    r'contains',
    r'distinct',
    r'drain',
    r'elementAt',
    r'every',
    r'expand',
    r'firstWhere',
    r'fold',
    r'forEach',
    r'handleError',
    r'join',
    r'lastWhere',
    r'pipe',
    r'reduce',
    r'singleWhere',
    r'skipWhile',
    r'takeWhile',
    r'timeout',
    r'toList',
    r'toSet',
    r'transform',
  ],
  'ServerSocket': [
    r'asBroadcastStream',
    r'asyncExpand',
    r'asyncMap',
    r'cast',
    r'distinct',
    r'drain',
    r'handleError',
    r'pipe',
    r'reduce',
    r'timeout',
  ],
  'Stdin': [
    r'any',
    r'asBroadcastStream',
    r'asyncExpand',
    r'asyncMap',
    r'cast',
    r'contains',
    r'distinct',
    r'drain',
    r'elementAt',
    r'every',
    r'expand',
    r'first',
    r'firstWhere',
    r'fold',
    r'forEach',
    r'handleError',
    r'isBroadcast',
    r'isEmpty',
    r'join',
    r'last',
    r'lastWhere',
    r'length',
    r'map',
    r'pipe',
    r'reduce',
    r'single',
    r'singleWhere',
    r'skip',
    r'skipWhile',
    r'supportsAnsiEscapes',
    r'take',
    r'takeWhile',
    r'timeout',
    r'toList',
    r'toSet',
    r'transform',
    r'where',
  ],
  'Stdout': [r'lineTerminator', r'nonBlocking', r'writeCharCode'],
  'StringConversionSink': [r'asUtf8Sink'],
};

/// Candidates that could not be measured, per bridged class. Each of these has a
/// stated reason in `_notAuditable` in the tool; they are pinned so that a member
/// moving out of this bucket is reported as the new information it is, rather
/// than as a fresh defect.
const unmeasurable = <String, List<String>>{
  'HttpClientRequest': [r'writeCharCode'],
  'HttpClientResponse': [
    r'any',
    r'asBroadcastStream',
    r'asyncExpand',
    r'asyncMap',
    r'cast',
    r'contains',
    r'distinct',
    r'drain',
    r'elementAt',
    r'every',
    r'expand',
    r'first',
    r'firstWhere',
    r'fold',
    r'forEach',
    r'handleError',
    r'isBroadcast',
    r'isEmpty',
    r'join',
    r'last',
    r'lastWhere',
    r'length',
    r'map',
    r'pipe',
    r'reduce',
    r'single',
    r'singleWhere',
    r'skip',
    r'skipWhile',
    r'take',
    r'takeWhile',
    r'timeout',
    r'toList',
    r'toSet',
    r'where',
  ],
  'HttpHeaders': [r'[]'],
};

/// Classes whose instance recipe produced a usable instance when the baseline was
/// taken. A class dropping out of this list means its gaps stopped being
/// measured, which the test reports as a failure rather than as a pass.
const measuredClasses = <String>{
  'AsciiCodec',
  'BigInt',
  'ByteBuffer',
  'ByteData',
  'Converter',
  'DateTime',
  'DoubleLinkedQueue',
  'Duration',
  'Encoding',
  'FileSystemEntityType',
  'Float32List',
  'Float64List',
  'HashMap',
  'HashSet',
  'HtmlEscape',
  'HtmlEscapeMode',
  'HttpClient',
  'HttpServer',
  'Int16List',
  'Int32List',
  'Int64List',
  'Int8List',
  'InternetAddress',
  'InternetAddressType',
  'Iterable',
  'JsonDecoder',
  'JsonEncoder',
  'Latin1Codec',
  'LineSplitter',
  'LinkedHashMap',
  'LinkedHashSet',
  'LinkedList',
  'LinkedListEntry',
  'List',
  'ListQueue',
  'Object',
  'Point',
  'ProcessSignal',
  'ProcessStartMode',
  'Queue',
  'RawDatagramSocket',
  'RawServerSocket',
  'RawSocket',
  'RawSocketEvent',
  'ReceivePort',
  'Rectangle',
  'SendPort',
  'ServerSocket',
  'Set',
  'Socket',
  'SplayTreeMap',
  'SplayTreeSet',
  'Stdin',
  'StdioType',
  'Stdout',
  'StreamController',
  'StreamSubscription',
  'StreamTransformerBase',
  'StreamView',
  'String',
  'StringConversionSink',
  'Symbol',
  'Uint16List',
  'Uint32List',
  'Uint64List',
  'Uint8ClampedList',
  'Uint8List',
  'UnmodifiableListView',
  'Uri',
  'UriData',
  'Utf8Codec',
  'bool',
  'double',
  'int',
  'num',
};
