// scd9_aicx: a fixture that reaches its host by `path:` must resolve the
// host's own dependencies the same way the host does.
//
// A path dependency supplies the SOURCE but not the RESOLUTION. The fixture
// compiles the host's worktree `lib/` against the FIXTURE's lock, so a stale
// fixture lock type-checks current first-party source against an old
// third-party dependency. What the reader is shown is a CFE error inside
// `../../lib/` — a directory the fixture does not own and whose contents are
// correct — and the pubspec that is actually wrong names no version at all.
// Measured instance: every `tom_d4rt_exec/example/*/pubspec.lock` pinned
// `tom_d4rt_ast` 0.19.0 while exec's lib needed 0.20.x, and it surfaced as
// `The getter 'Logger' isn't defined for the type 'ModuleLoader'` plus
// `Bad state: Generating AOT kernel dill failed!`. It cost a full triage cycle
// to rule out as a real defect. The locks are gitignored, so the drift never
// appears in `git status` and accumulates silently.
//
// WHICH PACKAGES ARE COMPARED, and why not all of them. The host's own
// `lib/` is compiled against the host's RUNTIME dependencies, so those are the
// ones whose drift can produce this error; the lock labels them
// `dependency: "direct main"`. Comparing every shared hosted package instead
// reports benign differences — measured 2026-09-12 across all three
// d4rt packages with examples: seven mismatches, every one of them `lints`, a
// dev-only ruleset no library imports.
library;

import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:test/test.dart';
import 'package:tom_d4rt_generator/testing.dart';

/// Writes a `pubspec.lock` naming [packages] as `name: (dependency, version)`.
File writeLock(Directory dir, Map<String, (String, String)> packages) {
  final buffer = StringBuffer('# Generated by pub\npackages:\n');
  packages.forEach((name, entry) {
    final (dependency, version) = entry;
    buffer.write('  $name:\n'
        '    dependency: "$dependency"\n'
        '    description:\n'
        '      name: $name\n'
        '      sha256: "0000"\n'
        '      url: "https://pub.dev"\n'
        '    source: hosted\n'
        '    version: "$version"\n');
  });
  buffer.write('sdks:\n  dart: ">=3.0.0 <4.0.0"\n');
  final file = File(p.join(dir.path, 'pubspec.lock'))
    ..writeAsStringSync(buffer.toString());
  return file;
}

void main() {
  late Directory host;
  late Directory fixture;
  final temps = <Directory>[];

  setUp(() {
    host = Directory.systemTemp.createTempSync('parity_host_');
    fixture = Directory.systemTemp.createTempSync('parity_fixture_');
    temps..add(host)..add(fixture);
  });

  tearDownAll(() {
    for (final d in temps) {
      try {
        d.deleteSync(recursive: true);
      } catch (_) {}
    }
  });

  group('scd9: fixture and host resolve the host\'s dependencies alike', () {
    test(
      'G-PARITY-1: matching resolutions report nothing [2026-09-12] (PASS)',
      () {
        writeLock(host, {
          'tom_d4rt_ast': ('direct main', '0.65.0'),
          'lints': ('direct dev', '6.1.0'),
        });
        writeLock(fixture, {
          'tom_d4rt_ast': ('direct main', '0.65.0'),
          'lints': ('direct dev', '5.1.1'),
        });

        expect(
          compareFixtureResolution(
            hostProjectPath: host.path,
            fixtureProjectPath: fixture.path,
          ),
          isEmpty,
          reason: 'lints differs, but it is dev-only and never compiled into '
              "the host's lib",
        );
      },
    );

    test(
      'G-PARITY-2: a runtime dependency resolved differently is reported with '
      'both versions and the fixture [2026-09-12] (PASS)',
      () {
        writeLock(host, {'tom_d4rt_ast': ('direct main', '0.20.1')});
        writeLock(fixture, {'tom_d4rt_ast': ('direct main', '0.19.0')});

        final mismatches = compareFixtureResolution(
          hostProjectPath: host.path,
          fixtureProjectPath: fixture.path,
        );

        expect(mismatches, hasLength(1));
        final mismatch = mismatches.single;
        expect(mismatch.package, 'tom_d4rt_ast');
        expect(mismatch.hostVersion, '0.20.1');
        expect(mismatch.fixtureVersion, '0.19.0');
        expect(mismatch.fixturePath, fixture.path);
        expect(
          mismatch.toString(),
          allOf(contains('tom_d4rt_ast'), contains('0.19.0'),
              contains('0.20.1')),
        );
      },
    );

    test(
      'G-PARITY-3: a package the fixture does not resolve at all is not a '
      'mismatch [2026-09-12] (PASS)',
      () {
        // A fixture need not use everything the host does.
        writeLock(host, {
          'tom_d4rt_ast': ('direct main', '0.65.0'),
          'archive': ('direct main', '4.0.0'),
        });
        writeLock(fixture, {'tom_d4rt_ast': ('direct main', '0.65.0')});

        expect(
          compareFixtureResolution(
            hostProjectPath: host.path,
            fixtureProjectPath: fixture.path,
          ),
          isEmpty,
        );
      },
    );

    test(
      'G-PARITY-4: a transitive dependency of the host is compared too — the '
      "host's lib imports those as well [2026-09-12] (PASS)",
      () {
        writeLock(host, {'tom_ast_model': ('transitive', '0.4.0')});
        writeLock(fixture, {'tom_ast_model': ('transitive', '0.3.0')});

        expect(
          compareFixtureResolution(
            hostProjectPath: host.path,
            fixtureProjectPath: fixture.path,
          ),
          hasLength(1),
        );
      },
    );

    test(
      'G-PARITY-5: a missing lock on either side reports nothing rather than '
      'guessing [2026-09-12] (PASS)',
      () {
        writeLock(host, {'tom_d4rt_ast': ('direct main', '0.65.0')});
        // fixture has no lock at all: it has never resolved, which is
        // example_resolution_test's business, not this one's.
        expect(
          compareFixtureResolution(
            hostProjectPath: host.path,
            fixtureProjectPath: fixture.path,
          ),
          isEmpty,
        );
      },
    );

    test(
      'G-PARITY-6: describeMismatches names the remedy [2026-09-12] (PASS)',
      () {
        writeLock(host, {'tom_d4rt_ast': ('direct main', '0.20.1')});
        writeLock(fixture, {'tom_d4rt_ast': ('direct main', '0.19.0')});

        final report = describeMismatches(compareFixtureResolution(
          hostProjectPath: host.path,
          fixtureProjectPath: fixture.path,
        ));

        expect(report, contains('dart pub get'));
        expect(report, contains('tom_d4rt_ast'));
        expect(
          report,
          contains('path'),
          reason: 'the reader has to be told why a lock they did not edit '
              "governs a compile of someone else's lib",
        );
      },
    );
  });
}
