/// Tests for the generic method/static interceptor re-dispatch
/// emitter ([generateGenericInterceptor] /
/// [generateGenericInterceptorRegistrations]) and the
/// [GenericInterceptorConfig] data class.
///
/// Some Flutter lookups are keyed by the exact reified type argument
/// (`RadioGroup.maybeOf<T>(context)`); the generated bridge adapter drops `<T>`
/// at the boundary, so the previously hand-written interceptor body
/// re-dispatched the generic over an allow-list of common type-arg names. This
/// emitter templates that re-dispatch half; the ancestor-walk fallback stays
/// hand-written (supplied via `fallbackExpr`).
///
/// These tests pin: the canonical `RadioGroup.maybeOf` static interceptor
/// byte-for-byte (with and without a fallback); the instance-method shape;
/// the dormant empty default (no type-arg variants → empty string); the
/// registration-wrapper function; and the config JSON round-trip.
library;

import 'package:test/test.dart';
import 'package:tom_d4rt_generator/tom_d4rt_generator.dart';

/// The canonical `RadioGroup.maybeOf<T>` static interceptor with a hand-written
/// fallback expression. This is the exact shape the flutterm runtime declared
/// by hand before the emitter existed.
const _radioGroupGolden =
    r'''  // Re-dispatch RadioGroup.maybeOf<T> over the declared
  // type-arg allow-list so the type-erased bridge boundary doesn't
  // collapse <T> to <dynamic>. Generated by the d4rtgen generic-
  // interceptor generator.
  D4.registerBridgedStaticMethodInterceptor('RadioGroup', 'maybeOf',
      (visitor, positional, named, typeArgs) {
    if (positional.length <= 0) return null;
    final ctx = positional[0];
    if (ctx is! BuildContext) return null;
    final typeName = (typeArgs != null && typeArgs.isNotEmpty)
        ? typeArgs[0].name
        : null;
    final byType = switch (typeName) {
      'String' => RadioGroup.maybeOf<String>(ctx),
      'int' => RadioGroup.maybeOf<int>(ctx),
      'double' => RadioGroup.maybeOf<double>(ctx),
      'num' => RadioGroup.maybeOf<num>(ctx),
      'bool' => RadioGroup.maybeOf<bool>(ctx),
      'Object' => RadioGroup.maybeOf<Object>(ctx),
      _ => null,
    };
    if (byType != null) return byType;
    return _radioGroupMaybeOfFallback(visitor, positional, named, typeArgs);
  });
''';

void main() {
  group('GenericInterceptorConfig (G-GMI)', () {
    const radioGroup = GenericInterceptorConfig(
      className: 'RadioGroup',
      methodName: 'maybeOf',
      isStatic: true,
      typeArgVariants: ['String', 'int', 'double', 'num', 'bool', 'Object'],
      fallbackExpr:
          '_radioGroupMaybeOfFallback(visitor, positional, named, typeArgs)',
    );

    test('G-GMI-1: canonical RadioGroup.maybeOf static interceptor byte-for-byte',
        () {
      expect(generateGenericInterceptor(radioGroup), _radioGroupGolden);
    });

    test('G-GMI-2: static interceptor uses the static registry + class receiver',
        () {
      final out = generateGenericInterceptor(radioGroup);
      expect(out, contains('D4.registerBridgedStaticMethodInterceptor'));
      expect(out, contains('(visitor, positional, named, typeArgs) {'));
      // Static re-dispatch targets the class itself.
      expect(out, contains("'String' => RadioGroup.maybeOf<String>(ctx),"));
      // No instance receiver-validation lines for a static interceptor.
      expect(out, isNot(contains('target is RadioGroup')));
    });

    test('G-GMI-3: every declared type-arg becomes a switch arm in order', () {
      final out = generateGenericInterceptor(radioGroup);
      final arms = const ['String', 'int', 'double', 'num', 'bool', 'Object'];
      var prev = -1;
      for (final t in arms) {
        final idx = out.indexOf("'$t' => RadioGroup.maybeOf<$t>(ctx),");
        expect(idx, greaterThan(prev),
            reason: 'arm $t out of declaration order');
        prev = idx;
      }
      // Default arm + closing.
      expect(out, contains('      _ => null,'));
    });

    test('G-GMI-4: with fallbackExpr, switch result is short-circuited then '
        'fallback is returned', () {
      final out = generateGenericInterceptor(radioGroup);
      expect(out, contains('    if (byType != null) return byType;'));
      expect(
          out,
          contains(
              '    return _radioGroupMaybeOfFallback(visitor, positional, named, typeArgs);'));
    });

    test('G-GMI-5: without fallbackExpr, the switch result is returned directly',
        () {
      const noFallback = GenericInterceptorConfig(
        className: 'RadioGroup',
        methodName: 'maybeOf',
        isStatic: true,
        typeArgVariants: ['String', 'int'],
      );
      final out = generateGenericInterceptor(noFallback);
      expect(out, contains('    return byType;'));
      expect(out, isNot(contains('if (byType != null) return byType;')));
    });

    test('G-GMI-6: instance interceptor validates the receiver and targets it',
        () {
      const themeExt = GenericInterceptorConfig(
        className: 'ThemeData',
        methodName: 'extension',
        typeArgVariants: ['MyExt'],
      );
      final out = generateGenericInterceptor(themeExt);
      expect(out, contains('D4.registerBridgedMethodInterceptor'));
      expect(out, contains('(visitor, target, positional, named, typeArgs) {'));
      expect(out, contains('    final t = target is ThemeData ? target : null;'));
      expect(out, contains('    if (t == null) return null;'));
      // Instance re-dispatch targets the validated receiver `t`.
      expect(out, contains("'MyExt' => t.extension<MyExt>(ctx),"));
    });

    test('G-GMI-7: empty type-arg allow-list emits nothing (dormant default)',
        () {
      const dormant = GenericInterceptorConfig(
        className: 'RadioGroup',
        methodName: 'maybeOf',
        isStatic: true,
      );
      expect(generateGenericInterceptor(dormant), isEmpty);
    });

    test('G-GMI-8: contextArgIndex + contextArgType customise the guard', () {
      const cfg = GenericInterceptorConfig(
        className: 'Foo',
        methodName: 'bar',
        isStatic: true,
        typeArgVariants: ['String'],
        contextArgIndex: 1,
        contextArgType: 'Element',
      );
      final out = generateGenericInterceptor(cfg);
      expect(out, contains('    if (positional.length <= 1) return null;'));
      expect(out, contains('    final ctx = positional[1];'));
      expect(out, contains('    if (ctx is! Element) return null;'));
    });

    test('G-GMI-9: registrations wrapper emits one body per config', () {
      const second = GenericInterceptorConfig(
        className: 'Foo',
        methodName: 'bar',
        isStatic: true,
        typeArgVariants: ['String'],
      );
      final out = generateGenericInterceptorRegistrations([radioGroup, second]);
      expect(out, contains('void _registerGeneratedGenericInterceptors() {'));
      expect(out, contains("D4.registerBridgedStaticMethodInterceptor('RadioGroup', 'maybeOf',"));
      expect(out, contains("D4.registerBridgedStaticMethodInterceptor('Foo', 'bar',"));
      expect(out.trimRight(), endsWith('}'));
    });

    test('G-GMI-10: registrations wrapper is empty when no config contributes',
        () {
      expect(generateGenericInterceptorRegistrations(const []), isEmpty);
      expect(
        generateGenericInterceptorRegistrations(const [
          GenericInterceptorConfig(className: 'A', methodName: 'b'),
        ]),
        isEmpty,
      );
    });

    test('G-GMI-11: config JSON round-trips through fromJson/toJson', () {
      final json = radioGroup.toJson();
      final restored = GenericInterceptorConfig.fromJson(json);
      expect(restored.toJson(), json);
      expect(restored.className, 'RadioGroup');
      expect(restored.methodName, 'maybeOf');
      expect(restored.isStatic, isTrue);
      expect(restored.typeArgVariants,
          ['String', 'int', 'double', 'num', 'bool', 'Object']);
      expect(restored.fallbackExpr, radioGroup.fallbackExpr);
    });

    test('G-GMI-12: toJson omits defaulted fields', () {
      const minimal = GenericInterceptorConfig(
        className: 'A',
        methodName: 'b',
        typeArgVariants: ['String'],
      );
      final json = minimal.toJson();
      expect(json.containsKey('isStatic'), isFalse);
      expect(json.containsKey('contextArgIndex'), isFalse);
      expect(json.containsKey('contextArgType'), isFalse);
      expect(json.containsKey('fallbackExpr'), isFalse);
      expect(json['typeArgVariants'], ['String']);
    });

    test('G-GMI-13: fromJson rejects missing className/methodName', () {
      expect(
        () => GenericInterceptorConfig.fromJson({'className': 'A'}),
        throwsArgumentError,
      );
      expect(
        () => GenericInterceptorConfig.fromJson({'methodName': 'b'}),
        throwsArgumentError,
      );
    });

    test('G-GMI-14: fromYaml accepts a Map and rejects non-Map', () {
      final cfg = GenericInterceptorConfig.fromYaml({
        'className': 'RadioGroup',
        'methodName': 'maybeOf',
        'isStatic': true,
        'typeArgVariants': ['String', 'int'],
      });
      expect(cfg.className, 'RadioGroup');
      expect(cfg.typeArgVariants, ['String', 'int']);
      expect(() => GenericInterceptorConfig.fromYaml('nope'),
          throwsArgumentError);
    });
  });

  group('BridgeConfig genericInterceptors wiring (G-GMI-BC)', () {
    const radioGroup = GenericInterceptorConfig(
      className: 'RadioGroup',
      methodName: 'maybeOf',
      isStatic: true,
      typeArgVariants: ['String', 'int', 'double', 'num', 'bool', 'Object'],
      fallbackExpr:
          '_radioGroupMaybeOfFallback(visitor, positional, named, typeArgs)',
    );

    Map<String, dynamic> baseJson() => {
          'name': 'flutterm',
          'modules': <dynamic>[],
        };

    test('G-GMI-BC-1: defaults to an empty list', () {
      final config = BridgeConfig.fromJson(baseJson());
      expect(config.genericInterceptors, isEmpty);
      // Dormant by default: toJson omits the key entirely.
      expect(config.toJson().containsKey('genericInterceptors'), isFalse);
    });

    test('G-GMI-BC-2: fromJson parses declared interceptors', () {
      final config = BridgeConfig.fromJson({
        ...baseJson(),
        'genericInterceptors': [radioGroup.toJson()],
      });
      expect(config.genericInterceptors, hasLength(1));
      final gi = config.genericInterceptors.single;
      expect(gi.className, 'RadioGroup');
      expect(gi.methodName, 'maybeOf');
      expect(gi.isStatic, isTrue);
      expect(gi.typeArgVariants,
          ['String', 'int', 'double', 'num', 'bool', 'Object']);
      expect(gi.fallbackExpr, radioGroup.fallbackExpr);
    });

    test('G-GMI-BC-3: round-trips through BridgeConfig.toJson/fromJson', () {
      final config = BridgeConfig.fromJson({
        ...baseJson(),
        'genericInterceptors': [radioGroup.toJson()],
      });
      final restored = BridgeConfig.fromJson(config.toJson());
      expect(restored.genericInterceptors.single.toJson(), radioGroup.toJson());
    });

    test('G-GMI-BC-4: copyWith replaces genericInterceptors', () {
      final base = BridgeConfig.fromJson(baseJson());
      final updated = base.copyWith(genericInterceptors: [radioGroup]);
      expect(base.genericInterceptors, isEmpty);
      expect(updated.genericInterceptors, [radioGroup]);
      // Omitting the argument preserves the existing list.
      expect(updated.copyWith().genericInterceptors, [radioGroup]);
    });
  });
}
