/// Tests for the RC-2 generic-constructor reifier emitter (`genericConstructors`)
/// ([generateGenericConstructor] /
/// [generateGenericConstructorRegistrations]) and the
/// [GenericConstructorConfig] data class.
///
/// The interpreter cannot reify a script's explicit type argument into a real
/// native generic — `GlobalKey<NavigatorState>()` reaches the bridge as a
/// type-erased constructor call, so a plain bridge factory builds
/// `GlobalKey<dynamic>` and the downstream cast fails. The fix is a
/// `D4.registerGenericConstructor(class, '', …)` whose body switches on the
/// reified type-arg name and constructs the concrete `Class<T>(…)` per arm.
///
/// Two body shapes occur in the corpus, selected by [GenericConstructorKind]:
/// [GenericConstructorKind.namedPassthrough] (`GlobalKey`) and
/// [GenericConstructorKind.nullableValue] (`ValueKey`, `ValueNotifier`).
///
/// These tests pin: the canonical `GlobalKey` named-passthrough body and the
/// canonical `ValueKey` nullable-value body byte-for-byte; the `ValueNotifier`
/// dynamic-arm variant; the dormant empty default (no type-arg variants → empty
/// string); the registration-wrapper function; and the config JSON round-trip.
library;

import 'package:test/test.dart';
import 'package:tom_d4rt_generator/tom_d4rt_generator.dart';

/// The canonical `GlobalKey<T>` named-passthrough reifier. This is the exact
/// shape the flutterm runtime declared by hand before the emitter existed.
const _globalKeyGolden =
    r'''  // RC-2 — reify GlobalKey<T> over the declared type-arg
  // allow-list so the interpreter's type-erased constructor
  // boundary builds the concrete native generic. Generated by the
  // d4rtgen generic-constructor generator.
  D4.registerGenericConstructor('GlobalKey', '',
      (visitor, positional, named, typeArgs) {
    final debugLabel =
        D4.extractBridgedArgOrNull<String>(named['debugLabel'], 'debugLabel');
    final typeName = (typeArgs != null && typeArgs.isNotEmpty)
        ? typeArgs[0].name
        : null;
    return switch (typeName) {
      'NavigatorState' => GlobalKey<NavigatorState>(debugLabel: debugLabel),
      'FormState' => GlobalKey<FormState>(debugLabel: debugLabel),
      'ScaffoldState' => GlobalKey<ScaffoldState>(debugLabel: debugLabel),
      _ => GlobalKey(debugLabel: debugLabel),
    };
  });
''';

/// The canonical `ValueKey<T>` nullable-value reifier (no dynamic arm).
const _valueKeyGolden =
    r'''  // RC-2 — reify ValueKey<T> over the declared type-arg
  // allow-list with nullable-aware construction; an unlisted or
  // absent <T> returns null so the bridge ctor infers T from the
  // runtime value. Generated by the d4rtgen generic-constructor
  // generator.
  D4.registerGenericConstructor('ValueKey', '',
      (visitor, positional, named, typeArgs) {
    final value = positional.isNotEmpty ? positional[0] : null;
    final typeName = (typeArgs != null && typeArgs.isNotEmpty)
        ? typeArgs[0].name
        : null;
    return switch (typeName) {
      'String' => value is String
          ? ValueKey<String>(value)
          : ValueKey<String?>(value as String?),
      'int' => value is int
          ? ValueKey<int>(value)
          : ValueKey<int?>(value as int?),
      _ => null,
    };
  });
''';

void main() {
  group('GenericConstructorConfig emitter (G-GCC)', () {
    const globalKey = GenericConstructorConfig(
      className: 'GlobalKey',
      kind: GenericConstructorKind.namedPassthrough,
      typeArgVariants: ['NavigatorState', 'FormState', 'ScaffoldState'],
      namedArgs: [GenericCtorNamedArg(name: 'debugLabel', type: 'String')],
    );

    const valueKey = GenericConstructorConfig(
      className: 'ValueKey',
      kind: GenericConstructorKind.nullableValue,
      typeArgVariants: ['String', 'int'],
    );

    const valueNotifier = GenericConstructorConfig(
      className: 'ValueNotifier',
      kind: GenericConstructorKind.nullableValue,
      typeArgVariants: ['String', 'int', 'double', 'bool'],
      includeDynamicArm: true,
    );

    test('G-GCC-1: canonical GlobalKey named-passthrough body byte-for-byte',
        () {
      expect(generateGenericConstructor(globalKey), _globalKeyGolden);
    });

    test('G-GCC-2: canonical ValueKey nullable-value body byte-for-byte', () {
      expect(generateGenericConstructor(valueKey), _valueKeyGolden);
    });

    test('G-GCC-3: every declared type-arg becomes a switch arm in order '
        '(named-passthrough)', () {
      final out = generateGenericConstructor(globalKey);
      const arms = ['NavigatorState', 'FormState', 'ScaffoldState'];
      var prev = -1;
      for (final t in arms) {
        final idx =
            out.indexOf("'$t' => GlobalKey<$t>(debugLabel: debugLabel),");
        expect(idx, greaterThan(prev),
            reason: 'arm $t out of declaration order');
        prev = idx;
      }
      // Default arm constructs the non-null unparameterized class.
      expect(out, contains('      _ => GlobalKey(debugLabel: debugLabel),'));
    });

    test('G-GCC-4: nullable-value arms emit the is/as ternary; default is null',
        () {
      final out = generateGenericConstructor(valueKey);
      expect(
          out,
          contains("      'String' => value is String\n"
              '          ? ValueKey<String>(value)\n'
              '          : ValueKey<String?>(value as String?),'));
      expect(out, contains('      _ => null,'));
    });

    test('G-GCC-5: includeDynamicArm prepends the dynamic|Object|Object? arm',
        () {
      final out = generateGenericConstructor(valueNotifier);
      expect(
          out,
          contains("      'dynamic' || 'Object' || 'Object?' => "
              'ValueNotifier<dynamic>(value),'));
      // The dynamic arm precedes the first concrete arm.
      expect(out.indexOf("'dynamic' || 'Object' || 'Object?'"),
          lessThan(out.indexOf("'String' => value is String")));
    });

    test('G-GCC-6: no dynamic arm when includeDynamicArm is false', () {
      final out = generateGenericConstructor(valueKey);
      expect(out, isNot(contains("'dynamic' || 'Object' || 'Object?'")));
    });

    test('G-GCC-7: empty type-arg allow-list emits nothing (dormant default)',
        () {
      const dormant = GenericConstructorConfig(
        className: 'GlobalKey',
        kind: GenericConstructorKind.namedPassthrough,
      );
      expect(generateGenericConstructor(dormant), isEmpty);
    });

    test('G-GCC-8: registrations wrapper emits one body per config', () {
      final out = generateGenericConstructorRegistrations(
          [globalKey, valueKey, valueNotifier]);
      expect(out, contains('void _registerGeneratedGenericConstructors() {'));
      expect(out, contains("D4.registerGenericConstructor('GlobalKey', '',"));
      expect(out, contains("D4.registerGenericConstructor('ValueKey', '',"));
      expect(
          out, contains("D4.registerGenericConstructor('ValueNotifier', '',"));
      expect(out.trimRight(), endsWith('}'));
    });

    test('G-GCC-9: registrations wrapper is empty when no config contributes',
        () {
      expect(generateGenericConstructorRegistrations(const []), isEmpty);
      expect(
        generateGenericConstructorRegistrations(const [
          GenericConstructorConfig(
            className: 'GlobalKey',
            kind: GenericConstructorKind.namedPassthrough,
          ),
        ]),
        isEmpty,
      );
    });

    test('G-GCC-10: multiple named args forward as a comma-separated set', () {
      const twoArgs = GenericConstructorConfig(
        className: 'Foo',
        kind: GenericConstructorKind.namedPassthrough,
        typeArgVariants: ['Bar'],
        namedArgs: [
          GenericCtorNamedArg(name: 'a', type: 'int'),
          GenericCtorNamedArg(name: 'b', type: 'String'),
        ],
      );
      final out = generateGenericConstructor(twoArgs);
      expect(out, contains("'Bar' => Foo<Bar>(a: a, b: b),"));
      expect(out, contains('      _ => Foo(a: a, b: b),'));
    });
  });

  group('GenericConstructorConfig data class (G-GCC-DC)', () {
    const globalKey = GenericConstructorConfig(
      className: 'GlobalKey',
      kind: GenericConstructorKind.namedPassthrough,
      typeArgVariants: ['NavigatorState', 'FormState'],
      namedArgs: [GenericCtorNamedArg(name: 'debugLabel', type: 'String')],
    );

    test('G-GCC-DC-1: config JSON round-trips through fromJson/toJson', () {
      final json = globalKey.toJson();
      final restored = GenericConstructorConfig.fromJson(json);
      expect(restored.toJson(), json);
      expect(restored.className, 'GlobalKey');
      expect(restored.kind, GenericConstructorKind.namedPassthrough);
      expect(restored.typeArgVariants, ['NavigatorState', 'FormState']);
      expect(restored.namedArgs.single.name, 'debugLabel');
      expect(restored.namedArgs.single.type, 'String');
    });

    test('G-GCC-DC-2: toJson omits defaulted fields', () {
      const minimal = GenericConstructorConfig(
        className: 'ValueKey',
        kind: GenericConstructorKind.nullableValue,
        typeArgVariants: ['String'],
      );
      final json = minimal.toJson();
      expect(json['kind'], 'nullableValue');
      expect(json.containsKey('namedArgs'), isFalse);
      expect(json.containsKey('includeDynamicArm'), isFalse);
      expect(json['typeArgVariants'], ['String']);
    });

    test('G-GCC-DC-3: fromYaml accepts a Map and rejects non-Map', () {
      final cfg = GenericConstructorConfig.fromYaml({
        'className': 'ValueKey',
        'kind': 'nullableValue',
        'typeArgVariants': ['String', 'int'],
      });
      expect(cfg.className, 'ValueKey');
      expect(cfg.kind, GenericConstructorKind.nullableValue);
      expect(cfg.typeArgVariants, ['String', 'int']);
      expect(() => GenericConstructorConfig.fromYaml('nope'),
          throwsArgumentError);
    });

    test('G-GCC-DC-4: kind defaults to nullableValue when absent', () {
      final cfg = GenericConstructorConfig.fromJson({
        'className': 'ValueKey',
        'typeArgVariants': ['String'],
      });
      expect(cfg.kind, GenericConstructorKind.nullableValue);
    });
  });

  group('BridgeConfig genericConstructors wiring (G-GCC-BC)', () {
    const globalKey = GenericConstructorConfig(
      className: 'GlobalKey',
      kind: GenericConstructorKind.namedPassthrough,
      typeArgVariants: ['NavigatorState', 'FormState'],
      namedArgs: [GenericCtorNamedArg(name: 'debugLabel', type: 'String')],
    );

    Map<String, dynamic> baseJson() => {
          'name': 'flutterm',
          'modules': <dynamic>[],
        };

    test('G-GCC-BC-1: defaults to an empty list', () {
      final config = BridgeConfig.fromJson(baseJson());
      expect(config.genericConstructors, isEmpty);
      // Dormant by default: toJson omits the key entirely.
      expect(config.toJson().containsKey('genericConstructors'), isFalse);
    });

    test('G-GCC-BC-2: fromJson parses declared generic constructors', () {
      final config = BridgeConfig.fromJson({
        ...baseJson(),
        'genericConstructors': [globalKey.toJson()],
      });
      expect(config.genericConstructors, hasLength(1));
      final gc = config.genericConstructors.single;
      expect(gc.className, 'GlobalKey');
      expect(gc.kind, GenericConstructorKind.namedPassthrough);
      expect(gc.typeArgVariants, ['NavigatorState', 'FormState']);
      expect(gc.namedArgs.single.name, 'debugLabel');
    });

    test('G-GCC-BC-3: round-trips through BridgeConfig.toJson/fromJson', () {
      final config = BridgeConfig.fromJson({
        ...baseJson(),
        'genericConstructors': [globalKey.toJson()],
      });
      final restored = BridgeConfig.fromJson(config.toJson());
      expect(restored.genericConstructors.single.toJson(), globalKey.toJson());
    });

    test('G-GCC-BC-4: copyWith replaces genericConstructors', () {
      final base = BridgeConfig.fromJson(baseJson());
      final updated = base.copyWith(genericConstructors: [globalKey]);
      expect(base.genericConstructors, isEmpty);
      expect(updated.genericConstructors, [globalKey]);
      // Omitting the argument preserves the existing list.
      expect(updated.copyWith().genericConstructors, [globalKey]);
    });
  });
}
