/// Tests for the RenderBox-proxy variant emitter
/// ([generateRenderBoxProxyVariant] / [generateRenderBoxProxyFamily]).
///
/// Interpreted `RenderBox` subclasses that declare a real Flutter container
/// mixin (`ContainerRenderObjectMixin` + `RenderBoxContainerDefaultsMixin`, or
/// `SlottedContainerRenderObjectMixin`) need a native proxy that *actually
/// mixes in* the corresponding mixin so the native plumbing runs. These were
/// previously hand-written as near-verbatim copies of the plain
/// `_InterpretedRenderBox` proxy, once in `tom_d4rt_flutter` and again in
/// `tom_d4rt_flutter_ast`. The emitter replaces them with one parameterized
/// template plus the runtime factory selector.
///
/// These tests pin: the canonical plain `_InterpretedRenderBox` byte-for-byte;
/// the per-variant `with` clause and the divergent `paint` /
/// `hitTestChildren` / `setupParentData` bodies; the slotted-only intrinsic
/// forwarders; the `_classChainHasBridgedMixin` selector; the variant-name
/// mapping; the family ordering + de-duplication; the selector being emitted
/// only when a non-plain variant exists; and the unknown-mixin warn-and-skip.
library;

import 'package:test/test.dart';
import 'package:tom_d4rt_generator/tom_d4rt_generator.dart';

/// The canonical plain-RenderBox proxy. The container/slotted variants are
/// this exact skeleton plus a `with` clause and divergent fallback bodies.
const _plainGolden = r'''/// A native [RenderBox] proxy backed by an interpreted D4rt
/// RenderBox subclass.
///
/// Generated by the d4rtgen proxy generator (RenderBox proxy variants).
/// The most common interpreted overrides are forwarded; anything
/// not overridden inherits the RenderBox (or mixin) default.
class _InterpretedRenderBox extends RenderBox
    implements D4InterpretedProxy {
  _InterpretedRenderBox(this._visitor, this._instance);

  final InterpreterVisitor _visitor;
  final InterpretedInstance _instance;

  static const Object _kNotImplemented = Object();

  @override
  Object get d4rtInstance => _instance;

  Object? _maybeInvoke(String methodName, List<Object?> args,
      [Map<String, Object?> named = const {}]) {
    final method = _instance.klass.findInstanceMethod(methodName);
    if (method == null) return _kNotImplemented;
    return method.bind(_instance).call(_visitor, args, named);
  }

  @override
  void performLayout() {
    final result = _maybeInvoke('performLayout', const []);
    if (identical(result, _kNotImplemented)) {
      size = constraints.smallest;
      return;
    }
    if (!hasSize) {
      try {
        final reflected = _instance.get('size', visitor: _visitor);
        if (reflected is Size) size = reflected;
      } catch (_) {}
    }
    if (!hasSize) size = constraints.smallest;
  }

  @override
  void paint(PaintingContext context, Offset offset) {
    final result = _maybeInvoke('paint', [context, offset]);
    if (identical(result, _kNotImplemented)) super.paint(context, offset);
  }

  @override
  bool hitTest(BoxHitTestResult result, {required Offset position}) {
    final method = _instance.klass.findInstanceMethod('hitTest');
    if (method == null) return super.hitTest(result, position: position);
    final raw = method
        .bind(_instance)
        .call(_visitor, [result], {'position': position});
    if (raw is bool) return raw;
    return false;
  }

  @override
  bool hitTestSelf(Offset position) {
    final method = _instance.klass.findInstanceMethod('hitTestSelf');
    if (method == null) return super.hitTestSelf(position);
    try {
      final raw = method.bind(_instance).call(_visitor, [position], const {});
      if (raw is bool) return raw;
    } catch (_) {}
    return false;
  }

  @override
  bool hitTestChildren(BoxHitTestResult result, {required Offset position}) {
    final method = _instance.klass.findInstanceMethod('hitTestChildren');
    if (method == null) {
      return super.hitTestChildren(result, position: position);
    }
    try {
      final raw = method
          .bind(_instance)
          .call(_visitor, [result], {'position': position});
      if (raw is bool) return raw;
    } catch (_) {}
    return false;
  }

  @override
  void setupParentData(RenderObject child) {
    final result = _maybeInvoke('setupParentData', [child]);
    if (identical(result, _kNotImplemented)) super.setupParentData(child);
  }
}
''';

void main() {
  group('generateRenderBoxProxyVariant', () {
    test('G-RBX-1: plain _InterpretedRenderBox matches the canonical golden byte-for-byte. [2026-06-07 00:00] (PASS)', () {
      final out = generateRenderBoxProxyVariant(RenderBoxProxyVariantSpec.plain);
      expect(out, equals(_plainGolden));
    });

    test('G-RBX-2: container variant mixes in the container mixins and uses the mixin defaults. [2026-06-07 00:00] (PASS)', () {
      final out =
          generateRenderBoxProxyVariant(RenderBoxProxyVariantSpec.container);
      expect(out, contains('class _InterpretedRenderBoxContainer extends RenderBox'));
      expect(
        out,
        contains(
          'ContainerRenderObjectMixin<RenderBox, ContainerBoxParentData<RenderBox>>,',
        ),
      );
      expect(out, contains('RenderBoxContainerDefaultsMixin<RenderBox,'));
      expect(out, contains('    implements D4InterpretedProxy {'));
      // Paint + hit-test fall back to the mixin defaults, not super.
      expect(out, contains('defaultPaint(context, offset);'));
      expect(out, contains('defaultHitTestChildren(result, position: position);'));
      // setupParentData takes a RenderObject child and defers to super.
      expect(out, contains('void setupParentData(RenderObject child) {'));
      expect(
        out,
        contains('if (identical(result, _kNotImplemented)) super.setupParentData(child);'),
      );
      // No slotted-only intrinsics.
      expect(out, isNot(contains('computeMinIntrinsicWidth')));
    });

    test('G-RBX-3: slotted variant mixes in the slot mixin and walks slot children. [2026-06-07 00:00] (PASS)', () {
      final out =
          generateRenderBoxProxyVariant(RenderBoxProxyVariantSpec.slotted);
      expect(out, contains('class _InterpretedSlottedRenderBox extends RenderBox'));
      expect(
        out,
        contains('with SlottedContainerRenderObjectMixin<dynamic, RenderBox>'),
      );
      // Paint walks the slot children.
      expect(out, contains('for (final child in children) {'));
      expect(out, contains('context.paintChild(child, childOffset);'));
      // Hit-test walks children in reverse paint order.
      expect(out, contains('for (final child in children.toList().reversed) {'));
      expect(out, contains('result.addWithPaintOffset('));
      // setupParentData takes a RenderBox child and assigns a BoxParentData.
      expect(out, contains('void setupParentData(RenderBox child) {'));
      expect(out, contains('child.parentData = BoxParentData();'));
    });

    test('G-RBX-4: slotted variant carries the four intrinsic-dimension forwarders. [2026-06-07 00:00] (PASS)', () {
      final out =
          generateRenderBoxProxyVariant(RenderBoxProxyVariantSpec.slotted);
      for (final dim in const [
        'computeMinIntrinsicWidth',
        'computeMaxIntrinsicWidth',
        'computeMinIntrinsicHeight',
        'computeMaxIntrinsicHeight',
      ]) {
        expect(out, contains('double $dim('),
            reason: 'missing intrinsic forwarder $dim');
      }
    });

    test('G-RBX-5: mixin-name mapping resolves the container and slotted variants. [2026-06-07 00:00] (PASS)', () {
      expect(
        renderBoxProxyVariantSpecFor('ContainerRenderObjectMixin')?.variant,
        RenderBoxProxyVariant.container,
      );
      expect(
        renderBoxProxyVariantSpecFor('RenderBoxContainerDefaultsMixin')?.variant,
        RenderBoxProxyVariant.container,
      );
      expect(
        renderBoxProxyVariantSpecFor('SlottedContainerRenderObjectMixin')?.variant,
        RenderBoxProxyVariant.slotted,
      );
      expect(renderBoxProxyVariantSpecFor('NotARealMixin'), isNull);
    });
  });

  group('generateRenderBoxProxyFamily', () {
    test('G-RBX-6: family emits the plain variant followed by each declared variant in order. [2026-06-07 00:00] (PASS)', () {
      const config = ProxyClassConfig(
        className: 'RenderBox',
        mixinVariants: [
          'ContainerRenderObjectMixin',
          'SlottedContainerRenderObjectMixin',
        ],
      );
      final out = generateRenderBoxProxyFamily(config);

      final order = [
        out.indexOf('class _InterpretedRenderBox extends'),
        out.indexOf('class _InterpretedRenderBoxContainer extends'),
        out.indexOf('class _InterpretedSlottedRenderBox extends'),
        out.indexOf('bool _classChainHasBridgedMixin('),
      ];
      expect(order, everyElement(greaterThanOrEqualTo(0)));
      for (var i = 1; i < order.length; i++) {
        expect(order[i], greaterThan(order[i - 1]));
      }
    });

    test('G-RBX-7: duplicate container-mapping mixin names emit the container variant once. [2026-06-07 00:00] (PASS)', () {
      const config = ProxyClassConfig(
        className: 'RenderBox',
        mixinVariants: [
          'ContainerRenderObjectMixin',
          'RenderBoxContainerDefaultsMixin',
        ],
      );
      final out = generateRenderBoxProxyFamily(config);
      expect(
        'class _InterpretedRenderBoxContainer'.allMatches(out).length,
        1,
      );
    });

    test('G-RBX-8: an empty mixinVariants list yields only the plain variant and no selector. [2026-06-07 00:00] (PASS)', () {
      const config = ProxyClassConfig(className: 'RenderBox');
      final out = generateRenderBoxProxyFamily(config);
      expect(out, equals(_plainGolden));
      expect(out, isNot(contains('_classChainHasBridgedMixin')));
    });

    test('G-RBX-9: the runtime selector is emitted only when a non-plain variant exists. [2026-06-07 00:00] (PASS)', () {
      const config = ProxyClassConfig(
        className: 'RenderBox',
        mixinVariants: ['SlottedContainerRenderObjectMixin'],
      );
      final out = generateRenderBoxProxyFamily(config);
      expect(out, contains('bool _classChainHasBridgedMixin('));
    });

    test('G-RBX-10: an unknown mixin name is reported via warn and skipped. [2026-06-07 00:00] (PASS)', () {
      const config = ProxyClassConfig(
        className: 'RenderBox',
        mixinVariants: ['ContainerRenderObjectMixin', 'BogusMixin'],
      );
      final warnings = <String>[];
      final out = generateRenderBoxProxyFamily(config, warn: warnings.add);

      expect(out, contains('class _InterpretedRenderBoxContainer'));
      expect(warnings, hasLength(1));
      expect(warnings.single, contains('BogusMixin'));
    });
  });
}
