// sce38: generation must name a package the pub cache cannot supply, rather
// than quietly emitting a bridge file with classes missing from it.
//
// `generateBridges` opens an analysis context over the package's resolved
// dependencies. A locked package whose cache directory is absent produces no
// resolution error — the lock is satisfiable, so `dart pub get` reports
// success — and the analyzer reports `Undefined name` at each use site
// instead. The generator swallows the resulting link failures and drops the
// affected classes, so the only visible symptom is a generated file that is
// short, with nothing anywhere mentioning the cache. That is the shape scd8
// was misread as an upstream rename, twice in one session.
//
// The fixture is built here rather than pointed at a real project so the test
// cannot be perturbed by the state of the developer's ~/.pub-cache: the lock
// names `zom_sce38_absent`, which is not a package that exists.
@Tags(['generation'])
library;

import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:test/test.dart';
import 'package:tom_d4rt_generator/tom_d4rt_generator.dart';
import 'package:tom_d4rt_generator/src/build_config_loader.dart';

/// A resolved project whose lock names [lockedPackages].
Directory fixture(Map<String, String> lockedPackages) {
  final dir = Directory.systemTemp.createTempSync('sce38_');
  File(p.join(dir.path, 'pubspec.yaml')).writeAsStringSync(
    'name: zom_sce38\nenvironment:\n  sdk: ">=3.0.0 <4.0.0"\n',
  );

  final lock = StringBuffer('# Generated by pub\npackages:\n');
  lockedPackages.forEach((name, version) {
    lock.write(
      '  $name:\n'
      '    dependency: "direct main"\n'
      '    description:\n'
      '      name: $name\n'
      '      sha256: "0000"\n'
      '      url: "https://pub.dev"\n'
      '    source: hosted\n'
      '    version: "$version"\n',
    );
  });
  lock.write('sdks:\n  dart: ">=3.0.0 <4.0.0"\n');
  File(p.join(dir.path, 'pubspec.lock')).writeAsStringSync(lock.toString());

  // Present, so the resolve step does not shell out to `dart pub get`.
  Directory(p.join(dir.path, '.dart_tool')).createSync(recursive: true);
  File(
    p.join(dir.path, '.dart_tool', 'package_config.json'),
  ).writeAsStringSync('{"configVersion":2,"packages":[]}');

  Directory(p.join(dir.path, 'lib')).createSync(recursive: true);
  File(
    p.join(dir.path, 'lib', 'zom_sce38.dart'),
  ).writeAsStringSync('class Thing {}\n');

  File(p.join(dir.path, 'buildkit.yaml')).writeAsStringSync('''
d4rtgen:
  name: zom_sce38
  modules:
    - name: all
      barrelFiles:
        - lib/zom_sce38.dart
      outputPath: lib/src/d4rt_bridges/zom_sce38_bridges.b.dart
''');
  return dir;
}

void main() {
  final temps = <Directory>[];

  Directory temp(Directory d) {
    temps.add(d);
    return d;
  }

  tearDownAll(() {
    for (final d in temps) {
      try {
        d.deleteSync(recursive: true);
      } catch (_) {}
    }
  });

  group('GEN-PCPF: pub-cache pre-flight', () {
    test('GEN-PCPF-1: generation stops and names the uncached package '
        '[2026-09-18] (PASS)', () async {
      final project = temp(fixture({'zom_sce38_absent': '9.9.9'}));
      final config = BuildConfigLoader.loadFromTomBuildYaml(project.path)!;

      final result = await generateBridges(
        config: config,
        projectPath: project.path,
        runPubGet: false,
      );

      expect(
        result.errors,
        isNotEmpty,
        reason:
            'silence here is the defect: the run would otherwise emit a '
            'bridge file with classes missing and no explanation',
      );
      final joined = result.errors.join('\n');
      expect(joined, contains('zom_sce38_absent'));
      expect(joined, contains('9.9.9'));
      expect(
        joined,
        contains('dart pub get'),
        reason: 'a report without the repair leaves the reader stuck',
      );
      expect(
        result.outputFiles,
        isEmpty,
        reason: 'nothing may be written from an unreadable dependency set',
      );
    });

    test(
      'GEN-PCPF-2: a project whose locked packages are all present generates '
      'normally [2026-09-18] (PASS)',
      () async {
        // The control. Without it, a pre-flight that refused every project
        // would pass GEN-PCPF-1 and look correct.
        final project = temp(fixture(const {}));
        final config = BuildConfigLoader.loadFromTomBuildYaml(project.path)!;

        final result = await generateBridges(
          config: config,
          projectPath: project.path,
          runPubGet: false,
        );

        expect(
          result.errors.where((e) => e.contains('pub cache')),
          isEmpty,
          reason: 'nothing is missing, so the pre-flight must not fire',
        );
      },
    );
  });
}
