// sce47: `@D4rtUserProxy` / `@D4rtUserRelaxer` now reach the generator.
//
// `UserProxyRelaxerScanner` was fully implemented and unit-tested but
// constructed NOWHERE under `lib/`, so the two annotations it exists to find
// changed no generated byte. Meanwhile user relaxers were in practice
// discovered by an entirely different, undocumented mechanism — the
// `user_relaxers/*_user_relaxer.dart` file convention. Two discovery designs,
// one wired and undocumented, one documented and unwired. The decision on the
// todo was (A): wire the annotations up, keeping the file convention as the
// fallback it already is.
//
// THE WIRING HAS TWO HALVES AND THEY ARE TESTED WHERE EACH CAN BE.
//
//   * DISCOVERY — `preScanUserVariantDirectives`, a folder pre-scan mirroring
//     `preScanUserBridges`. It needs a resolved analyzer context, so it is
//     exercised against a fixture project that sits INSIDE this package and
//     therefore resolves against this package's own config.
//   * CONVERSION — `userVariantExtractionSites`, which joins discovery to the
//     existing relaxer pipeline. Pure, so it needs no analyzer at all.
//
// WHY NOT ONE END-TO-END TEST THROUGH `bridge_api.generateBridges`: measured,
// a synthesised temp-directory package cannot resolve `package:` imports in an
// in-process analyzer context even with a copied package config — and the
// SHIPPED `preScanUserBridges` fails in exactly the same fixture, reporting
// "1 user-bridge file(s) found ... but no user bridges were registered". That
// is a property of the fixture, not of either scan, and writing an end-to-end
// test against it would have pinned the fixture's limitation as though it were
// the generator's behaviour.
@Tags(['generation'])
library;

import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:test/test.dart';
import 'package:tom_d4rt_generator/src/user_bridge_prescan.dart';
import 'package:tom_d4rt_generator/src/user_proxy_relaxer_scanner.dart';
import 'package:tom_d4rt_generator/src/user_variant_sites.dart';

String get _fixtureProject => p.join(
  Directory.current.path,
  'test',
  'fixtures',
  'sce47_directive_project',
);

void main() {
  group('SCE47: the folder pre-scan discovers directives', () {
    late UserProxyRelaxerScanner scanner;
    late List<String> warnings;

    setUpAll(() async {
      warnings = [];
      scanner = await preScanUserVariantDirectives(
        _fixtureProject,
        onWarning: warnings.add,
      );
    });

    test('G-SCE47-1: the directive is found [2026-09-18] (PASS)', () async {
      expect(
        scanner.relaxerDirectives,
        hasLength(1),
        reason:
            'this is the whole defect: before sce47 nothing under lib/ ever '
            'constructed this scanner, so a directive here reached no '
            'generation path at all. Warnings: $warnings',
      );
      final directive = scanner.relaxerDirectives.single;
      expect(directive.kind, UserVariantKind.relaxer);
      expect(directive.baseClass, 'ZomBox');
      expect(directive.directiveClassName, 'ZomBoxUserRelaxer');
    });

    test('G-SCE47-2: the marker actually resolved [2026-09-18] (PASS)', () {
      // Anti-vacuity, and it is not theoretical. When `D4UserRelaxer` does not
      // resolve, the analyzer reports the supertype as `Object`, the scanner
      // skips the class in silence, and G-SCE47-1 fails with an empty list
      // that looks exactly like "the wiring is not called". This asserts the
      // fixture resolves, so a failure above means the WIRING is wrong rather
      // than the fixture.
      expect(
        scanner.directiveClassNames,
        contains('ZomBoxUserRelaxer'),
        reason:
            'the class is recorded as a directive only once its supertype has '
            'been resolved to the marker base',
      );
      expect(
        warnings,
        isEmpty,
        reason: 'a resolving fixture produces no scanner warnings',
      );
    });

    test('G-SCE47-3: a directory with no directives yields an empty scanner '
        '[2026-09-18] (PASS)', () async {
      // The other direction: the scan must not invent directives, and must
      // tolerate a project that has no directive folder at all — which is
      // every package in this workspace today.
      final empty = await preScanUserVariantDirectives(
        Directory.systemTemp.createTempSync('sce47_empty_').path,
      );
      expect(empty.relaxerDirectives, isEmpty);
      expect(empty.proxyDirectives, isEmpty);
    });
  });

  group('SCE47: directives become generic extraction sites', () {
    /// Builds a directive without an analyzer — the module's core is
    /// deliberately analyzer-free.
    UserVariantDirective directive(List<String> variants) =>
        UserVariantDirective.parse(
          kind: UserVariantKind.relaxer,
          libraryPath: 'package:zom_sce47/boxes.dart',
          baseClass: 'ZomBox',
          variants: variants,
          directiveClassName: 'ZomBoxUserRelaxer',
          sourceFile: 'zom_box_directive.dart',
        );

    test('G-SCE47-4: one site per declared variant [2026-09-18] (PASS)', () {
      final sites = userVariantExtractionSites([
        directive(['ZomCustomer', 'ZomOrder']),
      ], const []);

      expect(sites, hasLength(2));
      expect(sites.map((s) => s.baseTypeName).toSet(), {'ZomBox'});
      expect(sites.map((s) => s.typeArg), ['ZomCustomer', 'ZomOrder']);
      expect(
        sites.map((s) => s.moduleName).toSet(),
        {userDirectiveModuleName},
        reason:
            'a site that came from a declaration rather than a usage is '
            'labelled as such, so the generator diagnostics can tell them '
            'apart',
      );
    });

    test('G-SCE47-5: explicit variants need no candidate pool '
        '[2026-09-18] (PASS)', () {
      // The pool is what a WILDCARD expands against. Requiring it for explicit
      // variants would make a directive silently produce nothing in a package
      // whose class lookup happens to be empty.
      expect(
        userVariantExtractionSites([
          directive(['ZomCustomer']),
        ], const []),
        hasLength(1),
      );
    });

    test(
      'G-SCE47-6: a wildcard expands against the pool [2026-09-18] (PASS)',
      () {
        final sites = userVariantExtractionSites(
          [
            directive([r'*Customer']),
          ],
          const ['ZomCustomer', 'ZomOrder', 'OtherCustomer'],
        );

        expect(
          sites.map((s) => s.typeArg).toSet(),
          {'ZomCustomer', 'OtherCustomer'},
          reason: 'the pattern selects from the pool; ZomOrder does not match',
        );
      },
    );

    test('G-SCE47-7: no directives yields no sites [2026-09-18] (PASS)', () {
      // Anti-vacuity for the live call site: every package in the workspace
      // has no directives today, so this is the path that must add nothing.
      expect(
        userVariantExtractionSites(const [], const ['ZomCustomer']),
        isEmpty,
      );
    });
  });
}
