/// Tests for the MCI#3 / A3 State-proxy variant emitter
/// ([generateStateProxyVariant] / [generateStateProxyFamily]).
///
/// Interpreted `State` subclasses that declare a real Flutter mixin
/// (`SingleTickerProviderStateMixin`, `TickerProviderStateMixin`,
/// `RestorationMixin`, `AutomaticKeepAliveClientMixin`) need a native proxy
/// that *actually mixes in* the corresponding mixin so the mixin's native
/// overrides run. These were previously hand-written as near-verbatim copies
/// (and the web twin had drifted, missing the keep-alive variant). The
/// emitter replaces them with one parameterized template.
///
/// These tests pin: the canonical plain `_InterpretedState` byte-for-byte;
/// the `with` mixin clause per variant; the Bug-46 re-entrancy guard on every
/// lifecycle override; the RestorationMixin extra-override slot
/// (`restorationId` + `restoreState`); the KeepAlive slot (`wantKeepAlive` +
/// the `super.build(context)` prefix); the family ordering; and the
/// unknown-mixin warn-and-skip bail.
library;

import 'package:test/test.dart';
import 'package:tom_d4rt_generator/tom_d4rt_generator.dart';

/// The canonical plain-State proxy. The mixin variants are this exact shape
/// plus a `with` clause and a per-mixin extra-override slot.
const _plainGolden = r'''/// A native [State] proxy that delegates lifecycle methods to an
/// interpreted D4rt State subclass.
///
/// Generated by the d4rtgen proxy generator (MCI#3 mixinVariants).
/// Each lifecycle override is wrapped in a Bug-46 re-entrancy guard
/// so a script body that calls `super.initState()` (etc.) does not
/// recurse back into the proxy indefinitely.
class _InterpretedState extends State<_InterpretedStatefulWidget>
    implements D4InterpretedProxy {
  final InterpreterVisitor _visitor;
  final InterpretedInstance _stateInstance;

  _InterpretedState(this._visitor, this._stateInstance);

  @override
  Object get d4rtInstance => _stateInstance;

  @override
  void initState() {
    if (_lifecycleInProgress.contains('initState')) return;
    _lifecycleInProgress.add('initState');
    try {
      super.initState();
      _callVoidMethod('initState');
    } finally {
      _lifecycleInProgress.remove('initState');
    }
  }

  @override
  void didChangeDependencies() {
    if (_lifecycleInProgress.contains('didChangeDependencies')) return;
    _lifecycleInProgress.add('didChangeDependencies');
    try {
      super.didChangeDependencies();
      _callVoidMethod('didChangeDependencies');
    } finally {
      _lifecycleInProgress.remove('didChangeDependencies');
    }
  }

  @override
  Widget build(BuildContext context) {
    final method = _stateInstance.klass.findInstanceMethod('build');
    if (method != null) {
      final bound = method.bind(_stateInstance);
      final result = bound.call(_visitor, [context], {});
      return D4.extractBridgedArg<Widget>(result, 'build', _visitor);
    }
    throw StateError(
      'Interpreted State ${_stateInstance.klass.name} does not implement build()',
    );
  }

  @override
  void didUpdateWidget(covariant _InterpretedStatefulWidget oldWidget) {
    if (_lifecycleInProgress.contains('didUpdateWidget')) return;
    _lifecycleInProgress.add('didUpdateWidget');
    try {
      super.didUpdateWidget(oldWidget);
      _stateInstance.interpretedStatefulWidget = widget._instance;
      final didUpdateMethod =
          _stateInstance.klass.findInstanceMethod('didUpdateWidget');
      if (didUpdateMethod != null) {
        try {
          didUpdateMethod
              .bind(_stateInstance)
              .call(_visitor, <Object?>[oldWidget._instance], {});
        } catch (_) {
          // Lifecycle methods may call super which isn't available in proxy.
        }
      }
    } finally {
      _lifecycleInProgress.remove('didUpdateWidget');
    }
  }

  @override
  void deactivate() {
    if (_lifecycleInProgress.contains('deactivate')) return;
    _lifecycleInProgress.add('deactivate');
    try {
      _callVoidMethod('deactivate');
      super.deactivate();
    } finally {
      _lifecycleInProgress.remove('deactivate');
    }
  }

  @override
  void dispose() {
    if (_lifecycleInProgress.contains('dispose')) return;
    _lifecycleInProgress.add('dispose');
    try {
      _callVoidMethod('dispose');
      super.dispose();
    } finally {
      _lifecycleInProgress.remove('dispose');
    }
  }

  void _callVoidMethod(String name) {
    final method = _stateInstance.klass.findInstanceMethod(name);
    if (method != null) {
      try {
        method.bind(_stateInstance).call(_visitor, [], {});
      } catch (_) {
        // Lifecycle methods may call super which isn't available in proxy.
      }
    }
  }

  final Set<String> _lifecycleInProgress = <String>{};
}
''';

/// Every guarded lifecycle override for [member] must enter, add, and remove
/// the [member] key from `_lifecycleInProgress` exactly so a re-entrant
/// `super.<member>()` short-circuits.
Matcher _hasBug46Guard(String member) => allOf(
      contains("if (_lifecycleInProgress.contains('$member')) return;"),
      contains("_lifecycleInProgress.add('$member');"),
      contains("_lifecycleInProgress.remove('$member');"),
    );

void main() {
  group('generateStateProxyVariant (MCI#3)', () {
    test('G-SPX-1: plain _InterpretedState matches the canonical golden byte-for-byte. [2026-06-07 00:00] (PASS)', () {
      final out = generateStateProxyVariant(StateProxyVariantSpec.plain);
      expect(out, equals(_plainGolden));
    });

    test('G-SPX-2: every lifecycle override carries the Bug-46 re-entrancy guard. [2026-06-07 00:00] (PASS)', () {
      final out = generateStateProxyVariant(StateProxyVariantSpec.plain);
      for (final member in const [
        'initState',
        'didChangeDependencies',
        'didUpdateWidget',
        'deactivate',
        'dispose',
      ]) {
        expect(out, _hasBug46Guard(member), reason: 'missing guard for $member');
      }
    });

    test('G-SPX-3: SingleTickerProviderStateMixin variant emits the mixin clause. [2026-06-07 00:00] (PASS)', () {
      final spec = stateProxyVariantSpecFor('SingleTickerProviderStateMixin')!;
      final out = generateStateProxyVariant(spec);
      expect(out, contains('class _InterpretedSingleTickerProviderState'));
      expect(out, contains('    extends State<_InterpretedStatefulWidget>'));
      expect(out, contains('    with SingleTickerProviderStateMixin'));
      expect(out, contains('    implements D4InterpretedProxy {'));
      // No extra-override slot for a plain ticker mixin.
      expect(out, isNot(contains('get restorationId')));
      expect(out, isNot(contains('get wantKeepAlive')));
    });

    test('G-SPX-4: TickerProviderStateMixin maps to the multi-ticker variant. [2026-06-07 00:00] (PASS)', () {
      final spec = stateProxyVariantSpecFor('TickerProviderStateMixin')!;
      final out = generateStateProxyVariant(spec);
      expect(out, contains('class _InterpretedMultiTickerProviderState'));
      expect(out, contains('    with TickerProviderStateMixin'));
    });

    test('G-SPX-5: RestorationMixin variant emits the restorationId + restoreState slot. [2026-06-07 00:00] (PASS)', () {
      final spec = stateProxyVariantSpecFor('RestorationMixin')!;
      final out = generateStateProxyVariant(spec);
      expect(out, contains('class _InterpretedRestorationMixinState'));
      expect(
        out,
        contains('    with RestorationMixin<_InterpretedStatefulWidget>'),
      );
      expect(out, contains('  String? get restorationId {'));
      expect(
        out,
        contains(
          '  void restoreState(RestorationBucket? oldBucket, bool initialRestore) {',
        ),
      );
      // restoreState is itself re-entrancy guarded.
      expect(out, _hasBug46Guard('restoreState'));
    });

    test('G-SPX-6: AutomaticKeepAliveClientMixin variant emits wantKeepAlive + super.build prefix. [2026-06-07 00:00] (PASS)', () {
      final spec = stateProxyVariantSpecFor('AutomaticKeepAliveClientMixin')!;
      final out = generateStateProxyVariant(spec);
      expect(out, contains('class _InterpretedKeepAliveState'));
      expect(out, contains('    with AutomaticKeepAliveClientMixin'));
      // wantKeepAlive is declared without @override (mixin abstract getter).
      expect(out, contains('  bool get wantKeepAlive {'));
      expect(out, isNot(contains('  @override\n  bool get wantKeepAlive')));
      // build() must call super.build(context) first so the mixin can
      // dispatch its KeepAliveNotification before the script build runs.
      expect(
        out,
        contains(
          '  Widget build(BuildContext context) {\n'
          '    super.build(context);\n',
        ),
      );
    });

    test('G-SPX-7: unknown mixin names return null from the spec lookup. [2026-06-07 00:00] (PASS)', () {
      expect(stateProxyVariantSpecFor('NotARealMixin'), isNull);
    });
  });

  group('generateStateProxyFamily (MCI#3)', () {
    test('G-SPX-8: family emits the plain variant followed by each declared variant in order. [2026-06-07 00:00] (PASS)', () {
      const config = ProxyClassConfig(
        className: 'State',
        mixinVariants: [
          'SingleTickerProviderStateMixin',
          'TickerProviderStateMixin',
          'RestorationMixin',
          'AutomaticKeepAliveClientMixin',
        ],
      );
      final out = generateStateProxyFamily(config);

      final order = [
        out.indexOf('class _InterpretedState extends'),
        out.indexOf('class _InterpretedSingleTickerProviderState'),
        out.indexOf('class _InterpretedMultiTickerProviderState'),
        out.indexOf('class _InterpretedRestorationMixinState'),
        out.indexOf('class _InterpretedKeepAliveState'),
      ];
      // All present.
      expect(order, everyElement(greaterThanOrEqualTo(0)));
      // Strictly increasing — declaration order preserved.
      for (var i = 1; i < order.length; i++) {
        expect(order[i], greaterThan(order[i - 1]));
      }
    });

    test('G-SPX-9: an empty mixinVariants list yields only the plain variant. [2026-06-07 00:00] (PASS)', () {
      const config = ProxyClassConfig(className: 'State');
      final out = generateStateProxyFamily(config);
      expect(out, equals(_plainGolden));
    });

    test('G-SPX-10: an unknown mixin name is reported via warn and skipped. [2026-06-07 00:00] (PASS)', () {
      const config = ProxyClassConfig(
        className: 'State',
        mixinVariants: ['SingleTickerProviderStateMixin', 'BogusMixin'],
      );
      final warnings = <String>[];
      final out = generateStateProxyFamily(config, warn: warnings.add);

      expect(out, contains('class _InterpretedSingleTickerProviderState'));
      expect(warnings, hasLength(1));
      expect(warnings.single, contains('BogusMixin'));
    });
  });
}
