/// Tests for the generic-type-arg proxy-variant emitter (`typeArgVariants`)
/// ([generateTypeArgProxyVariant] / [generateTypeArgProxyClasses] /
/// [generateTypeArgProxySelector]).
///
/// An invariant generic delegate (`CustomClipper<T>`) cannot be backed by a
/// single `<Path>` proxy — Flutter's downstream `getClip(size) as RRect` cast
/// fails. So one typed proxy per concrete type argument is generated, each
/// returning a non-null fallback of its own `T`, plus a selector switch that
/// picks the variant matching the script's reified bridged-super type argument.
/// These were previously four hand-written near-verbatim classes per twin.
///
/// These tests pin: the canonical `_InterpretedCustomClipperPath` variant
/// byte-for-byte; the per-variant type arg + `defaultExpr` substitution; the
/// declaration-order family; the selector switch (first entry = default arm,
/// the rest = `case` arms in order); the dormant empty default; and the
/// config round-trip + validation of `typeArgVariants`.
library;

import 'package:test/test.dart';
import 'package:tom_d4rt_generator/tom_d4rt_generator.dart';

/// The canonical `CustomClipper<Path>` variant. Every other variant is this
/// exact shape with `Path` → `<typeArg>` and `Path()` → `<defaultExpr>`.
const _pathGolden = r'''/// Native [CustomClipper<Path>] backing an interpreted subclass
/// declared as `extends CustomClipper<Path>`.
///
/// Generated by the d4rtgen proxy generator (typeArgVariants).
class _InterpretedCustomClipperPath extends CustomClipper<Path> {
  _InterpretedCustomClipperPath(this._visitor, this._instance);

  final InterpreterVisitor _visitor;
  final InterpretedInstance _instance;

  @override
  Path getClip(Size size) {
    final method = _instance.klass.findInstanceMethod('getClip');
    if (method == null) return Path();
    try {
      final raw = method.bind(_instance).call(_visitor, [size], {});
      if (raw is Path) return raw;
    } catch (_) {}
    return Path();
  }

  @override
  bool shouldReclip(covariant CustomClipper<Path> oldClipper) {
    final method = _instance.klass.findInstanceMethod('shouldReclip');
    if (method == null) return false;
    try {
      final raw = method.bind(_instance).call(_visitor, [oldClipper], {});
      if (raw is bool) return raw;
    } catch (_) {}
    return false;
  }
}
''';

/// The canonical selector switch for the four-variant CustomClipper family.
/// `Path` (first listed) is the default arm; the other three are `case` arms
/// in declaration order.
const _selectorGolden = r'''  // Pick the typed CustomClipper proxy variant that matches
  // the script's reified bridged-super type argument so Flutter's
  // downstream invariant-generic cast succeeds. Generated by the
  // d4rtgen proxy generator (typeArgVariants).
  D4.registerInterfaceProxy('CustomClipper', (visitor, instance) {
    final typeArgNames = instance.klass.bridgedSuperTypeArgNames;
    final firstArg = (typeArgNames != null && typeArgNames.isNotEmpty)
        ? typeArgNames[0]
        : '';
    final Object proxy;
    switch (firstArg) {
      case 'Rect':
        proxy = _InterpretedCustomClipperRect(visitor, instance);
        break;
      case 'RRect':
        proxy = _InterpretedCustomClipperRRect(visitor, instance);
        break;
      case 'RSuperellipse':
        proxy = _InterpretedCustomClipperRSuperellipse(visitor, instance);
        break;
      default:
        proxy = _InterpretedCustomClipperPath(visitor, instance);
        break;
    }
    instance.nativeProxy ??= proxy;
    return proxy;
  });
''';

/// The full CustomClipper family config, mirroring the hand-written variants.
const _clipperConfig = ProxyClassConfig(
  className: 'CustomClipper',
  typeArgVariants: [
    TypeArgProxyVariant(typeArg: 'Path', defaultExpr: 'Path()'),
    TypeArgProxyVariant(typeArg: 'Rect', defaultExpr: 'Offset.zero & size'),
    TypeArgProxyVariant(
      typeArg: 'RRect',
      defaultExpr: 'RRect.fromRectAndCorners(Offset.zero & size)',
    ),
    TypeArgProxyVariant(
      typeArg: 'RSuperellipse',
      defaultExpr:
          'RSuperellipse.fromRectAndRadius(Offset.zero & size, Radius.zero)',
    ),
  ],
);

void main() {
  group('generateTypeArgProxyVariant', () {
    test('G-TAV-1: Path variant matches the canonical golden byte-for-byte. [2026-06-07 00:00] (PASS)', () {
      final out = generateTypeArgProxyVariant(
        'CustomClipper',
        _clipperConfig.typeArgVariants.first,
      );
      expect(out, equals(_pathGolden));
    });

    test('G-TAV-2: type arg + defaultExpr substitute into both the null-method and trailing return. [2026-06-07 00:00] (PASS)', () {
      final out = generateTypeArgProxyVariant(
        'CustomClipper',
        _clipperConfig.typeArgVariants[2], // RRect
      );
      expect(out, contains('class _InterpretedCustomClipperRRect extends CustomClipper<RRect> {'));
      expect(out, contains('  RRect getClip(Size size) {'));
      // defaultExpr appears twice: the null-method early return and the
      // catch/non-match fallthrough.
      expect(
        'RRect.fromRectAndCorners(Offset.zero & size)'.allMatches(out).length,
        equals(2),
      );
      expect(out, contains('    if (method == null) return RRect.fromRectAndCorners(Offset.zero & size);'));
      expect(out, contains('      if (raw is RRect) return raw;'));
      expect(out, contains('  bool shouldReclip(covariant CustomClipper<RRect> oldClipper) {'));
    });
  });

  group('generateTypeArgProxyClasses', () {
    test('G-TAV-3: family emits one class per variant in declaration order. [2026-06-07 00:00] (PASS)', () {
      final out = generateTypeArgProxyClasses(_clipperConfig);
      final order = [
        out.indexOf('class _InterpretedCustomClipperPath extends'),
        out.indexOf('class _InterpretedCustomClipperRect extends'),
        out.indexOf('class _InterpretedCustomClipperRRect extends'),
        out.indexOf('class _InterpretedCustomClipperRSuperellipse extends'),
      ];
      expect(order, everyElement(greaterThanOrEqualTo(0)));
      for (var i = 1; i < order.length; i++) {
        expect(order[i], greaterThan(order[i - 1]),
            reason: 'declaration order not preserved');
      }
      // The first class is the canonical Path golden verbatim.
      expect(out, startsWith(_pathGolden));
    });

    test('G-TAV-4: an empty typeArgVariants list yields the empty string. [2026-06-07 00:00] (PASS)', () {
      const config = ProxyClassConfig(className: 'CustomClipper');
      expect(generateTypeArgProxyClasses(config), isEmpty);
      expect(generateTypeArgProxySelector(config), isEmpty);
      expect(generateTypeArgProxyFamily(config), isEmpty);
    });
  });

  group('generateTypeArgProxySelector', () {
    test('G-TAV-5: selector matches the canonical golden byte-for-byte. [2026-06-07 00:00] (PASS)', () {
      final out = generateTypeArgProxySelector(_clipperConfig);
      expect(out, equals(_selectorGolden));
    });

    test('G-TAV-6: first variant is the default arm; the rest are case arms in order. [2026-06-07 00:00] (PASS)', () {
      const config = ProxyClassConfig(
        className: 'CustomClipper',
        typeArgVariants: [
          TypeArgProxyVariant(typeArg: 'Rect', defaultExpr: 'Offset.zero & size'),
          TypeArgProxyVariant(typeArg: 'Path', defaultExpr: 'Path()'),
        ],
      );
      final out = generateTypeArgProxySelector(config);
      // Rect is now the default arm (first listed); Path is the only case arm.
      expect(out, contains("      case 'Path':"));
      expect(out, isNot(contains("      case 'Rect':")));
      expect(
        out,
        contains('      default:\n'
            '        proxy = _InterpretedCustomClipperRect(visitor, instance);'),
      );
    });
  });

  group('TypeArgProxyVariant config round-trip', () {
    test('G-TAV-7: typeArgVariants survive a ProxyClassConfig JSON round-trip. [2026-06-07 00:00] (PASS)', () {
      final json = _clipperConfig.toJson();
      final restored = ProxyClassConfig.fromJson(json);
      expect(restored.typeArgVariants, hasLength(4));
      expect(restored.typeArgVariants[2].typeArg, equals('RRect'));
      expect(
        restored.typeArgVariants[2].defaultExpr,
        equals('RRect.fromRectAndCorners(Offset.zero & size)'),
      );
      // Re-emitting from the restored config is identical.
      expect(
        generateTypeArgProxySelector(restored),
        equals(generateTypeArgProxySelector(_clipperConfig)),
      );
    });

    test('G-TAV-8: a variant missing typeArg or defaultExpr is rejected. [2026-06-07 00:00] (PASS)', () {
      expect(
        () => TypeArgProxyVariant.fromYaml({'typeArg': 'Path'}),
        throwsArgumentError,
      );
      expect(
        () => TypeArgProxyVariant.fromYaml('Path'),
        throwsArgumentError,
      );
    });
  });
}
