// Turn the pre-publish path-resolved pass on and off (SCD66).
//
// WHY THIS EXISTS. Both Flutter twins and `tom_d4rt_exec` resolve their
// interpreter from pub.dev, deliberately, so that what they measure is what a
// consumer of the published package gets (DGUC6). The cost is that the
// quest's largest test asset — the bridge corpus — cannot see an interpreter
// change until it has been published, and a publish is irreversible. The
// quest's own protocol makes that concrete: a name-resolution change must get
// a corpus run, AFTER publishing. tcca19 is the precedent it was written for,
// a registry change that broke 17 base-corpus scripts with every unit test
// green. Found after the release rather than before it.
//
// SCD66's decision: hosted stays the DEFAULT and the only configuration whose
// results may be recorded as a verification run; this script adds an opt-in
// pre-publish pass that path-resolves the interpreter so the corpus can be
// run against the working tree BEFORE the publish that makes it permanent.
//
// WHAT IT IS NOT. This is not a way to make a downstream package work against
// an unpublished API — the workspace rule against path overrides is about
// exactly that, and it stands. Nothing here is committed (the override files
// are gitignored, and `scd66_resolution_strategy_test.dart` fails if one is
// tracked or if a `dependency_overrides:` block appears in a pubspec), nothing
// is published from this state, and results measured in it must not be written
// into `## Verification runs` — the record is a record of published pairs.
//
// USAGE, from the `tom_d4rt_flutter_ast` package root:
//
//   dart run tool/prepublish_overrides.dart            # status (default)
//   dart run tool/prepublish_overrides.dart --set      # path-resolve, pub get
//   dart run tool/prepublish_overrides.dart --restore  # remove, pub get
//   dart run tool/prepublish_overrides.dart --pass     # set, gate, restore
//
// `--pass` is the one a publish runs: it sets the overrides, runs analyze in
// both twins and exec plus exec's own suite, and restores hosted resolution
// whatever the outcome. See [_gates] for what it does and does not cover.
//
// `--set` and `--restore` both re-resolve every target, because a twin and its
// companion app have separate lockfiles and upgrading one without the other is
// a near-miss this corpus has already had (see `## Verification runs`,
// 2026-09-06, and SCD65-4).

import 'dart:io';

/// One package whose resolution the pass flips, and the interpreter packages
/// it should point at the working tree.
typedef Target = ({String dir, bool isFlutter, Map<String, String> overrides});

/// Every package the corpus and the exec suite actually resolve through.
///
/// The companion apps are separate packages with their own lockfiles, and they
/// are the ones the corpus scripts execute in — overriding only the twins
/// would leave the run measuring the published interpreter while the twin's own
/// `flutter test` measured the tree.
const targets = <Target>[
  (dir: '.', isFlutter: true, overrides: {'tom_d4rt_ast': '../tom_d4rt_ast'}),
  (
    dir: 'test/tom_d4rt_flutter_ast_app',
    isFlutter: true,
    overrides: {'tom_d4rt_ast': '../../../tom_d4rt_ast'},
  ),
  (
    dir: '../tom_d4rt_flutter',
    isFlutter: true,
    overrides: {'tom_d4rt': '../tom_d4rt'},
  ),
  (
    dir: '../tom_d4rt_flutter/test/tom_d4rt_flutter_test_app',
    isFlutter: true,
    overrides: {'tom_d4rt': '../../../tom_d4rt'},
  ),
  // `tom_d4rt_exec` is in scope for the same reason and by the same mechanism,
  // though its gate is `dart test` rather than the corpus. `tom_ast_generator`
  // rides along because exec's front end is the pair, not the interpreter
  // alone: a parse-side change is as invisible to exec's suite as an
  // interpreter one.
  (
    dir: '../tom_d4rt_exec',
    isFlutter: false,
    overrides: {
      'tom_d4rt_ast': '../tom_d4rt_ast',
      'tom_ast_generator': '../tom_ast_generator',
    },
  ),
];

const _overrideFile = 'pubspec_overrides.yaml';

const _banner = '''
# GENERATED by tool/prepublish_overrides.dart (SCD66) — do not commit.
#
# This package is path-resolved against the WORKING TREE, so anything measured
# here is measuring unpublished code. Results from this state must not be
# recorded under `## Verification runs` in
# tom_d4rt_flutter_ast/doc/interpreter_issues.md, which records published
# pairs. Remove with `dart run tool/prepublish_overrides.dart --restore`.
''';

File _overrideOf(Target t) => File('${t.dir}/$_overrideFile');

Future<bool> _pubGet(Target t) async {
  final exe = t.isFlutter ? 'flutter' : 'dart';
  stdout.write('  $exe pub get in ${t.dir} … ');
  final result = await Process.run(exe, [
    'pub',
    'get',
  ], workingDirectory: t.dir);
  if (result.exitCode != 0) {
    stdout.writeln('FAILED');
    stdout.writeln(result.stdout);
    stdout.writeln(result.stderr);
    return false;
  }
  stdout.writeln('ok');
  return true;
}

/// The resolved version and source of [package] in [dir]'s lockfile.
({String version, String source})? _resolved(String dir, String package) {
  final file = File('$dir/pubspec.lock');
  if (!file.existsSync()) return null;
  final lines = file.readAsLinesSync();
  for (var i = 0; i < lines.length; i++) {
    if (lines[i].trimRight() != '  $package:') continue;
    String? version;
    String? source;
    for (var j = i + 1; j < lines.length && lines[j].startsWith('    '); j++) {
      version ??= RegExp(
        r'^\s+version: "([^"]+)"',
      ).firstMatch(lines[j])?.group(1);
      source ??= RegExp(r'^\s+source: (\S+)').firstMatch(lines[j])?.group(1);
    }
    if (version != null && source != null) {
      return (version: version, source: source);
    }
  }
  return null;
}

void _printStatus() {
  stdout.writeln('Resolution of every target:\n');
  var anyPath = false;
  for (final t in targets) {
    final marker = _overrideOf(t).existsSync() ? 'override present' : '—';
    for (final package in t.overrides.keys) {
      final r = _resolved(t.dir, package);
      final where = r == null ? 'unresolved' : '${r.version} (${r.source})';
      if (r?.source == 'path') anyPath = true;
      stdout.writeln('  ${t.dir.padRight(46)} $package → $where  [$marker]');
    }
  }
  stdout.writeln(
    anyPath
        ? '\nPRE-PUBLISH MODE. At least one target resolves the working tree, '
              'so nothing measured here describes a published interpreter.\n'
              'Restore with --restore before recording any run.'
        : '\nHosted — the normal, recordable configuration.',
  );
}

/// The gates `--pass` runs, in order, while the targets are path-resolved.
///
/// SCE108 made the pass a STEP OF THE PUBLISH rather than a tool somebody
/// remembers. SCD66 built the mechanism and proved it pays — its first run
/// found two exec tests the next `tom_d4rt_ast` publish would have broken
/// (SCE107) — but it left `--set` / `--restore` as two commands with the work
/// in between, which is the same shape as the `_bin/check_*.py` scripts the
/// workspace describes as "scripts somebody has to remember to run". The
/// answer there was to move the check into the toolchain; this is that move.
///
/// WHAT IS AND IS NOT HERE. Analyze catches an API break that would stop a
/// consumer compiling, which is the most embarrassing class of bad release.
/// exec's suite catches behavioural drift neither interpreter tree can see,
/// because exec carries stdlib and conformance suites they do not — it is what
/// found SCE107. The base CORPUS is deliberately absent: it costs about an hour
/// per twin, the twins must not run in parallel, and it earns that only for a
/// NAME-RESOLUTION change, which the quest already singles out. `--pass` says
/// so on the way out rather than silently deciding for you.
const _gates = <({String label, String dir, String exe, List<String> args})>[
  (
    label: 'analyze: tom_d4rt_flutter_ast',
    dir: '.',
    exe: 'flutter',
    args: ['analyze', '--no-pub'],
  ),
  (
    label: 'analyze: tom_d4rt_flutter',
    dir: '../tom_d4rt_flutter',
    exe: 'flutter',
    args: ['analyze', '--no-pub'],
  ),
  (
    label: 'analyze: tom_d4rt_exec',
    dir: '../tom_d4rt_exec',
    exe: 'dart',
    args: ['analyze'],
  ),
  (
    label: 'test: tom_d4rt_exec',
    dir: '../tom_d4rt_exec',
    exe: 'dart',
    args: ['test', '-j', '4'],
  ),
];

/// Runs [_gates], returning the labels that failed.
///
/// Streams nothing: a gate's output is printed only when it FAILS, because the
/// useful form of this command's output is a short verdict, and burying it
/// under four analyzer runs is how a gate stops being read.
Future<List<String>> _runGates() async {
  final failed = <String>[];
  for (final gate in _gates) {
    stdout.write('  ${gate.label} … ');
    final result = await Process.run(
      gate.exe,
      gate.args,
      workingDirectory: gate.dir,
    );
    if (result.exitCode == 0) {
      stdout.writeln('ok');
    } else {
      stdout.writeln('FAILED');
      failed.add(gate.label);
      stdout.writeln(result.stdout);
      stdout.writeln(result.stderr);
    }
  }
  return failed;
}

Future<int> main(List<String> args) async {
  if (!File('pubspec.yaml').existsSync() ||
      !Directory('test/tom_d4rt_flutter_ast_app').existsSync()) {
    stderr.writeln(
      'Run this from the tom_d4rt_flutter_ast package root — the target paths '
      'are relative to it.',
    );
    return 2;
  }

  final pass = args.contains('--pass');
  final set = args.contains('--set') || pass;
  final restore = args.contains('--restore') && !pass;
  if (args.contains('--set') && args.contains('--restore')) {
    stderr.writeln('--set and --restore are mutually exclusive.');
    return 2;
  }
  if (!set && !restore) {
    _printStatus();
    return 0;
  }

  for (final t in targets) {
    final file = _overrideOf(t);
    if (set) {
      final buffer = StringBuffer(_banner)..writeln('dependency_overrides:');
      t.overrides.forEach((package, path) {
        buffer.writeln('  $package:');
        buffer.writeln('    path: $path');
      });
      file.writeAsStringSync(buffer.toString());
      stdout.writeln('wrote ${file.path}');
    } else if (file.existsSync()) {
      file.deleteSync();
      stdout.writeln('removed ${file.path}');
    }
  }

  var ok = true;
  for (final t in targets) {
    if (!await _pubGet(t)) ok = false;
  }

  stdout.writeln('');
  _printStatus();
  if (!ok) {
    stderr.writeln(
      '\nAt least one `pub get` failed — the targets are NOT in a consistent '
      'state. Fix the reported error and re-run the same command.',
    );
    if (pass) await _restoreAll();
    return 1;
  }
  if (!pass) return 0;

  stdout.writeln('\nPRE-PUBLISH PASS — gates against the working tree:\n');
  List<String> failed;
  try {
    failed = await _runGates();
  } finally {
    // RESTORED WHATEVER HAPPENED. A failed gate that also leaves the tree
    // path-resolved is strictly worse than not having run the pass: the next
    // command anybody types — a corpus run, a `flutter test`, a publish dry
    // run — then measures unpublished code without saying so. The restore is
    // the one step that must not depend on the outcome.
    stdout.writeln('\nrestoring hosted resolution …');
    await _restoreAll();
  }

  stdout.writeln('');
  if (failed.isEmpty) {
    stdout.writeln(
      'PRE-PUBLISH PASS: clean. Nothing here was recorded as a verification '
      'run, and must not be — it measured a version nobody can install.\n'
      'If this publish changes NAME RESOLUTION, the base corpus is still owed '
      'before it: re-run with --set, drive both twins serially, then '
      '--restore.',
    );
    return 0;
  }
  stderr.writeln(
    'PRE-PUBLISH PASS: ${failed.length} gate(s) FAILED — do not publish.\n'
    '  ${failed.join('\n  ')}\n\n'
    'These ran against the working tree, so a failure here is a defect the '
    'publish would have shipped and no downstream suite could have reported '
    'first. Hosted resolution has been restored.',
  );
  return 1;
}

/// Removes every override and re-resolves, reporting but not throwing.
Future<void> _restoreAll() async {
  for (final t in targets) {
    final file = _overrideOf(t);
    if (file.existsSync()) {
      file.deleteSync();
      stdout.writeln('removed ${file.path}');
    }
  }
  for (final t in targets) {
    await _pubGet(t);
  }
}
