name: tom_d4rt_ast
description: Serializable AST model for Dart code interpretation without analyzer dependency.
version: 0.19.0
repository: https://github.com/al-the-bear/tom_d4rt
homepage: https://github.com/al-the-bear/tom_d4rt/tree/main/tom_d4rt_ast
topics:
  - ast
  - interpreter
  - d4rt
  - dart

environment:
  sdk: ^3.10.4

dependencies:
  archive: ^4.0.9
  tom_ast_model: ">=0.2.0"

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
