/// Writes the bundle fixture tom_d4rt_ast's browser test decodes and runs.
///
/// The fixture is what a real deployment ships: source parsed by the analyzer
/// front end on a host, bundled, and gzip-compressed with the NATIVE `dart:io`
/// codec. `tom_d4rt_ast/test/web/bundle_in_browser_test.dart` then decodes it
/// with the pure-Dart codec `package:archive` uses on the web and executes it.
/// A hand-built bundle compressed in the browser would prove only that the web
/// codec agrees with itself.
///
/// The output is a persisted artifact, like any shipped `.ast` bundle, so it is
/// NOT regenerated on every release: a bundle written by an older build must
/// still load. Re-run this only when the fixture's script has to change.
///
///     cd tom_d4rt_exec && dart run tool/write_web_bundle_fixture.dart
library;

import 'dart:convert';
import 'dart:io';

import 'package:tom_d4rt_exec/d4rt.dart';

/// Two modules, so the fixture also exercises cross-module resolution, and a
/// class, a closure, a loop, a record and interpolation, so it is a program
/// rather than a literal.
const _helper = r'''
class Counter {
  int _n = 0;
  void add(int by) => _n += by;
  int get value => _n;
}

String describe(List<int> xs) => xs.map((x) => 'x$x').join(',');
''';

const _main = r'''
import 'package:web_fixture/helper.dart';

String main() {
  final c = Counter();
  for (final x in [1, 2, 3, 4]) {
    c.add(x * x);
  }
  final r = (total: c.value, label: describe([1, 2]));
  return '${r.label}=${r.total}';
}
''';

const _expected = 'x1,x2=30';
const _target = '../tom_d4rt_ast/test/web/support/bundle_fixture.dart';

Future<void> main() async {
  final bundle = await D4rt().createBundleFromSource(
    _main,
    sourcePath: 'package:web_fixture/main.dart',
    explicitSources: const {'package:web_fixture/helper.dart': _helper},
  );

  // Executed here first, so a fixture that does not produce its expected value
  // is never written.
  final result = D4rt().executeBundle(bundle);
  if (result != _expected) {
    stderr.writeln('fixture returned $result, expected $_expected');
    exit(1);
  }

  final bytes = gzip.encode(utf8.encode(jsonEncode(bundle.toJson())));
  final out = StringBuffer()
    ..writeln(
      '// GENERATED by tom_d4rt_exec/tool/write_web_bundle_fixture.dart',
    )
    ..writeln(
      '// on ${DateTime.now().toUtc().toIso8601String()} — do not edit.',
    )
    ..writeln('//')
    ..writeln(
      '// An AstBundle the analyzer front end produced from the script in',
    )
    ..writeln(
      '// that tool, gzip-compressed by the native dart:io codec. It is a',
    )
    ..writeln('// persisted artifact: keep it loading, do not regenerate it to')
    ..writeln('// make a test pass.')
    ..writeln('library;')
    ..writeln()
    ..writeln('/// What the fixture\'s `main` returns.')
    ..writeln("const String fixtureExpectedResult = '$_expected';")
    ..writeln()
    ..writeln('/// The entry point the bundle declares.')
    ..writeln("const String fixtureEntryPoint = '${bundle.entryPointUri}';")
    ..writeln()
    ..writeln('/// The gzip bytes (${bytes.length}).')
    ..writeln('const List<int> fixtureBundleGzip = <int>[');
  for (var i = 0; i < bytes.length; i += 16) {
    final end = i + 16 < bytes.length ? i + 16 : bytes.length;
    out.writeln('  ${bytes.sublist(i, end).join(', ')},');
  }
  out.writeln('];');

  File(_target)
    ..parent.createSync(recursive: true)
    ..writeAsStringSync(out.toString());
  stdout.writeln('wrote $_target (${bytes.length} gzip bytes)');
}
