# D4rt Bridge Generator Configuration for tom_d4rt_dcli
# 
# This file configures bridge generation for dcli and VS Code scripting API.
# Run with: dart run build_runner build --delete-conflicting-outputs

targets:
  $default:
    builders:
      # Cleanup builder - removes generated files
      tom_cleanup_builder:cleanup_builder:
        enabled: true
        options:
          cleanup:
            - 'lib/src/bridges_trigger.g.dart'
      
      tom_d4rt_generator:d4rt_bridge_builder:
        enabled: true
        options:
          name: tom_d4rt_dcli
          helpersImport: package:tom_d4rt/tom_d4rt.dart
          
          # Generate master barrel files
          generateBarrel: true
          barrelPath: lib/d4rt_bridges.b.dart
          generateDartscript: true
          dartscriptPath: lib/dartscript.b.dart
          registrationClass: TomD4rtDcliBridge
          
          modules:
            # CLI API - D4rt CLI scripting API
            - name: cli_api
              barrelFiles:
                - package:tom_d4rt_dcli/tom_d4rt_cli_api.dart
              barrelImport: package:tom_d4rt_dcli/tom_d4rt_cli_api.dart
              outputPath: lib/src/bridges/cli_api_bridges.b.dart
              followAllReExports: false

            # Tom VS Code Scripting API - VS Code API wrappers
            - name: tom_vscode_scripting_api
              barrelFiles:
                - package:tom_vscode_scripting_api/script_globals.dart
              barrelImport: package:tom_vscode_scripting_api/script_globals.dart
              outputPath: lib/src/bridges/tom_vscode_scripting_api_bridges.b.dart
              excludePatterns:
                - "**/*_bridge.dart"
                - "**/*_generated.dart"
              excludeClasses: []

            # DCli - CLI scripting utilities from pub.dev
            - name: dcli
              barrelFiles:
                - package:dcli/dcli.dart
              outputPath: lib/src/bridges/dcli_bridges.b.dart
              # Don't follow re-exports - dcli re-exports from crypto/dcli_core
              # which aren't accessible via the main barrel import
              followAllReExports: false
              excludePatterns:
                - "**/*_bridge.dart"
                - "**/*_generated.dart"
              excludeClasses:
                # Crypto classes not exported from dcli barrel
                - Hmac
                - Cat
                - Hash
                - Digest
                # dcli_core classes not re-exported by dcli.dart
                - WhichSearch
                - Which
                - LineFile
                - FileSync
                - CopyTreeException
                - DCliFunctionException
                - HeadException
                - TailException
                - TouchException
                - BackupFileException
                - RestoreFileException
                - CatException
                - FindAsync
                - DCliFunction
                - LimitedStreamController
                # Progress uses LineAction type which causes import issues
                - Progress
                # Settings has methods (captureLogOutput, clearLogCapture, frame, listener) 
                # from dcli_core that aren't in dcli's re-exported Settings
                - Settings
              excludeFunctions:
                # Functions not exported from dcli barrel
                - dartSdkNotFound
                - capturePrinterrKey
                - withFileProtectionAsync
                - withTempDirAsync
                - withEnvironment
                - findAsync
                - withTempFileAsync
                - withOpenLineFile
                - sleepAsync
                - isTerminalDumb
                - searchForCommandExtension
                - findExtension
                # cat uses LineAction parameter which causes ext_dcli_core import issues
                - cat
                # which uses Sink<String> (WhichSearch callback) - type mismatch
                - which
                # withOpenFile uses FileSync type which isn't exported from dcli
                - withOpenFile
              excludeVariables:
                # Crypto hash constants - re-exported but not directly accessible
                - md5
                - sha1
                - sha256
                - sha224
                - sha384
                - sha512
                - sha512224
                - sha512256
                # Other variables not exported from main barrel
                - dartSdkNotFound
                - capturePrinterrKey
