# D4rt Bridge Generator Configuration for tom_d4rt_dcli
# 
# This file configures bridge generation for dcli and VS Code scripting API.
# Run with: dart run build_runner build --delete-conflicting-outputs

targets:
  $default:
    builders:
      # Cleanup builder - removes generated files
      tom_cleanup_builder:cleanup_builder:
        enabled: true
        options:
          cleanup:
            - 'lib/src/bridges_trigger.g.dart'
      
      tom_d4rt_generator:d4rt_bridge_builder:
        enabled: true
        options:
          name: tom_d4rt_dcli
          helpersImport: package:tom_d4rt/tom_d4rt.dart
          
          # Generate master barrel files
          generateBarrel: true
          barrelPath: lib/d4rt_bridges.b.dart
          generateDartscript: true
          dartscriptPath: lib/dartscript.b.dart
          registrationClass: TomD4rtDcliBridge
          
          modules:
            # CLI API - D4rt CLI scripting API
            - name: cli_api
              barrelFiles:
                - package:tom_d4rt_dcli/tom_d4rt_cli_api.dart
              barrelImport: package:tom_d4rt_dcli/tom_d4rt_cli_api.dart
              outputPath: lib/src/bridges/cli_api_bridges.b.dart
              followAllReExports: false

            # Tom VS Code Scripting API - VS Code API wrappers
            - name: tom_vscode_scripting_api
              barrelFiles:
                - package:tom_vscode_scripting_api/script_globals.dart
              barrelImport: package:tom_vscode_scripting_api/script_globals.dart
              outputPath: lib/src/bridges/tom_vscode_scripting_api_bridges.b.dart
              excludePatterns:
                - "**/*_bridge.dart"
                - "**/*_generated.dart"
              excludeClasses: []
              
            # DCli - Full dcli package with additional utilities
            - name: dcli
              barrelFiles:
                - package:dcli/dcli.dart
                - package:dcli_core/dcli_core.dart
              barrelImport: package:dcli/dcli.dart
              outputPath: lib/src/bridges/dcli_bridges.b.dart
              followAllReExports: false
              skipReExports:
                - dcli_core
                - crypto
              excludePatterns:
                - "**/*_bridge.dart"
                - "**/*_generated.dart"

