# D4rt Bridge Generator Configuration for tom_d4rt_dcli
# 
# This file configures bridge generation for dcli and VS Code scripting API.
# Run with: dart run build_runner build --delete-conflicting-outputs

targets:
  $default:
    builders:
      # Version builder - generates version.g.dart with build info
      tom_build_kit:version_builder:
        enabled: true
        options:
          output: lib/src/version.g.dart
          includeGitCommit: true
          variablePrefix: dcli
      
      tom_d4rt_generator:d4rt_bridge_builder:
        enabled: true
        options:
          name: tom_d4rt_dcli
          helpersImport: package:tom_d4rt/tom_d4rt.dart
          
          # Generate master barrel files
          generateBarrel: true
          barrelPath: lib/d4rt_bridges.b.dart
          generateDartscript: true
          dartscriptPath: lib/dartscript.b.dart
          registrationClass: TomD4rtDcliBridge
          
          modules:
            # CLI API - D4rt CLI scripting API
            - name: cli_api
              barrelFiles:
                - package:tom_d4rt_dcli/tom_d4rt_cli_api.dart
              barrelImport: package:tom_d4rt_dcli/tom_d4rt_cli_api.dart
              outputPath: lib/src/bridges/cli_api_bridges.b.dart
              followAllReExports: false

            # Tom VS Code Scripting API - VS Code API wrappers
            - name: tom_vscode_scripting_api
              barrelFiles:
                - package:tom_vscode_scripting_api/script_globals.dart
              barrelImport: package:tom_vscode_scripting_api/script_globals.dart
              outputPath: lib/src/bridges/tom_vscode_scripting_api_bridges.b.dart
              excludePatterns:
                - "**/*_bridge.dart"
                - "**/*_generated.dart"
              excludeClasses: []
              
            # DCli - Full dcli package with additional utilities
            - name: dcli
              barrelFiles:
                - package:dcli/dcli.dart
                - package:dcli_core/dcli_core.dart
              barrelImport: package:dcli/dcli.dart
              outputPath: lib/src/bridges/dcli_bridges.b.dart
              #followAllReExports: false
              #skipReExports:
              #  - dcli_core
              #  - crypto
              #excludePatterns:
              #  - "**/*_bridge.dart"
              #  - "**/*_generated.dart"
              followAllReExports: true
              excludePatterns:
                - "**/*_bridge.dart"
                - "**/*_generated.dart"
              excludeSourcePatterns:
                - "package:dcli_core/src/settings.dart#Settings,verbose"
                - "package:dcli_core/src/util/file.dart#FileNotFoundException,NotAFileException,withOpenFile,symlink,deleteSymlink,resolveSymLink,stat,createTempFilename,createTempFile,fileLength,calculateHash"
                - "package:dcli_core/src/functions/backup.dart#backupFile,restoreFile"
                - "package:dcli_core/src/functions/cat.dart#cat"
                - "package:dcli_core/src/functions/copy.dart#copy"
                - "package:dcli_core/src/functions/copy_tree.dart#copyTree"
                - "package:dcli_core/src/functions/create_dir.dart#createDir,createTempDir"
                - "package:dcli_core/src/functions/delete.dart#delete"
                - "package:dcli_core/src/functions/delete_dir.dart#deleteDir"
                - "package:dcli_core/src/functions/find.dart#find"
                - "package:dcli_core/src/functions/head.dart#head"
                - "package:dcli_core/src/functions/is.dart#isFile,isDirectory,isLink,exists,lastModified,setLastModifed,isEmpty"
                - "package:dcli_core/src/functions/move.dart#move"
                - "package:dcli_core/src/functions/move_dir.dart#moveDir"
                - "package:dcli_core/src/functions/move_tree.dart#moveTree"
                - "package:dcli_core/src/functions/tail.dart#tail"
                - "package:dcli_core/src/functions/touch.dart#touch"
                - "package:dcli_core/src/functions/which.dart#which"

            # Tom ChatTools - Telegram and other messaging platform APIs
            - name: tom_chattools
              barrelFiles:
                - package:tom_chattools/tom_chattools.dart
              barrelImport: package:tom_chattools/tom_chattools.dart
              outputPath: lib/src/bridges/tom_chattools_bridges.b.dart
              followAllReExports: false
              excludePatterns:
                - "**/*_bridge.dart"
                - "**/*_generated.dart"
