# Build configuration for tom_d4rt_dcli
#
# Version builder generates version.g.dart with build info.
# D4rt bridge configuration is in tom_build.yaml (d4rtgen: section).

targets:
  $default:
    builders:
      # Version builder - generates version.g.dart with build info
      tom_build_kit:version_builder:
        enabled: true
        options:
          output: lib/src/version.g.dart
          includeGitCommit: true
          variablePrefix: dcli
