// D4rt test script: Tests KeyRepeatEvent from services
import 'package:flutter/services.dart';
import 'package:flutter/material.dart';

dynamic build(BuildContext context) {
  print('KeyRepeatEvent test executing');
  print('=' * 50);

  // Create KeyRepeatEvent for a letter key
  final repeatA = KeyRepeatEvent(
    physicalKey: PhysicalKeyboardKey.keyA,
    logicalKey: LogicalKeyboardKey.keyA,
    character: 'a',
    timeStamp: Duration(milliseconds: 600),
  );
  print('\nKeyRepeatEvent for key A:');
  print('runtimeType: ${repeatA.runtimeType}');
  print('physicalKey: ${repeatA.physicalKey}');
  print('logicalKey: ${repeatA.logicalKey}');
  print('character: "${repeatA.character}"');
  print('timeStamp: ${repeatA.timeStamp}');

  // Difference from KeyDownEvent
  print('\nKeyRepeatEvent vs KeyDownEvent:');
  print('KeyDownEvent: fires once when key is pressed');
  print('KeyRepeatEvent: fires repeatedly while key is held');

  // Test inherited KeyEvent properties
  print('\nInherited KeyEvent properties:');
  print('synthesized: ${repeatA.synthesized}');

  // Create for arrow key
  final repeatArrow = KeyRepeatEvent(
    physicalKey: PhysicalKeyboardKey.arrowDown,
    logicalKey: LogicalKeyboardKey.arrowDown,
    timeStamp: Duration(milliseconds: 800),
  );
  print('\nArrow key repeat:');
  print('physicalKey: ${repeatArrow.physicalKey}');
  print('character: ${repeatArrow.character ?? "null"}');

  // Create for backspace
  final repeatBackspace = KeyRepeatEvent(
    physicalKey: PhysicalKeyboardKey.backspace,
    logicalKey: LogicalKeyboardKey.backspace,
    timeStamp: Duration(milliseconds: 1000),
  );
  print('\nBackspace repeat:');
  print('physicalKey: ${repeatBackspace.physicalKey}');
  print('Typical use: delete multiple characters');

  // Simulating repeated keypresses
  print('\nSimulated key repeat sequence:');
  final repeats = [
    KeyRepeatEvent(
      physicalKey: PhysicalKeyboardKey.keyA,
      logicalKey: LogicalKeyboardKey.keyA,
      character: 'a',
      timeStamp: Duration(milliseconds: 500),
    ),
    KeyRepeatEvent(
      physicalKey: PhysicalKeyboardKey.keyA,
      logicalKey: LogicalKeyboardKey.keyA,
      character: 'a',
      timeStamp: Duration(milliseconds: 530),
    ),
    KeyRepeatEvent(
      physicalKey: PhysicalKeyboardKey.keyA,
      logicalKey: LogicalKeyboardKey.keyA,
      character: 'a',
      timeStamp: Duration(milliseconds: 560),
    ),
  ];
  for (int i = 0; i < repeats.length; i++) {
    print('Repeat ${i + 1}: ${repeats[i].timeStamp}');
  }

  // Test type hierarchy
  print('\nType hierarchy:');
  print('is KeyEvent: ${repeatA is KeyEvent}');
  print('is Object: ${repeatA is Object}');

  // Repeat rate explanation
  print('\nKey repeat behavior:');
  print('- Initial delay: ~500ms after key down');
  print('- Repeat interval: ~30ms between repeats');
  print('- OS-dependent timing');
  print('- Useful for text input and navigation');

  // Explain purpose
  print('\nKeyRepeatEvent purpose:');
  print('- Represents repeated key press while holding');
  print('- Part of KeyEvent hierarchy');
  print('- physicalKey: hardware key location');
  print('- logicalKey: semantic key meaning');
  print('- Generated by OS when key is held');
  print('- Enables continuous text input/scrolling');

  print('\n' + '=' * 50);
  print('KeyRepeatEvent test completed');
  return Column(
    mainAxisSize: MainAxisSize.min,
    children: [
      Text(
        'KeyRepeatEvent Tests',
        style: TextStyle(fontWeight: FontWeight.bold, fontSize: 18),
      ),
      SizedBox(height: 8),
      Text('Type: ${repeatA.runtimeType}'),
      Text('physicalKey: ${repeatA.physicalKey.debugName}'),
      Text('character: "${repeatA.character}"'),
      Text('is KeyEvent: ${repeatA is KeyEvent}'),
      Text('Purpose: Repeated key press'),
    ],
  );
}
